"use client"

import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { PosDialogMessages } from "./pos-dialog-messages"
import { ArrowDownToLine, ArrowUpFromLine, Check, HandCoins, LockKeyhole, X } from "lucide-react"

type Currency = { currency_id: number; currency_code: string; currency_name: string; rate_to_point: number }
type Session = { movement_totals?: Array<{ movement_type: string; amount: number }>; shift_guid?: string; opening_cash: number; expected_cash: number; opened_at?: string; payments?: Array<{ payment_method: string; amount: number; sale_amount?: number; refund_amount?: number }>; currencies?: Array<{ currency_id: number; expected_amount: number; currency_code: string; rate_to_point?: number }>; movements?: Array<{ id: number; movement_type: string; currency_code?: string; currency_amount?: number; amount: number; created_at?: string; note?: string }> }
type Props = { open: boolean; onOpenChange: (open: boolean) => void; session: Session | null; userName: string; currencyCode: string; currencies: Currency[]; action: string; onActionChange: (action: string) => void; amount: number; onAmountChange: (amount: number) => void; currencyId: number; onCurrencyIdChange: (id: number) => void; amounts: Record<number, number>; onCurrencyAmountChange: (id: number, amount: number) => void; movementAmounts: Record<number, number>; onMovementAmountChange: (id: number, amount: number) => void; note: string; onNoteChange: (value: string) => void; onConfirm: () => void; busy: boolean; error?: string }
const money = (value: number) => Number(value || 0).toFixed(2)
const methods = [{ key: "cash", label: "الفواتير النقدية" }, { key: "cheque", label: "الشيكات" }, { key: "card", label: "البطاقات" }, { key: "account", label: "الذمم" }, { key: "gift_card", label: "بطاقات الهدايا" }]
const actions = [{ key: "handover", label: "تسليم العهدة", icon: HandCoins }, { key: "cash_in", label: "إيداع", icon: ArrowDownToLine }, { key: "cash_out", label: "سحب", icon: ArrowUpFromLine }, { key: "close", label: "إغلاق الوردية", icon: LockKeyhole }]
const movementLabels: Record<string, string> = { opening: "فتح الوردية", receive: "استلام العهدة", sale: "بيع", refund: "مردود", cash_in: "إيداع", cash_out: "سحب", handover: "تسليم العهدة", close: "إغلاق الوردية" }

export function PosHandoverDialog(p: Props) {
  const { open, onOpenChange, session, userName, currencyCode, currencies, action, onActionChange, amounts, onCurrencyAmountChange, movementAmounts, onMovementAmountChange, note, onNoteChange, onConfirm, busy, error } = p
  const closing = action === "close"
  const payments = session?.payments || []
  const sales = (method: string) => payments.filter(row => row.payment_method === method).reduce((sum, row) => sum + Number(row.sale_amount ?? row.amount ?? 0), 0)
  const refunds = (method: string) => payments.filter(row => row.payment_method === method).reduce((sum, row) => sum + Number(row.refund_amount || 0), 0)
  const totalSales = methods.reduce((sum, row) => sum + sales(row.key), 0)
  const totalRefunds = methods.reduce((sum, row) => sum + refunds(row.key), 0)
  const netCashSales = sales("cash") - refunds("cash")
  const available = (id: number) => Number(session?.currencies?.find(row => row.currency_id === id)?.expected_amount || 0)
  const rate = (id: number) => Number(session?.currencies?.find(row => row.currency_id === id)?.rate_to_point || currencies.find(row => row.currency_id === id)?.rate_to_point || 1)
  const totalEntered = currencies.reduce((sum, row) => sum + Number(amounts[row.currency_id] || 0) * rate(row.currency_id), 0)
  const validAmount = (value: number) => Number.isFinite(value) && value >= 0 && Math.abs(value * 100 - Math.round(value * 100)) < 0.000001
  const valid = action === "handover" || closing
    ? currencies.length > 0 && currencies.every(row => { const value = Number(amounts[row.currency_id] ?? 0); return validAmount(value) && (closing || value <= available(row.currency_id) + 0.009) })
    : currencies.some(row => Number(movementAmounts[row.currency_id] || 0) > 0) && currencies.every(row => { const value = Number(movementAmounts[row.currency_id] || 0); return validAmount(value) && (action !== "cash_out" || value <= available(row.currency_id) + 0.009) })
  const movements = session?.movements || []
  const movementTotal = (type: string) => (session?.movement_totals || movements).filter(row => row.movement_type === type).reduce((sum, row) => sum + Number(row.amount || 0), 0)
  const totalRequired = Math.round((Number(session?.opening_cash || 0) + netCashSales + movementTotal("cash_in") - movementTotal("cash_out")) * 100) / 100
  const difference = Math.round((totalEntered - totalRequired) * 100) / 100
  const totalsSummary = <div className="space-y-3 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold dark:border-emerald-900 dark:bg-emerald-950/30" aria-live="polite">
    <div className="flex items-center justify-between gap-3"><span>إجمالي المبلغ المعدود ({currencyCode})</span><strong dir="ltr" className="text-lg tabular-nums">{money(totalEntered)}</strong></div>
    <div className="flex items-center justify-between gap-3"><span>إجمالي المبلغ المطلوب ({currencyCode})</span><strong dir="ltr" className="text-lg tabular-nums">{money(totalRequired)}</strong></div>
    <div className={"flex items-center justify-between gap-3 border-t border-emerald-200 pt-3 dark:border-emerald-900 " + (difference > 0 ? "text-green-700 dark:text-green-400" : difference < 0 ? "text-red-600 dark:text-red-400" : "text-slate-700 dark:text-slate-200")}><span>الفرق ({currencyCode})</span><strong dir="ltr" className="text-lg tabular-nums">{difference > 0 ? "+" : ""}{money(difference)}</strong></div>
  </div>

  return <Dialog open={open} onOpenChange={onOpenChange}>
    <DialogContent dir="rtl" className="flex h-[calc(100%-1.5rem)] max-h-[760px] w-[calc(100%-1.5rem)] max-w-[920px] flex-col gap-0 overflow-hidden rounded-2xl border border-slate-200 bg-white p-0 shadow-2xl sm:rounded-3xl dark:border-slate-800 dark:bg-slate-950" onKeyDown={event => { if (event.key === "F3") { event.preventDefault(); if (valid && !busy) onConfirm() } }}>
      <DialogHeader className="shrink-0 border-b border-emerald-700/20 bg-gradient-to-l from-emerald-700 via-teal-700 to-sky-700 px-6 py-5 text-right text-white">
        <div className="flex items-center gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-white/15 ring-1 ring-white/25">{closing ? <LockKeyhole className="size-5" /> : <HandCoins className="size-5" />}</span><div><DialogTitle className="text-lg font-bold text-white">{closing ? "إغلاق الوردية" : "تسليم العهدة"}</DialogTitle><DialogDescription className="mt-1 text-xs text-emerald-50">{closing ? "المبلغ المعدود حسب المبالغ المدخلة في تفاصيل التسليم حسب العملة" : "إدارة عهدة الوردية والأرصدة حسب العملة"}</DialogDescription></div></div>
      </DialogHeader>
      <PosDialogMessages error={error} open={open} />
      <div className="min-h-0 space-y-5 overflow-y-auto bg-slate-50/70 p-4 sm:p-6 dark:bg-slate-950">
        <div className="flex max-w-full gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm dark:border-slate-800 dark:bg-slate-900">{actions.map(row => <Button key={row.key} type="button" size="sm" variant="ghost" onClick={() => onActionChange(row.key)} className={`shrink-0 rounded-xl px-4 ${action === row.key ? "bg-emerald-600 text-white shadow-sm hover:bg-emerald-700 hover:text-white" : "text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800"}`}><row.icon className="ml-2 size-4" />{row.label}</Button>)}</div>
        {closing ? <section className="rounded-2xl border border-emerald-200 bg-gradient-to-bl from-emerald-50 to-white p-5 shadow-sm dark:border-emerald-900 dark:from-emerald-950/30 dark:to-slate-900">
          <h3 className="mb-4 flex items-center gap-2 text-sm font-bold text-slate-900 dark:text-white"><span className="flex size-8 items-center justify-center rounded-xl bg-emerald-600 text-white"><LockKeyhole className="size-4" /></span>المبلغ المعدود</h3>
          <div className="grid gap-4 sm:grid-cols-2">{currencies.map(row => <div key={row.currency_id} className="min-w-0 rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900"><Label htmlFor={`counted-${row.currency_id}`} className="mb-2 block text-xs font-semibold text-slate-600 dark:text-slate-300">{row.currency_name} ({row.currency_code})</Label><Input id={`counted-${row.currency_id}`} aria-label={`المبلغ المعدود ${row.currency_code}`} type="text" readOnly disabled value={money(Number(amounts[row.currency_id] ?? 0))} className="h-11 rounded-xl border-slate-200 bg-slate-50 text-left text-lg font-bold tabular-nums disabled:cursor-default disabled:opacity-100 dark:border-slate-700 dark:bg-slate-950" dir="ltr" /></div>)}</div>
          <div className="mt-4">{totalsSummary}</div>
        </section> : <>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[{ label: "رقم الوردية", value: session?.shift_guid || "" }, { label: "تاريخ العملية", value: new Date().toLocaleString("en-GB") }, { label: "المستخدم", value: userName }, { label: "الرصيد الافتتاحي", value: `${money(Number(session?.opening_cash || 0))} ${currencyCode}` }, { label: "مجموع المبيعات", value: `${money(totalSales)} ${currencyCode}` }, { label: "الرصيد المتوقع", value: `${money(Number(session?.expected_cash || 0))} ${currencyCode}` }].map(card => <div key={card.label} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-2 text-xs text-slate-500 dark:text-slate-400">{card.label}</div><div className="truncate text-sm font-bold text-slate-900 dark:text-white" title={card.value}>{card.value}</div></div>)}</div>
          {action === "handover" ? <>
            <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="border-b border-slate-100 px-4 py-3 text-sm font-bold dark:border-slate-800">ملخص حركة الوردية</h3><div className="overflow-x-auto"><table className="w-full min-w-[540px] text-xs"><thead className="bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><tr><th className="p-3 text-right">التفاصيل</th><th className="p-3 text-center">المبيعات</th><th className="p-3 text-center">المردودات</th><th className="p-3 text-center">الصافي</th></tr></thead><tbody>{methods.map(row => <tr key={row.key} className="border-t border-slate-100 dark:border-slate-800"><th className="p-3 text-right font-medium">{row.label}</th><td className="p-3 text-center">{money(sales(row.key))}</td><td className="p-3 text-center">{money(refunds(row.key))}</td><td className="p-3 text-center">{money(sales(row.key) - refunds(row.key))}</td></tr>)}<tr className="border-t border-emerald-200 bg-emerald-50 font-bold text-emerald-900 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"><th className="p-3 text-right">المجموع</th><td className="p-3 text-center">{money(totalSales)}</td><td className="p-3 text-center">{money(totalRefunds)}</td><td className="p-3 text-center">{money(totalSales - totalRefunds)}</td></tr></tbody></table></div></section>
            <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="border-b border-slate-100 px-4 py-3 text-sm font-bold dark:border-slate-800">تفاصيل التسليم حسب العملة</h3><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-xs"><thead className="bg-sky-50 text-sky-900 dark:bg-sky-950/30 dark:text-sky-100"><tr><th className="p-3 text-right">العملة</th><th className="p-3 text-center">الرصيد المتاح</th><th className="p-3 text-center">المبلغ المسلم</th><th className="p-3 text-center">سعر الصرف</th><th className="p-3 text-center">المبلغ المقيم</th></tr></thead><tbody>{currencies.map(row => <tr key={row.currency_id} className="border-t border-slate-100 dark:border-slate-800"><th className="p-3 text-right font-medium">{row.currency_name} · {row.currency_code}</th><td className="p-3 text-center">{money(available(row.currency_id))}</td><td className="p-2"><Input aria-label={`المبلغ المسلم ${row.currency_code}`} type="number" min="0" max={available(row.currency_id)} step="0.01" value={amounts[row.currency_id] ?? 0} onChange={event => onCurrencyAmountChange(row.currency_id, Number(event.target.value))} className="h-9 min-w-24 rounded-lg text-center" /></td><td className="p-3 text-center">{rate(row.currency_id).toFixed(4)}</td><td className="p-3 text-center font-bold">{money(Number(amounts[row.currency_id] || 0) * rate(row.currency_id))}</td></tr>)}</tbody></table></div></section>
            {totalsSummary}
          </> : <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="border-b border-slate-100 px-4 py-3 text-sm font-bold dark:border-slate-800">{action === "cash_in" ? "تفاصيل الإيداع" : "تفاصيل السحب"}</h3><div className="overflow-x-auto"><table className="w-full min-w-[440px] text-xs"><thead className="bg-sky-50 text-sky-900 dark:bg-sky-950/30 dark:text-sky-100"><tr><th className="p-3 text-right">العملة</th><th className="p-3 text-center">الرصيد المتاح</th><th className="p-3 text-center">{action === "cash_in" ? "مبلغ الإيداع" : "مبلغ السحب"}</th><th className="p-3 text-center">المبلغ المقيم ({currencyCode})</th></tr></thead><tbody>{currencies.map(row => <tr key={row.currency_id} className="border-t border-slate-100 dark:border-slate-800"><th className="p-3 text-right">{row.currency_code} · {row.currency_name}</th><td className="p-3 text-center">{money(available(row.currency_id))}</td><td className="p-2"><Input aria-label={`${action === "cash_in" ? "إيداع" : "سحب"} ${row.currency_code}`} type="number" min="0" max={action === "cash_out" ? available(row.currency_id) : undefined} step="0.01" value={movementAmounts[row.currency_id] ?? 0} onChange={event => onMovementAmountChange(row.currency_id, Number(event.target.value))} className="h-9 min-w-24 rounded-lg text-center" /></td><td className="p-3 text-center">{money(Number(movementAmounts[row.currency_id] || 0) * rate(row.currency_id))}</td></tr>)}</tbody></table></div></section>}
        </>}
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2 border-b border-slate-100 px-4 py-3 dark:border-slate-800"><span className="size-2 rounded-full bg-emerald-500" /><h3 className="text-sm font-bold text-slate-900 dark:text-white">سجل العهدة في هذه الوردية</h3></div><div className="max-h-64 overflow-auto"><table className="w-full min-w-[540px] text-xs"><thead className="sticky top-0 bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><tr><th className="p-3 text-right">التاريخ والوقت</th><th className="p-3 text-right">العملية</th><th className="p-3 text-right">العملة</th><th className="p-3 text-left">المبلغ</th><th className="p-3 text-right">ملاحظات</th></tr></thead><tbody>{movements.map(row => <tr key={row.id} className="border-t border-slate-100 dark:border-slate-800"><td dir="ltr" className="p-3 text-right text-slate-500 dark:text-slate-400">{row.created_at ? new Date(row.created_at).toLocaleString("en-GB") : "—"}</td><td className="p-3 font-medium">{movementLabels[row.movement_type] || row.movement_type}</td><td className="p-3">{row.currency_code || currencyCode}</td><td dir="ltr" className="p-3 text-left font-bold tabular-nums">{money(Number(row.currency_amount ?? row.amount))}</td><td className="max-w-48 truncate p-3 text-slate-500" title={row.note || ""}>{row.note || "—"}</td></tr>)}</tbody></table>{movements.length === 0 && <p className="p-6 text-center text-xs text-slate-500">لا توجد حركات مسجلة في هذه الوردية</p>}</div></section>
        {!closing && <div className="space-y-2"><Label htmlFor="custody-note">ملاحظات</Label><Input id="custody-note" value={note} onChange={event => onNoteChange(event.target.value)} placeholder="أضف ملاحظة لهذه العملية (اختياري)" className="h-10 rounded-xl border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900" /></div>}
      </div>
      <div className="flex shrink-0 items-center gap-2 border-t border-slate-200 bg-white px-5 py-4 dark:border-slate-800 dark:bg-slate-950"><Button disabled={busy || !valid} onClick={onConfirm} className="min-w-28 rounded-xl bg-emerald-600 font-bold shadow-sm hover:bg-emerald-700"><Check className="ml-2 size-4" />موافق</Button><Button variant="outline" disabled={busy} onClick={() => onOpenChange(false)} className="rounded-xl"><X className="ml-2 size-4" />إلغاء</Button></div>
    </DialogContent>
  </Dialog>
}
