"use client"

import "./pos-workspace.css"
import {PosDiscountDialog} from "./pos-discount-dialog"
import {PosPartyPicker,PosPartyButton,type PosParty} from "./pos-party-picker"
import {PosStartSessionDialog} from "./pos-start-session-dialog"

import {useCallback,useEffect,useMemo,useRef,useState} from "react"
import {ArrowDownToLine,ArrowUpFromLine,Banknote,Barcode,Clock3,CreditCard,Gift,HandCoins,History,Minus,PackageOpen,Percent,Plus,Printer,RefreshCw,RotateCcw,Search,ShoppingBag,ShoppingCart,StickyNote,Trash2,UserRound,WalletCards,Warehouse,Wifi,WifiOff,X} from "lucide-react"
import {useAuth} from "@/components/auth/auth-context"
import {Button} from "@/components/ui/button"
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog"
import {Input} from "@/components/ui/input"
import {Label} from "@/components/ui/label"
import {cn} from "@/lib/utils"
import {currentPosTenantKey,listPosSales,loadPosCatalog,markPosSaleFailed,queuePosSale,removePosSale,savePosCatalog,type PosQueuedSale} from "@/lib/pos-offline"

type Product={id:number;code:string;name:string;barcode:string;price:number;unitId:number|null;unitName:string;accountId:number|null;returnAccountId:number|null;category:string;image?:string;available:number}
type CartLine=Product&{quantity:number;discount:number;gift:boolean}
type Customer={id:number;name:string;code?:string;accountId:number|null}
type Point=Record<string,any>&{id:number;name:string;code:string;warehouse_name:string;currency_name:string;currency_code:string}
type Session=Record<string,any>&{id:number;expected_cash:number;opening_cash:number;payments?:any[];movements?:any[]}
type Catalog={point:Point|null;products:Product[];customers:Customer[];salesmen?:PosParty[];session:Session|null}
type PaymentKey="cash"|"card"|"cheque"|"account"|"gift_card"
type Payment={method:PaymentKey;amount:number;reference:string;due_date?:string}
type Receipt={code:string;total:number;pending:boolean;lines:CartLine[];mode:"sale"|"return"}|null
const EMPTY:Catalog={point:null,products:[],customers:[],session:null}
const round=(n:number)=>Math.round(n*100)/100
const today=()=>new Date().toISOString().slice(0,10)
const makeId=()=>globalThis.crypto?.randomUUID?.()||`pos-${Date.now()}-${Math.random().toString(16).slice(2)}`
const paymentLabels:Record<PaymentKey,string>={cash:"نقدي",card:"بطاقة",cheque:"شيك",account:"على الحساب",gift_card:"بطاقة هدية"}
const paymentIcons:Record<PaymentKey,any>={cash:Banknote,card:CreditCard,cheque:WalletCards,account:UserRound,gift_card:Gift}
const errorText=(d:any,f:string)=>String(d?.error||d?.message||f)

export default function PosCashier(){
 const {user}=useAuth(),baseKey=useMemo(()=>currentPosTenantKey(user?.id),[user?.id]),searchRef=useRef<HTMLInputElement>(null),syncingRef=useRef(false)
 const [points,setPoints]=useState<Point[]>([]),[pointId,setPointId]=useState<number|null>(null),[catalog,setCatalog]=useState<Catalog>(EMPTY),[cart,setCart]=useState<CartLine[]>([]),[query,setQuery]=useState(""),[category,setCategory]=useState("all"),[customerId,setCustomerId]=useState<number|null>(null),[mode,setMode]=useState<"sale"|"return">("sale"),[note,setNote]=useState("")
 const [online,setOnline]=useState(true),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[pendingCount,setPendingCount]=useState(0),[message,setMessage]=useState<{type:"success"|"error"|"info";text:string}|null>(null),[receipt,setReceipt]=useState<Receipt>(null)
 const [checkoutOpen,setCheckoutOpen]=useState(false),[payments,setPayments]=useState<Payment[]>([]),[cashTendered,setCashTendered]=useState(0),[saving,setSaving]=useState(false),[custodyOpen,setCustodyOpen]=useState(false),[custodyAction,setCustodyAction]=useState("open"),[custodyAmount,setCustodyAmount]=useState(0),[custodyNote,setCustodyNote]=useState(""),[pendingHandovers,setPendingHandovers]=useState<any[]>([]),[discountOpen,setDiscountOpen]=useState(false),[discountValue,setDiscountValue]=useState(0),[noteOpen,setNoteOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[historyRows,setHistoryRows]=useState<any[]>([]),[historyQuery,setHistoryQuery]=useState("")
 const [selectedLineId,setSelectedLineId]=useState<number|null>(null),[quantityEntry,setQuantityEntry]=useState(""),[newSaleOpen,setNewSaleOpen]=useState(false)
 const applyQuantity=()=>{const quantity=Number(quantityEntry);if(!Number.isFinite(quantity)||quantity<=0)return;setCart(lines=>lines.map(line=>line.id===selectedLineId?{...line,quantity}:line))}
 const [noPoints,setNoPoints]=useState(false)
 const [partyPicker,setPartyPicker]=useState<"customer"|"salesman"|null>(null),[salesmanId,setSalesmanId]=useState<number|null>(null)
 const point=catalog.point,session=catalog.session
 const subtotal=useMemo(()=>round(cart.reduce((s,l)=>s+l.price*l.quantity*(1-l.discount/100),0)),[cart]),invoiceDiscount=round(subtotal*discountValue/100),tax=round((subtotal-invoiceDiscount)*Number(point?.tax_percent||0)/100),total=round(subtotal-invoiceDiscount+tax)
 const allocated=round(payments.reduce((s,p)=>s+p.amount,0)),change=round(Math.max(cashTendered-(payments.find(p=>p.method==="cash")?.amount||0),0))
 const categories=useMemo(()=>Array.from(new Set(catalog.products.map(p=>p.category).filter(Boolean))),[catalog.products])
 const shown=useMemo(()=>{const t=query.trim().toLocaleLowerCase("ar");return catalog.products.filter(p=>(category==="all"||p.category===category)&&(!t||`${p.code} ${p.barcode} ${p.name}`.toLocaleLowerCase("ar").includes(t))).slice(0,180)},[catalog.products,category,query])
 const updateQueue=useCallback(async()=>{try{setPendingCount((await listPosSales(baseKey)).length)}catch{setPendingCount(0)}},[baseKey])
 const normalize=(d:any):Catalog=>({point:d.point||null,session:d.session?{...d.session,expected_cash:Number(d.session.expected_cash||0),opening_cash:Number(d.session.opening_cash||0)}:null,products:(d.products||[]).map((r:any)=>({id:Number(r.id),code:String(r.product_code||""),name:String(r.product_name||"صنف"),barcode:String(r.first_barcode||r.barcode||""),price:Number(r.first_price||0),unitId:Number(r.unit_id)||null,unitName:String(r.unit_name||""),accountId:Number(r.selling_account_id)||null,returnAccountId:Number(r.selling_returns_account_id)||null,category:String(r.category_name||"غير مصنف"),image:r.product_image||undefined,available:Number(r.available_stock||0)})),salesmen:(d.salesmen||[]).map((r:any)=>({id:Number(r.id),code:String(r.code||""),name:String(r.name||"")})),customers:(d.customers||[]).map((r:any)=>({id:Number(r.id),name:String(r.name||""),code:String(r.code||""),accountId:Number(r.account_id)||null}))})
 const loadPoints=useCallback(async()=>{if(!navigator.onLine){const last=Number(localStorage.getItem(`${baseKey}:last-point`)||0);if(last)setPointId(last);return}try{const r=await fetch("/api/pos/points",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);setPoints(d.points||[]);setNoPoints(!d.points?.length);if(!d.points?.length){setCatalog(EMPTY);setLoading(false);setCustodyOpen(false)}const saved=Number(localStorage.getItem(`${baseKey}:last-point`)||0),next=(d.points||[]).find((p:any)=>p.id===saved)?.id||d.points?.[0]?.id||null;setPointId(next)}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"تعذر تحميل نقاط البيع"})}},[baseKey])
 const loadCatalogData=useCallback(async()=>{if(!pointId)return;setLoading(true);const key=`${baseKey}:point:${pointId}`,cached=await loadPosCatalog<Catalog>(key).catch(()=>null);if(cached?.catalog)setCatalog(cached.catalog);if(!navigator.onLine){if(!cached)setMessage({type:"error",text:"افتح نقطة البيع مرة أثناء الاتصال لتنزيل أصناف المخزن الرئيسي"});setLoading(false);return}try{const r=await fetch(`/api/pos/catalog?point_id=${pointId}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);const next=normalize(d);setCatalog(next);await savePosCatalog(key,next);localStorage.setItem(`${baseKey}:last-point`,String(pointId));setMessage(null)}catch(e){if(!cached)setMessage({type:"error",text:e instanceof Error?e.message:"تعذر تحميل الكاشير"})}finally{setLoading(false)}},[baseKey,pointId])
 const loadSession=useCallback(async()=>{if(!pointId||!navigator.onLine)return;try{const r=await fetch(`/api/pos/sessions?point_id=${pointId}`,{cache:"no-store"}),d=await r.json();if(r.ok){setCatalog(c=>({...c,session:d.session||null}));setPendingHandovers(d.pending||[]);return d}}catch{}},[pointId])
 const syncPending=useCallback(async()=>{if(!navigator.onLine||syncingRef.current)return;syncingRef.current=true;setSyncing(true);try{for(const sale of await listPosSales(baseKey)){try{const r=await fetch("/api/pos/sales",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(sale.payload)}),d=await r.json();if(!r.ok){await markPosSaleFailed(sale,errorText(d,"فشلت المزامنة"));continue}await removePosSale(sale.id)}catch(e){await markPosSaleFailed(sale,e instanceof Error?e.message:"انقطع الاتصال");break}}await updateQueue();await loadSession()}finally{syncingRef.current=false;setSyncing(false)}},[baseKey,loadSession,updateQueue])
 useEffect(()=>{setOnline(navigator.onLine);void loadPoints();void updateQueue();const on=()=>{setOnline(true);void syncPending();void loadPoints()},off=()=>setOnline(false);addEventListener("online",on);addEventListener("offline",off);return()=>{removeEventListener("online",on);removeEventListener("offline",off)}},[loadPoints,syncPending,updateQueue])
 useEffect(()=>{setCart([]);setDiscountValue(0);setCustomerId(null);setSalesmanId(null);setCategory("all");void loadCatalogData()},[loadCatalogData])
 useEffect(()=>{if(pointId&&catalog.point)void savePosCatalog(`${baseKey}:point:${pointId}`,catalog)},[baseKey,catalog,pointId])
 useEffect(()=>{if(custodyOpen)void loadSession()},[custodyOpen,loadSession])
 useEffect(()=>{if(!pointId||!catalog.point||!online)return;let active=true;void loadSession().then(data=>{if(active&&data&&!data.session){setCustodyAmount(0);setCustodyAction(data.pending?.length?"receive":"open");setCustodyOpen(true)}});return()=>{active=false}},[pointId,catalog.point?.id,online,loadSession])
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if(document.querySelector('[role="dialog"]'))return;if(e.key==="F2"){e.preventDefault();searchRef.current?.focus()}if(e.key==="F4"&&cart.length){e.preventDefault();openCheckout()}if(e.key==="F8"){e.preventDefault();setCustodyOpen(true)}};addEventListener("keydown",h);return()=>removeEventListener("keydown",h)},[cart.length,total])
 const add=(p:Product)=>{setSelectedLineId(p.id);setQuantityEntry(String((cart.find(l=>l.id===p.id)?.quantity||0)+1));setCart(c=>{const f=c.find(x=>x.id===p.id);return f?c.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x):[...c,{...p,quantity:1,discount:0,gift:false}]});setQuery("")}
 const changeQty=(id:number,n:number)=>setCart(c=>c.map(x=>x.id===id?{...x,quantity:Math.max(0,x.quantity+n)}:x).filter(x=>x.quantity>0))
 const searchEnter=()=>{const exact=catalog.products.find(p=>p.barcode===query.trim()||p.code===query.trim());if(exact)add(exact);else if(shown.length===1)add(shown[0])}
 const setPay=(method:PaymentKey,value:number,reference?:string,dueDate?:string)=>setPayments(rows=>{const exists=rows.find(p=>p.method===method),next={method,amount:Math.max(0,round(value)),reference:reference??exists?.reference??"",due_date:dueDate??exists?.due_date};return exists?rows.map(p=>p.method===method?next:p):[...rows,next]})
 const openCheckout=()=>{if(!session){setCustodyAction(pendingHandovers.length?"receive":"open");setCustodyOpen(true);return}setPayments([{method:"cash",amount:total,reference:""}]);setCashTendered(total);setCheckoutOpen(true);setMessage(null)}
 const updatePayment=(method:PaymentKey,value:number,reference?:string)=>{setPayments(rows=>{const exists=rows.find(p=>p.method===method),next={method,amount:Math.max(0,round(value)),reference:reference??exists?.reference??"",due_date:exists?.due_date};let result=exists?rows.map(p=>p.method===method?next:p):[...rows,next];if(method!=="cash"){const others=result.filter(p=>p.method!=="cash").reduce((s,p)=>s+p.amount,0),cash=Math.max(total-others,0),cashRow=result.find(p=>p.method==="cash"),cashNext={method:"cash" as const,amount:round(cash),reference:""};result=cashRow?result.map(p=>p.method==="cash"?cashNext:p):[cashNext,...result];setCashTendered(cash)}return result})}
 const buildPayload=(id:string)=>{const customer=catalog.customers.find(c=>c.id===customerId);return {pos_client_sale_id:id,pos_point_id:pointId,pos_session_id:session?.id,pos_mode:mode,salesman_id:salesmanId,vch_date:today(),manual_date:today(),due_date:today(),account_id:customer?.accountId||point?.walk_in_account_id||null,customer_name:customer?.name||"عميل نقدي",rate:Number(point?.exchange_rate||1),discount_type:"percentage",discount_value:discountValue,vat_classification_id:1,invoice_type:1,vat_included:false,is_maqasa:false,status:2,note:note||`${mode==="return"?"مردود":"فاتورة"} من نقطة البيع ${point?.name||""}`,insert_user:Number(user?.id)||null,pos_payments:payments.filter(p=>p.amount>0),items:cart.map(l=>({product_id:l.id,item_id:l.id,product_code:l.code,product_name:l.name,item_name:l.name,barcode:l.barcode,unit_id:l.unitId,unit_name:l.unitName,unit:l.unitName,quantity:l.quantity,qnty:l.quantity,unit_price:l.price,price:l.price,discount_percent:l.discount,discount:l.discount,total_price:round(l.price*l.quantity*(1-l.discount/100)),line_amount:round(l.price*l.quantity*(1-l.discount/100)),account_id:mode==="return"?l.returnAccountId:l.accountId,available_stock:l.available}))}}
 const validate=()=>{if(mode==="return"&&payments.some(p=>p.amount>0&&p.method!=="cash"&&p.method!=="account"))return"المردودات متاحة نقداً أو على الذمة فقط";if(!point)return"اختر نقطة بيع";if(!session)return"يجب فتح عهدة";if(!cart.length)return"السلة فارغة";if(total<=0)return"لا يمكن حفظ فاتورة بإجمالي صفر";if(Math.abs(allocated-total)>.009)return"مجموع تفاصيل الدفع يجب أن يساوي إجمالي الفاتورة";if(payments.some(p=>p.amount>0&&p.method==="cheque"&&!p.reference.trim()))return"رقم الشيك مطلوب";if(payments.some(p=>p.amount>0&&p.method==="gift_card"&&!p.reference.trim()))return"رقم بطاقة الهدية مطلوب";if(payments.some(p=>p.amount>0&&p.method==="account")&&!customerId)return"اختر العميل للدفع على الحساب";if(cart.some(l=>!(mode==="return"?l.returnAccountId:l.accountId)))return mode==="return"?"يوجد صنف بلا حساب مردود مبيعات":"يوجد صنف بلا حساب مبيعات";return null}
 const finish=async()=>{const v=validate();if(v){setMessage({type:"error",text:v});return}setSaving(true);const id=makeId(),payload=buildPayload(id),snapshot=cart.map(x=>({...x})),queued:PosQueuedSale={id,tenantKey:baseKey,createdAt:new Date().toISOString(),payload,attempts:0};let completed=false;try{if(!navigator.onLine)throw new TypeError("offline");const r=await fetch("/api/pos/sales",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){setMessage({type:"error",text:errorText(d,"فشل الحفظ")});return}setReceipt({code:String(d.vch_code||""),total,pending:false,lines:snapshot,mode});setMessage({type:"success",text:`تم حفظ ${mode==="return"?"المردود":"الفاتورة"} ${d.vch_code||""}`});completed=true;await loadSession();await loadCatalogData()}catch(e){if(!(e instanceof TypeError)&&navigator.onLine){setMessage({type:"error",text:e instanceof Error?e.message:"فشل الحفظ"});return}if(!point?.allow_offline){setMessage({type:"error",text:"العمل دون اتصال غير مسموح لهذه النقطة"});return}await queuePosSale(queued);await updateQueue();setReceipt({code:`OFF-${id.slice(0,8).toUpperCase()}`,total,pending:true,lines:snapshot,mode});setMessage({type:"info",text:"حُفظت العملية على الجهاز وستُزامن تلقائيًا"});completed=true}finally{setSaving(false)}if(completed){setCart([]);setCheckoutOpen(false);setMode("sale");setNote("")}}
 const custody=async(sourceId?:number)=>{if(saving)return;if(!navigator.onLine){setMessage({type:"error",text:"عمليات العهدة تحتاج اتصالاً بالخادم"});return}setSaving(true);try{const r=await fetch("/api/pos/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:!session?(sourceId?"receive":"open"):custodyAction,point_id:pointId,amount:custodyAmount,note:custodyNote,source_session_id:sourceId})}),d=await r.json();if(!r.ok)throw new Error(d.error);setCatalog(c=>({...c,session:d.session||null}));setMessage({type:"success",text:"تم تنفيذ عملية العهدة بنجاح"});setCustodyOpen(false);setCustodyAmount(0);setCustodyNote("");await loadSession()}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"فشلت عملية العهدة"})}finally{setSaving(false)}}
 const loadHistory=async(q="")=>{if(!pointId||!navigator.onLine){setMessage({type:"error",text:"سجل الفواتير يحتاج اتصالاً بالخادم"});return}const r=await fetch(`/api/pos/history?point_id=${pointId}&q=${encodeURIComponent(q)}`,{cache:"no-store"}),d=await r.json();if(!r.ok){setMessage({type:"error",text:errorText(d,"تعذر تحميل الفواتير")});return}setHistoryRows(d.rows||[]);setHistoryOpen(true)}
 const print=()=>{if(!receipt)return;const rows=receipt.lines.map(l=>`<tr><td>${l.name}</td><td>${l.quantity}</td><td>${l.price.toFixed(2)}</td><td>${round(l.price*l.quantity*(1-l.discount/100)).toFixed(2)}</td></tr>`).join("");const w=window.open("","_blank","width=420,height=680");if(!w)return;w.document.write(`<html dir=rtl><style>body{font-family:Arial;padding:20px}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px dashed #aaa}</style><h2>${receipt.mode==="return"?"مردود مبيعات":"فاتورة بيع"}</h2><p>${receipt.code}</p><table><tr><th>الصنف</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th></tr>${rows}</table><h2>الإجمالي ${receipt.total.toFixed(2)} ${point?.currency_code||""}</h2></html>`);w.document.close();w.print()}
 const actions=[{label:"تفاصيل الدفع",icon:CreditCard,onClick:openCheckout},{label:"خصم",icon:Percent,onClick:()=>setDiscountOpen(true)},{label:mode==="return"?"إلغاء المردود":"مردودات",icon:RotateCcw,onClick:()=>{if(!point?.allow_returns)return setMessage({type:"error",text:"المردودات غير مفعلة لهذه النقطة"});setMode(m=>m==="sale"?"return":"sale");setCart([])}},{label:"هدية",icon:Gift,onClick:()=>{if(!point?.allow_gifts)return setMessage({type:"error",text:"الهدايا غير مفعلة لهذه النقطة"});setCart(c=>c.length?c.map((l,i)=>i===c.length-1?{...l,gift:!l.gift,discount:l.gift?0:100}:l):c)}},{label:"ملاحظة",icon:StickyNote,onClick:()=>setNoteOpen(true)},{label:"الفواتير",icon:History,onClick:()=>void loadHistory()},{label:"العهدة F8",icon:HandCoins,onClick:()=>setCustodyOpen(true)},{label:"تحديث",icon:RefreshCw,onClick:()=>void loadCatalogData()}]
 return <div dir="rtl" className="pos-workspace">
  {noPoints&&<div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-center text-lg font-bold text-amber-800">يجب تعريف نقطة بيع اولا</div>}
  <header className="pos-toolbar">
   <div className="flex items-center gap-3"><span className="pos-brand"><ShoppingBag size={23}/></span><div><h1 className="font-black">نقطة البيع</h1><p className="text-xs text-slate-500">{point?.name||"اختر نقطة البيع للبدء"}</p></div></div>
   <div className="flex flex-wrap items-center gap-2">
    <Button variant="outline" onClick={()=>setNewSaleOpen(true)} disabled={!cart.length||saving}><Plus size={16}/>جديد</Button>
    <Button onClick={openCheckout} disabled={!cart.length||saving}><CreditCard size={16}/>الدفع والحفظ F4</Button>
    <Button variant="outline" onClick={()=>void loadHistory()}><History size={16}/>الفواتير</Button>
    <Button variant="outline" onClick={()=>setCustodyOpen(true)}><HandCoins size={16}/>العهدة F8</Button>
    <button onClick={()=>void syncPending()} disabled={syncing||!online} className="pos-tool"><RefreshCw size={16} className={cn(syncing&&"animate-spin")}/>مزامنة ({pendingCount})</button>
   </div>
   <span className={cn("flex items-center gap-2 rounded-full px-3 py-2 text-xs font-bold",online?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700")}>{online?<Wifi size={15}/>:<WifiOff size={15}/>} {online?"متصل":"غير متصل"}</span>
  </header>
  <section className="pos-overview">
   <div className="pos-context"><label htmlFor="pos-point" className="text-xs text-slate-500">نقطة البيع</label><select id="pos-point" value={pointId||""} disabled={cart.length>0||saving} onChange={e=>setPointId(Number(e.target.value)||null)}><option value="">اختر نقطة البيع</option>{points.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select><div className="flex flex-wrap gap-3 text-xs text-slate-500"><span>{today()}</span><span>{point?.warehouse_name}</span><span>{session?`العهدة #${session.id}`:"لا توجد عهدة مفتوحة"}</span></div></div>
   <div className="pos-categories" aria-label="تصنيفات الأصناف"><button aria-pressed={category==="all"} onClick={()=>setCategory("all")}>كل الأصناف</button>{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
   <div className="pos-net"><span>{mode==="return"?"الصافي للاسترجاع":"الصافي للدفع"}</span><strong>{total.toFixed(2)} <small>{point?.currency_code}</small></strong></div>
  </section>
  {message&&<div role="status" className={cn("flex items-center justify-between rounded-xl border px-4 py-3 text-sm",message.type==="error"?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700")}><span>{message.text}</span><button aria-label="إغلاق الرسالة" onClick={()=>setMessage(null)}><X size={16}/></button></div>}
  <main className="pos-layout">
   <section className="pos-catalog">
    <div className="pos-panel-heading"><h2>الأصناف</h2><span>{shown.length} صنف</span></div>
    <div className="relative m-3"><Barcode className="absolute right-3 top-3 text-emerald-600" size={21}/><Input ref={searchRef} autoFocus aria-label="بحث الأصناف والباركود" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&searchEnter()} placeholder="امسح الباركود أو ابحث عن صنف… F2" className="h-12 pr-11"/></div>
    <div className="pos-products">{loading?<div className="pos-empty"><RefreshCw className="animate-spin"/>جاري تحميل الأصناف…</div>:shown.length?shown.map(p=><button key={p.id} onClick={()=>add(p)} className="pos-product"><div className="flex items-start justify-between gap-2"><span className="pos-product-icon">{p.image?<img src={p.image} alt=""/>:<PackageOpen size={24}/>}</span><small>{p.code}</small></div><b>{p.name}</b><div className="flex items-end justify-between gap-2"><strong>{p.price.toFixed(2)}</strong><small className={p.available<=0?"text-rose-600":""}>{p.available} {p.unitName}</small></div></button>):<div className="pos-empty"><Search size={32}/><p>لا توجد أصناف مطابقة</p><button className="pos-tool" onClick={()=>{setQuery("");setCategory("all")}}>مسح البحث والتصنيف</button></div>}</div>
   </section>
   <section className="pos-sale">
    <div className="pos-panel-heading"><h2 className="flex items-center gap-2"><ShoppingCart size={20}/>{mode==="return"?"مردود مبيعات":"الفاتورة الحالية"}</h2><span>{cart.length} أصناف · {cart.reduce((s,l)=>s+l.quantity,0)} وحدات</span></div>
    <div className="pos-cart" aria-label="أصناف الفاتورة">
     {cart.length?cart.map((l,index)=><article key={l.id} className={cn("pos-cart-line",selectedLineId===l.id&&"is-selected",l.gift&&"is-gift")}>
      <button className="pos-line-name" aria-pressed={selectedLineId===l.id} onClick={()=>{setSelectedLineId(l.id);setQuantityEntry(String(l.quantity))}}><small>{index+1} · {l.code}{l.barcode?` · ${l.barcode}`:""}</small><b>{l.name}</b><small>{l.price.toFixed(2)} / {l.unitName||"وحدة"}{l.gift?" · هدية":l.discount?` · خصم ${l.discount}%`:""}</small></button>
      <div className="pos-quantity"><button aria-label={`تقليل كمية ${l.name}`} onClick={()=>changeQty(l.id,-1)}><Minus size={16}/></button><strong>{l.quantity}</strong><button aria-label={`زيادة كمية ${l.name}`} onClick={()=>changeQty(l.id,1)}><Plus size={16}/></button></div>
      <strong className="pos-line-total">{round(l.price*l.quantity*(1-l.discount/100)).toFixed(2)}</strong><button className="pos-remove" aria-label={`حذف ${l.name}`} onClick={()=>setCart(c=>c.filter(x=>x.id!==l.id))}><Trash2 size={17}/></button>
     </article>):<div className="pos-empty"><ShoppingCart size={42}/><h3 className="font-bold">ابدأ فاتورة جديدة</h3><p>اختر صنفاً من القائمة أو امسح الباركود لإضافته</p></div>}
    </div>
    <div className="pos-checkout-dock">
     <div className="pos-keypad"><label htmlFor="pos-quantity-entry">كمية الصنف المحدد</label><div className="flex gap-1"><Input id="pos-quantity-entry" inputMode="decimal" value={quantityEntry} disabled={!cart.some(l=>l.id===selectedLineId)} onChange={e=>setQuantityEntry(e.target.value)} onKeyDown={e=>e.key==="Enter"&&applyQuantity()}/><Button variant="outline" onClick={applyQuantity} disabled={!cart.some(l=>l.id===selectedLineId)}>تطبيق</Button></div><div className="pos-keypad-keys" dir="ltr">{["1","2","3","4","5","6","7","8","9","⌫","0","."].map(key=><button key={key} disabled={!cart.some(l=>l.id===selectedLineId)} aria-label={key==="⌫"?"مسح رقم":key} onClick={()=>setQuantityEntry(v=>key==="⌫"?v.slice(0,-1):key==="."&&v.includes(".")?v:v+key)}>{key}</button>)}</div></div>
     <nav className="pos-actions" aria-label="إجراءات الفاتورة">{(["customer","salesman"] as const).map(kind=><PosPartyButton key={kind} kind={kind} selected={kind==="customer"?catalog.customers.find(c=>c.id===customerId):(catalog.salesmen||[]).find(c=>c.id===salesmanId)} onOpen={()=>setPartyPicker(kind)} onClear={()=>kind==="customer"?setCustomerId(null):setSalesmanId(null)}/>)}{actions.map(a=><button key={a.label} onClick={a.onClick} disabled={a.label==="تفاصيل الدفع"&&!cart.length}><a.icon size={19}/>{a.label}</button>)}</nav>
     <div className="pos-totals"><div><span>مجموع الأصناف</span><b>{cart.reduce((s,l)=>s+l.price*l.quantity,0).toFixed(2)}</b></div><div><span>خصم الأصناف</span><b>{cart.reduce((s,l)=>s+l.price*l.quantity*l.discount/100,0).toFixed(2)}</b></div><div><span>الضريبة</span><b>{tax.toFixed(2)}</b></div><div><span>خصم الفاتورة</span><b>{invoiceDiscount.toFixed(2)}</b></div><div className="pos-total-due"><span>الصافي للدفع</span><strong>{total.toFixed(2)}</strong></div><Button className="h-12 w-full" disabled={!cart.length||saving} onClick={openCheckout}>{mode==="return"?"إعادة المبلغ":"إتمام البيع"} F4</Button></div>
    </div>
    {note&&<div className="px-4 pb-3 text-xs text-slate-500">ملاحظة: {note}</div>}
   </section>
  </main>
  <Dialog open={newSaleOpen} onOpenChange={setNewSaleOpen}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>بدء فاتورة جديدة؟</DialogTitle><DialogDescription>سيتم مسح أصناف الفاتورة الحالية غير المحفوظة.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setNewSaleOpen(false)}>لا، متابعة الفاتورة</Button><Button onClick={()=>{setCart([]);setNote("");setCustomerId(null);setSalesmanId(null);setMode("sale");setSelectedLineId(null);setQuantityEntry("");setNewSaleOpen(false);searchRef.current?.focus()}}>نعم، فاتورة جديدة</Button></DialogFooter></DialogContent></Dialog>

 {partyPicker&&<PosPartyPicker title={partyPicker==="customer"?"بحث الحساب":"بحث المندوب"} rows={partyPicker==="customer"?catalog.customers:catalog.salesmen||[]} onClose={()=>setPartyPicker(null)} onSelect={id=>{if(partyPicker==="customer")setCustomerId(id);else setSalesmanId(id);setPartyPicker(null)}}/>}
 <Dialog open={checkoutOpen} onOpenChange={setCheckoutOpen}><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto p-0"><div className="bg-slate-950 p-6 text-white"><DialogHeader><DialogTitle className="text-2xl">تفاصيل الدفع</DialogTitle><DialogDescription className="text-slate-400">يمكن تقسيم المبلغ على أكثر من طريقة دفع.</DialogDescription></DialogHeader><div className="mt-5 flex justify-between"><span>المطلوب</span><strong className="text-4xl text-emerald-300">{total.toFixed(2)} <small className="text-sm">{point?.currency_code}</small></strong></div></div><div className="space-y-3 p-5">{((mode==="return"?["cash","account"]:["cash","card","cheque","account","gift_card"]) as PaymentKey[]).map(method=>{const Icon=paymentIcons[method],p=payments.find(x=>x.method===method);return <div key={method} className="grid items-end gap-3 rounded-2xl border p-3 sm:grid-cols-[150px_1fr_1fr]"><div className="flex items-center gap-2 font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100"><Icon className="h-4 w-4"/></span>{paymentLabels[method]}</div><Field label="المبلغ"><Input type="number" min="0" value={p?.amount||0} onChange={e=>{updatePayment(method,Number(e.target.value));if(method==="cash")setCashTendered(Number(e.target.value))}}/></Field>{method==="cheque"?<div className="grid grid-cols-2 gap-2"><Field label="رقم الشيك"><Input value={p?.reference||""} onChange={e=>setPay(method,p?.amount||0,e.target.value)}/></Field><Field label="الاستحقاق"><Input type="date" value={p?.due_date||today()} onChange={e=>setPay(method,p?.amount||0,undefined,e.target.value)}/></Field></div>:method==="gift_card"?<Field label="رقم بطاقة الهدية"><Input value={p?.reference||""} onChange={e=>setPay(method,p?.amount||0,e.target.value)}/></Field>:method==="cash"?<Field label="المبلغ المستلم"><Input type="number" min="0" value={cashTendered} onChange={e=>setCashTendered(Number(e.target.value))}/></Field>:<div/>}</div>})}<div className={cn("grid gap-2 rounded-2xl p-4 font-bold sm:grid-cols-3",Math.abs(allocated-total)<.009?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800")}><span>مجموع الدفعات: {allocated.toFixed(2)}</span><span>المتبقي: {Math.max(total-allocated,0).toFixed(2)}</span><span>المرتجع: {change.toFixed(2)}</span></div></div><DialogFooter className="border-t p-4"><Button variant="outline" onClick={()=>setCheckoutOpen(false)}>إلغاء</Button><Button onClick={()=>void finish()} disabled={saving}>{saving&&<RefreshCw className="ml-2 h-4 w-4 animate-spin"/>}تنفيذ وحفظ</Button></DialogFooter></DialogContent></Dialog>
 <PosStartSessionDialog open={custodyOpen&&!session&&!!point&&!noPoints} onOpenChange={setCustodyOpen} userName={user?.fullName||user?.username||""} currency={point?.currency_name||""} amount={custodyAmount} onAmountChange={setCustodyAmount} busy={saving} online={online} error={message?.type==="error"?message.text:undefined} pending={pendingHandovers} onConfirm={sourceId=>void custody(sourceId)}/>
 <Dialog open={custodyOpen&&!!session} onOpenChange={setCustodyOpen}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>تسليم واستلام العهدة</DialogTitle><DialogDescription>{session?`الرصيد المتوقع ${Number(session.expected_cash).toFixed(2)} ${point?.currency_code||""}`:"ابدأ عهدة جديدة أو استلم عهدة مسلّمة."}</DialogDescription></DialogHeader>{session&&Array.isArray(session.payments)&&session.payments.length>0&&<div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{session.payments.map((p:any)=><div key={p.payment_method} className="rounded-xl bg-slate-50 p-3"><small className="text-slate-400">{paymentLabels[p.payment_method as PaymentKey]||p.payment_method}</small><p className="font-black">{Number(p.amount).toFixed(2)}</p><small>{p.count} عمليات</small></div>)}</div>}<div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{(session?["cash_in","cash_out","handover","close"]:["open","receive"]).map(a=><button key={a} onClick={()=>setCustodyAction(a)} className={cn("rounded-xl border p-3 text-sm font-bold",custodyAction===a?"border-emerald-500 bg-emerald-50 text-emerald-700":"bg-white")}>{({open:"فتح عهدة",receive:"استلام",cash_in:"إيداع",cash_out:"سحب",handover:"تسليم",close:"إغلاق"} as any)[a]}</button>)}</div>{custodyAction==="receive"?<div className="space-y-2">{pendingHandovers.length?pendingHandovers.map(h=><button key={h.id} onClick={()=>void custody(Number(h.id))} className="flex w-full justify-between rounded-2xl border p-4 text-right hover:border-emerald-400"><span><b>{h.from_user_name||h.user_id}</b><small className="block text-slate-400">عهدة رقم {h.id}</small></span><strong>{Number(h.handover_amount).toFixed(2)}</strong></button>):<p className="rounded-xl bg-slate-50 p-4 text-center text-slate-500">لا توجد عهدة بانتظار الاستلام</p>}</div>:<><Field label={custodyAction==="close"?"الرصيد المعدود":custodyAction==="handover"?"مبلغ التسليم":"المبلغ"}><Input type="number" min="0" value={custodyAmount} onChange={e=>setCustodyAmount(Number(e.target.value))}/></Field><Field label="ملاحظة"><Input value={custodyNote} onChange={e=>setCustodyNote(e.target.value)}/></Field></>}<DialogFooter><Button variant="outline" onClick={()=>setCustodyOpen(false)}>إلغاء</Button>{custodyAction!=="receive"&&<Button disabled={saving} onClick={()=>void custody()}>{custodyAction==="cash_in"?<ArrowDownToLine className="ml-2 h-4 w-4"/>:custodyAction==="cash_out"?<ArrowUpFromLine className="ml-2 h-4 w-4"/>:<HandCoins className="ml-2 h-4 w-4"/>}تنفيذ العملية</Button>}</DialogFooter></DialogContent></Dialog>
 {discountOpen&&<PosDiscountDialog subtotal={subtotal} itemDiscount={cart.reduce((sum,line)=>sum+line.price*line.quantity*line.discount/100,0)} customer={catalog.customers.find(c=>c.id===customerId)?.name||"عميل نقدي"} maximum={Number(point?.max_discount_percent??100)} initialPercent={discountValue} taxPercent={Number(point?.tax_percent||0)} onApply={percent=>{setDiscountValue(percent);setDiscountOpen(false)}} onClose={()=>setDiscountOpen(false)}/>}
 <Dialog open={noteOpen} onOpenChange={setNoteOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>ملاحظة الفاتورة</DialogTitle></DialogHeader><textarea value={note} onChange={e=>setNote(e.target.value)} rows={5} className="w-full rounded-xl border p-3"/><DialogFooter><Button onClick={()=>setNoteOpen(false)}>حفظ الملاحظة</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={historyOpen} onOpenChange={setHistoryOpen}><DialogContent className="max-h-[88vh] max-w-3xl overflow-hidden p-0"><div className="bg-slate-950 p-5 text-white"><DialogHeader><DialogTitle>فواتير نقطة البيع</DialogTitle><DialogDescription className="text-slate-400">آخر مبيعات ومردودات هذه النقطة وطرق دفعها.</DialogDescription></DialogHeader><div className="mt-4 flex gap-2"><Input value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void loadHistory(historyQuery)} placeholder="رقم الفاتورة أو العميل..." className="bg-white text-slate-900"/><Button onClick={()=>void loadHistory(historyQuery)}><Search className="h-4 w-4"/></Button></div></div><div className="max-h-[58vh] space-y-2 overflow-y-auto p-4">{historyRows.map(r=><article key={r.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><b>{r.vch_code}</b><p className="text-sm text-slate-500">{r.customer_name||"عميل نقدي"} • {String(r.vch_date).slice(0,10)}</p></div><div className="text-left"><span className={cn("rounded-full px-2 py-1 text-xs font-bold",Number(r.vch_type)===16?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700")}>{Number(r.vch_type)===16?"مردود":"بيع"}</span><p className="mt-1 text-lg font-black">{Number(r.amount).toFixed(2)}</p></div></div><div className="mt-3 flex flex-wrap gap-1">{(r.payments||[]).map((p:any,i:number)=><span key={i} className="rounded-full bg-slate-100 px-2 py-1 text-xs">{paymentLabels[p.method as PaymentKey]||p.method}: {Number(p.amount).toFixed(2)}{p.reference?` • ${p.reference}`:""}</span>)}</div></article>)}{!historyRows.length&&<p className="py-12 text-center text-slate-400">لا توجد فواتير مطابقة</p>}</div></DialogContent></Dialog>
 <Dialog open={Boolean(receipt)} onOpenChange={o=>!o&&setReceipt(null)}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>{receipt?.mode==="return"?"تم حفظ المردود":"تمت عملية البيع"}</DialogTitle><DialogDescription>{receipt?.pending?"نسخة محلية بانتظار المزامنة":"تم ترحيل الحركة والمخزون والمدفوعات"}</DialogDescription></DialogHeader><div className="rounded-2xl bg-slate-950 p-5 text-center text-white"><small className="text-slate-400">رقم الحركة</small><p className="text-xl font-black text-emerald-300">{receipt?.code}</p><p className="mt-4 text-3xl font-black">{receipt?.total.toFixed(2)} {point?.currency_code}</p></div><DialogFooter><Button variant="outline" onClick={()=>setReceipt(null)}>عملية جديدة</Button><Button onClick={print}><Printer className="ml-2 h-4 w-4"/>طباعة</Button></DialogFooter></DialogContent></Dialog>
 </div>
}

function Field({label,children}:any){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
