"use client"

import ConfirmDialogYesNo from "@/components/ui/ConfirmDialogYesNo"
import { repricePosCart } from "@/lib/pos-customer-prices"

import "./pos-workspace.css"
import { posCartLineKey } from "@/lib/pos-cart"
import { validatePosAccounts } from "@/lib/pos-account-validation"
import { isScaleProduct, resolvePosBarcode } from "@/lib/scale-barcode"
import {PosDiscountDialog,PosItemDiscountDialog} from "./pos-discount-dialog"
import {PosPartyPicker,PosPartyButton,type PosParty} from "./pos-party-picker"
import {PosStartSessionDialog} from "./pos-start-session-dialog"
import {PosHandoverDialog} from "./pos-handover-dialog"
import {PosPaymentDetailsDialog,type PaymentDetail} from "./pos-payment-details-dialog"
import {PosInvoiceHistoryDialog,type PosInvoice} from "./pos-invoice-history-dialog"

import {useCallback,useEffect,useMemo,useRef,useState} from "react"
import {ArrowDownToLine,ArrowUpFromLine,ArrowLeft,Banknote,Barcode,Bookmark,ChevronLeft,ChevronRight,ChevronsLeft,ChevronsRight,Clock3,CreditCard,FolderOpen,Gift,HandCoins,History,Minus,PackageOpen,Pencil,Percent,Plus,Printer,RefreshCw,RotateCcw,Save,Search,ShoppingBag,ShoppingCart,StickyNote,Trash2,UserRound,WalletCards,Warehouse,Wifi,WifiOff,X} from "lucide-react"
import {useAuth} from "@/components/auth/auth-context"
import {Button} from "@/components/ui/button"
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog"
import {Input} from "@/components/ui/input"
import {Label} from "@/components/ui/label"
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select"
import {cn} from "@/lib/utils"
import {useToast} from "@/hooks/use-toast"
import {currentPosTenantKey,listPosSales,loadPosCatalog,markPosSaleFailed,queuePosSale,removePosSale,savePosCatalog,type PosQueuedSale} from "@/lib/pos-offline"

type BarcodeOption={barcode:string;price:number;unitId:number|null;unitName:string}
type Product={unitPrices?:{unitId:number|null;price:number}[];soldUsingScale:boolean;id:number;code:string;name:string;barcode:string;price:number;unitId:number|null;unitName:string;accountId:number|null;returnAccountId:number|null;category:string;image?:string;available:number;barcodeOptions:BarcodeOption[]}
type CartLine=Product&{quantity:number;discount:number;gift:boolean}
type Customer={pricecategory?:number;id:number;name:string;code?:string;accountId:number|null}
type Point=Record<string,any>&{id:number;name:string;code:string;warehouse_name:string;currency_name:string;currency_code:string}
type Session=Record<string,any>&{id:number;expected_cash:number;opening_cash:number;payments?:any[];movements?:any[]}
type Currency={currency_id:number;currency_code:string;currency_name:string;rate_to_point:number;exchange_rate:number}
type Catalog={point:Point|null;products:Product[];customers:Customer[];salesmen?:PosParty[];currencies:Currency[];banks:PosParty[];bankBranches:(PosParty&{bank_id?:number})[];cardTypes:(PosParty&{currency_id:number})[];session:Session|null}
type PaymentKey="cash"|"card"|"cheque"|"account"|"gift_card"
type Payment=PaymentDetail
type Receipt={code:string;total:number;pending:boolean;lines:CartLine[];mode:"sale"|"return"|"gift"}|null
const EMPTY:Catalog={point:null,products:[],customers:[],currencies:[],banks:[],bankBranches:[],cardTypes:[],session:null}
const round=(n:number)=>Math.round(n*100)/100
const today=()=>new Date().toISOString().slice(0,10)
const makeId=()=>globalThis.crypto?.randomUUID?.()||`pos-${Date.now()}-${Math.random().toString(16).slice(2)}`
const paymentLabels:Record<PaymentKey,string>={cash:"نقدي",card:"بطاقة",cheque:"شيك",account:"على الحساب",gift_card:"بطاقة هدية"}
const paymentIcons:Record<PaymentKey,any>={cash:Banknote,card:CreditCard,cheque:WalletCards,account:UserRound,gift_card:Gift}
const errorText=(d:any,f:string)=>String(d?.error||d?.message||f)

export default function PosCashier(){
 const {user}=useAuth(),{toast}=useToast(),baseKey=useMemo(()=>currentPosTenantKey(user?.id),[user?.id]),searchRef=useRef<HTMLInputElement>(null),syncingRef=useRef(false),focusBarcodeAfterSaveRef=useRef(false)
 const [points,setPoints]=useState<Point[]>([]),[pointId,setPointId]=useState<number|null>(null),[catalog,setCatalog]=useState<Catalog>(EMPTY),[cart,setCart]=useState<CartLine[]>([]),[query,setQuery]=useState(""),[barcodeQuery,setBarcodeQuery]=useState(""),[category,setCategory]=useState("all"),[customerId,setCustomerId]=useState<number|null>(null),[mode,setMode]=useState<"sale"|"return"|"gift">("sale"),[note,setNote]=useState("")
 const [online,setOnline]=useState(true),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[pendingCount,setPendingCount]=useState(0),[message,setMessage]=useState<{type:"success"|"error"|"info";text:string}|null>(null),[receipt,setReceipt]=useState<Receipt>(null)
 const [checkoutOpen,setCheckoutOpen]=useState(false),[payments,setPayments]=useState<Payment[]>([]),[cashTendered,setCashTendered]=useState(0),[saving,setSaving]=useState(false),[custodyOpen,setCustodyOpen]=useState(false),[custodyAction,setCustodyAction]=useState("open"),[custodyAmount,setCustodyAmount]=useState(0),[custodyNote,setCustodyNote]=useState(""),[pendingHandovers,setPendingHandovers]=useState<any[]>([]),[discountOpen,setDiscountOpen]=useState(false),[discountValue,setDiscountValue]=useState(0),[noteOpen,setNoteOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[historyRows,setHistoryRows]=useState<any[]>([]),[historyQuery,setHistoryQuery]=useState("")
 const custodyAmountsEditedRef=useRef(false)
 const [custodyAmounts,setCustodyAmounts]=useState<Record<number,number>>({})
 const [historyScope,setHistoryScope]=useState<"shift"|"all">("shift"),[historySelected,setHistorySelected]=useState<PosInvoice|null>(null),[historyLoading,setHistoryLoading]=useState(false),[historyDeleting,setHistoryDeleting]=useState(false),[historyError,setHistoryError]=useState(""),[editingInvoiceId,setEditingInvoiceId]=useState<number|null>(null)
 const [editingDraftId,setEditingDraftId]=useState<number|null>(null)
 const [draftOpen,setDraftOpen]=useState(false),[draftRows,setDraftRows]=useState<any[]>([]),[draftLoading,setDraftLoading]=useState(false),[draftError,setDraftError]=useState(""),[draftSaving,setDraftSaving]=useState(false)
 const [custodyCurrencyId,setCustodyCurrencyId]=useState<number|null>(null)
 const [movementAmounts,setMovementAmounts]=useState<Record<number,number>>({})
 const [activePointShift,setActivePointShift]=useState<{id:number;shift_guid?:string;user_name?:string}|null>(null)
 const [cashCurrencyAmounts,setCashCurrencyAmounts]=useState<Record<number,number>>({})
 const [checkoutError,setCheckoutError]=useState("")
 const [custodyError,setCustodyError]=useState("")
 const [selectedLineId,setSelectedLineId]=useState<string|null>(null),[quantityEntry,setQuantityEntry]=useState(""),[newSaleOpen,setNewSaleOpen]=useState(false)
 const [itemDiscountId,setItemDiscountId]=useState<string|null>(null)
 const [visibleLimit,setVisibleLimit]=useState(180)
 const applyQuantity=()=>{const quantity=Number(quantityEntry);if(!Number.isFinite(quantity)||quantity<=0)return;setCart(lines=>lines.map(line=>posCartLineKey(line)===selectedLineId?{...line,quantity}:line))}
 const [noPoints,setNoPoints]=useState(false)
 const [partyPicker,setPartyPicker]=useState<"customer"|"salesman"|null>(null),[salesmanId,setSalesmanId]=useState<number|null>(null)
 const [customerProducts,setCustomerProducts]=useState<Product[]|null>(null)
 const [pendingCustomer,setPendingCustomer]=useState<Customer|null>(null)
 const [pricingBusy,setPricingBusy]=useState(false)
 const [customerPriceError,setCustomerPriceError]=useState("")
 const pricingRequestRef=useRef(0)
 const productsForSale=customerProducts??catalog.products
 const point=catalog.point,session=catalog.session
 const subtotal=useMemo(()=>round(cart.reduce((s,l)=>s+l.price*l.quantity*(1-l.discount/100),0)),[cart]),invoiceDiscount=mode==="gift"?0:round(subtotal*discountValue/100),tax=mode==="gift"?0:round((subtotal-invoiceDiscount)*Number(point?.tax_percent||0)/100),total=mode==="gift"?0:round(subtotal-invoiceDiscount+tax)
 const allocated=round(payments.reduce((s,p)=>s+p.amount,0))
 const cashPayment=round(payments.find(p=>p.method==="cash")?.amount||0)
 const nonCashPaid=round(allocated-cashPayment)
 const change=mode==="sale"?round(Math.max(0,allocated-total)):0
 const pointCashOnly=catalog.currencies.every(row=>!(cashCurrencyAmounts[row.currency_id]>0)||row.currency_id===Number(point?.currency_id))
 const cashChangeAllowed=change>0&&pointCashOnly&&cashPayment>=change&&nonCashPaid<=total+.009
 const categories=useMemo(()=>Array.from(new Set(productsForSale.map(p=>p.category).filter(Boolean))).map(name=>({name,count:productsForSale.filter(product=>product.category===name).length})),[productsForSale])
 const shown=useMemo(()=>{const t=query.trim().toLocaleLowerCase("ar");return productsForSale.filter(p=>(category==="all"||p.category===category)&&(!t||p.name.toLocaleLowerCase("ar").includes(t)))},[productsForSale,category,query])
 useEffect(()=>setVisibleLimit(180),[category,query,pointId])
 const updateQueue=useCallback(async()=>{try{setPendingCount((await listPosSales(baseKey)).length)}catch{setPendingCount(0)}},[baseKey])
 const normalize=(d:any):Catalog=>({point:d.point||null,session:d.session?{...d.session,expected_cash:Number(d.session.expected_cash||0),opening_cash:Number(d.session.opening_cash||0)}:null,products:(d.products||[]).map((r:any)=>({id:Number(r.id),code:String(r.product_code||""),name:String(r.product_name||"صنف"),soldUsingScale:isScaleProduct(r.pos_sold_using_scale),barcode:String(r.first_barcode||r.barcode||""),price:Number(r.first_price||0),unitId:Number(r.unit_id)||null,unitName:String(r.unit_name||""),accountId:Number(r.selling_account_id)||null,returnAccountId:Number(r.selling_returns_account_id)||null,category:String(r.category_name||"غير مصنف"),image:r.product_image?( /^(https?:|data:|\/)/i.test(String(r.product_image))?String(r.product_image):`data:image/bmp;base64,${r.product_image}`):undefined,available:Number(r.available_stock||0),unitPrices:(Array.isArray(r.unit_prices)?r.unit_prices:[]).map((option:any)=>({unitId:Number(option.unit_id)||null,price:Number(option.price||0)})),barcodeOptions:(Array.isArray(r.barcode_options)?r.barcode_options:[]).map((option:any)=>({barcode:String(option.barcode||""),price:Number(option.price||0),unitId:Number(option.unit_id)||null,unitName:String(option.unit_name||"")}))})),currencies:(d.currencies||[]).map((r:any)=>({currency_id:Number(r.currency_id),currency_code:String(r.currency_code||""),currency_name:String(r.currency_name||""),rate_to_point:Number(r.rate_to_point||1),exchange_rate:Number(r.exchange_rate||1)})),banks:(d.banks||[]).map((r:any)=>({id:Number(r.id),code:String(r.code||""),name:String(r.name||"")})),bankBranches:(d.bankBranches||[]).map((r:any)=>({id:Number(r.id),bank_id:Number(r.bank_id)||undefined,code:String(r.code||""),name:String(r.name||"")})),cardTypes:(d.cardTypes||[]).filter((r:any)=>Number(r.currency_id)===Number(d.point?.currency_id)).map((r:any)=>({id:Number(r.id),name:String(r.name||""),currency_id:Number(r.currency_id)})),salesmen:(d.salesmen||[]).map((r:any)=>({id:Number(r.id),code:String(r.code||""),name:String(r.name||"")})),customers:(d.customers||[]).map((r:any)=>({id:Number(r.id),name:String(r.name||""),code:String(r.code||""),accountId:Number(r.account_id)||null,pricecategory:Number(r.pricecategory)||undefined}))})
 const loadPoints=useCallback(async()=>{if(!navigator.onLine){const last=Number(localStorage.getItem(`${baseKey}:last-point`)||0);if(last)setPointId(last);return}try{const r=await fetch("/api/pos/points",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);setPoints(d.points||[]);setNoPoints(!d.points?.length);if(!d.points?.length){setCatalog(EMPTY);setLoading(false);setCustodyOpen(false)}const saved=Number(localStorage.getItem(`${baseKey}:last-point`)||0),next=(d.points||[]).find((p:any)=>p.id===saved)?.id||d.points?.[0]?.id||null;setPointId(next)}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"تعذر تحميل نقاط البيع"})}},[baseKey])
 const loadCatalogData=useCallback(async()=>{if(!pointId)return;setLoading(true);const key=`${baseKey}:point:${pointId}`,cached=await loadPosCatalog<Catalog>(key).catch(()=>null);if(cached?.catalog)setCatalog(cached.catalog);if(!navigator.onLine){if(!cached)setMessage({type:"error",text:"افتح نقطة البيع مرة أثناء الاتصال لتنزيل أصناف المخزن الرئيسي"});setLoading(false);return}try{const r=await fetch(`/api/pos/catalog?point_id=${pointId}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);const next=normalize(d);setCatalog(next);await savePosCatalog(key,next);localStorage.setItem(`${baseKey}:last-point`,String(pointId));setMessage(null)}catch(e){if(!cached)setMessage({type:"error",text:e instanceof Error?e.message:"تعذر تحميل الكاشير"})}finally{setLoading(false)}},[baseKey,pointId])
 const loadSession=useCallback(async()=>{if(!pointId||!navigator.onLine)return;try{const r=await fetch(`/api/pos/sessions?point_id=${pointId}`,{cache:"no-store"}),d=await r.json();if(r.ok){setCatalog(c=>({...c,session:d.session||null}));setPendingHandovers(d.pending||[]);setActivePointShift(d.active_shift||null);return d}}catch{}},[pointId])
 const syncPending=useCallback(async()=>{if(!navigator.onLine||syncingRef.current)return;syncingRef.current=true;setSyncing(true);try{for(const sale of await listPosSales(baseKey)){try{const r=await fetch("/api/pos/sales",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(sale.payload)}),d=await r.json();if(!r.ok){await markPosSaleFailed(sale,errorText(d,"فشلت المزامنة"));continue}await removePosSale(sale.id)}catch(e){await markPosSaleFailed(sale,e instanceof Error?e.message:"انقطع الاتصال");break}}await updateQueue();await loadSession()}finally{syncingRef.current=false;setSyncing(false)}},[baseKey,loadSession,updateQueue])
 useEffect(()=>{setOnline(navigator.onLine);void loadPoints();void updateQueue();const on=()=>{setOnline(true);void syncPending();void loadPoints()},off=()=>setOnline(false);addEventListener("online",on);addEventListener("offline",off);return()=>{removeEventListener("online",on);removeEventListener("offline",off)}},[loadPoints,syncPending,updateQueue])
 useEffect(()=>{pricingRequestRef.current++;setCustomerProducts(null);setPendingCustomer(null);setPricingBusy(false);setCart([]);setDiscountValue(0);setCustomerId(null);setSalesmanId(null);setCategory("all");setEditingDraftId(null);void loadCatalogData()},[loadCatalogData])
 useEffect(()=>{if(pointId&&catalog.point)void savePosCatalog(`${baseKey}:point:${pointId}`,catalog)},[baseKey,catalog,pointId])
 useEffect(()=>{if(custodyOpen)void loadSession()},[custodyOpen,loadSession])
 useEffect(()=>{const refresh=()=>{void loadSession()};window.addEventListener("pos-session-changed",refresh);return()=>window.removeEventListener("pos-session-changed",refresh)},[loadSession])
 useEffect(()=>{if(custodyOpen){setCustodyError("");setMessage(null)}},[custodyOpen])
 useEffect(()=>{if(!custodyOpen)custodyAmountsEditedRef.current=false;if(!session?.id||custodyAmountsEditedRef.current)return;const next:Record<number,number>={};for(const row of session.currencies||[])next[Number(row.currency_id)]=Number(row.expected_amount||0);if(!Object.keys(next).length&&point?.currency_id)next[Number(point.currency_id)]=Number(session.expected_cash||0);setCustodyAmounts(next)},[custodyOpen,session?.id,session?.expected_cash,session?.currencies,point?.currency_id])
 useEffect(()=>{if(!custodyOpen)return;if(session){if(!["cash_in","cash_out","handover","close"].includes(custodyAction)){setCustodyAction("handover");setCustodyAmount(Number(session.expected_cash||0))}if(!custodyAmountsEditedRef.current)setCustodyAmounts(Object.fromEntries((session.currencies||[]).map((row:any)=>[Number(row.currency_id),Number(row.expected_amount||0)])))}else if(pendingHandovers.length){setCustodyAction("receive")}},[custodyOpen,session?.id,pendingHandovers.length])
 useEffect(()=>{if(!pointId||!catalog.point||!online)return;let active=true;void loadSession().then(data=>{if(active&&data&&!data.session){setCustodyAmount(0);setCustodyAction(data.pending?.length?"receive":"open");setCustodyOpen(true)}});return()=>{active=false}},[pointId,catalog.point?.id,online,loadSession])
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if(document.querySelector('[role="dialog"]'))return;if(e.key==="F2"){e.preventDefault();searchRef.current?.focus()}if(e.key==="F4"&&cart.length){e.preventDefault();openCheckout()}if(e.key==="F8"){e.preventDefault();requestTransactionAction(()=>setCustodyOpen(true))}};addEventListener("keydown",h);return()=>removeEventListener("keydown",h)})
 const playPriceErrorBeep=()=>{try{const audio=new Audio("/sounds/beep.mp3");audio.play().catch(()=>{const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)return;const context=new AudioContextClass(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.connect(gain);gain.connect(context.destination);oscillator.frequency.value=800;oscillator.type="square";gain.gain.setValueAtTime(0.3,context.currentTime);oscillator.start();oscillator.stop(context.currentTime+0.1)})}catch{}}
 const add=(p:Product,quantity=1)=>{if(pricingBusy)return;if(!Number.isFinite(p.price)||p.price<=0){toast({title:"خطأ",description:"لم يتم تحديد سعر الصنف المختار لا يمكن اضافته الى الفاتورة",variant:"destructive"});playPriceErrorBeep();setBarcodeQuery("");requestAnimationFrame(()=>searchRef.current?.focus());return}setHistorySelected(null);setSelectedLineId(posCartLineKey(p));setQuantityEntry(String(Number(((cart.find(l=>posCartLineKey(l)===posCartLineKey(p))?.quantity||0)+quantity).toFixed(4))));setCart(c=>{const f=c.find(x=>posCartLineKey(x)===posCartLineKey(p));return f?c.map(x=>posCartLineKey(x)===posCartLineKey(p)?{...x,quantity:Number((x.quantity+quantity).toFixed(4))}:x):[...c,{...p,quantity,discount:0,gift:false}]});setBarcodeQuery("");requestAnimationFrame(()=>searchRef.current?.focus())}
 const changeQty=(id:string,n:number)=>setCart(c=>c.map(x=>posCartLineKey(x)===id?{...x,quantity:Math.max(0,x.quantity+n)}:x).filter(x=>x.quantity>0))
 const searchEnter=()=>{
  const term=barcodeQuery.trim()
  if(!term)return
  // A scanner usually sends the complete barcode followed by Enter. Prefer a
  // unique exact identifier over the currently selected category or text filter.
  const resolved=resolvePosBarcode(productsForSale,term)
  const product=resolved?.product
  const option=product?.barcodeOptions.find(row=>row.barcode===resolved?.barcode)
  const match=product&&option?{...product,barcode:option.barcode,price:option.price,unitId:option.unitId,unitName:option.unitName}:product
  if(match&&resolved)add(match,resolved.quantity)
  else{setMessage({type:"error",text:"لا يوجد صنف بهذا الباركود"});searchRef.current?.select()}
 }
 const setPay=(method:PaymentKey,value:number,reference?:string,dueDate?:string)=>setPayments(rows=>{const exists=rows.find(p=>p.method===method),next={...exists,method,amount:Math.max(0,round(value)),reference:reference??exists?.reference??"",due_date:dueDate??exists?.due_date};return exists?rows.map(p=>p.method===method?next:p):[...rows,next]})
 const applyCustomerPrices=async(customer:Customer)=>{
  const requestId=++pricingRequestRef.current
  setPricingBusy(true);setCustomerPriceError("")
  try{
   const response=await fetch(`/api/pos/catalog?point_id=${pointId}&customer_id=${customer.id}`,{cache:"no-store"})
   const data=await response.json()
   if(!response.ok)throw new Error(data.error||"تعذر تحميل أسعار العميل")
   const nextProducts=normalize(data).products
   const nextCart=repricePosCart(cart,nextProducts)
   if(requestId!==pricingRequestRef.current)return
   setCart(nextCart);setCustomerProducts(nextProducts);setCustomerId(customer.id);setPendingCustomer(null)
   setPayments([]);setCashCurrencyAmounts({});setCashTendered(0)
  }catch(reason){
   if(requestId===pricingRequestRef.current){setPendingCustomer(null);setCustomerPriceError(reason instanceof Error?reason.message:"تعذر تحميل أسعار العميل")}
  }finally{if(requestId===pricingRequestRef.current)setPricingBusy(false)}
 }
 const selectCustomer=(id:number|null)=>{
  if(pricingBusy||saving||id===customerId)return
  if(id===null){setCustomerId(null);setCustomerProducts(null);return}
  const customer=catalog.customers.find(row=>row.id===id)
  if(!customer)return
  const priceClass=Number(customer.pricecategory)||Number(point?.price_category_id)
  if(priceClass!==Number(point?.price_category_id)){
   if(cart.length){setPendingCustomer(customer);return}
   void applyCustomerPrices(customer)
  }else{setCustomerId(id);setCustomerProducts(null)}
 }
 const keepCustomerPrices=()=>{if(pendingCustomer)setCustomerId(pendingCustomer.id);setPendingCustomer(null)}
 const cancelCustomerSelection=()=>setPendingCustomer(null)
 const [unsavedActionOpen,setUnsavedActionOpen]=useState(false)
 const pendingActionRef=useRef<null|(()=>void)>(null)
 const hasUnsavedChanges=cart.length>0||Boolean(note.trim())||customerId!==null||salesmanId!==null||discountValue!==0||editingInvoiceId!==null
 const resetTransaction=()=>{pricingRequestRef.current++;setCustomerProducts(null);setPendingCustomer(null);setPricingBusy(false);setCart([]);setNote("");setCustomerId(null);setSalesmanId(null);setDiscountValue(0);setPayments([]);setCashCurrencyAmounts({});setCashTendered(0);setEditingInvoiceId(null);setEditingDraftId(null);setSelectedLineId(null);setQuantityEntry("");setCheckoutError("")}
 const requestTransactionAction=(action:()=>void)=>{
  if(saving||draftSaving||pricingBusy)return
  if(!hasUnsavedChanges){action();return}
  pendingActionRef.current=action
  setUnsavedActionOpen(true)
 }
 const cancelTransactionAction=()=>{pendingActionRef.current=null;setUnsavedActionOpen(false)}
 const resumeTransactionAction=()=>{const action=pendingActionRef.current;pendingActionRef.current=null;action?.()}
 const discardAndContinue=()=>{resetTransaction();setUnsavedActionOpen(false);resumeTransactionAction()}
 const saveAndContinue=()=>{setUnsavedActionOpen(false);openCheckout()}
 const openCheckout=()=>{if(!session){setCustodyAction(pendingHandovers.length?"receive":"open");setCustodyOpen(true);return}setPayments([]);setCashCurrencyAmounts({});setCashTendered(0);setCheckoutError("");setCheckoutOpen(true);setMessage(null)}
 const updateCashCurrency=(currencyId:number,value:number)=>{const next={...cashCurrencyAmounts,[currencyId]:Math.max(0,round(value))};setCashCurrencyAmounts(next);const evaluated=round(catalog.currencies.reduce((sum,row)=>sum+round((next[row.currency_id]||0)*row.rate_to_point),0));setPay("cash",evaluated);setCashTendered(evaluated);setCheckoutError("")}
 const updatePayment=(method:PaymentKey,value:number,reference?:string,currencyId?:number)=>{setPayments(rows=>{const exists=rows.find(p=>p.method===method),chosen=currencyId||exists?.currency_id||Number(point?.currency_id),currency=catalog.currencies.find(row=>row.currency_id===chosen),original=Math.max(0,round(value)),next:Payment={...exists,method,amount:round(original*(currency?.rate_to_point||1)),currency_id:chosen,currency_amount:original,reference:reference??exists?.reference??"",due_date:exists?.due_date};return exists?rows.map(p=>p.method===method?next:p):[...rows,next]})}
 const updatePaymentField=(method:PaymentKey,field:keyof Payment,value:string|number)=>{setPayments(rows=>{const existing=rows.find(row=>row.method===method),next={method,amount:0,reference:"",...existing,[field]:value} as Payment;return existing?rows.map(row=>row.method===method?next:row):[...rows,next]});setCheckoutError("")}
 const buildPayload=(id:string)=>{const customer=catalog.customers.find(c=>c.id===customerId);return {pos_client_sale_id:id,pos_point_id:pointId,pos_session_id:session?.id,pos_customer_id:customerId,pos_mode:mode,salesman_id:salesmanId,vch_date:today(),manual_date:today(),due_date:today(),account_id:customer?.accountId||null,customer_name:customer?.name||"عميل نقدي",rate:Number(point?.exchange_rate||1),discount_type:"percentage",discount_value:discountValue,vat_classification_id:1,invoice_type:1,vat_included:false,is_maqasa:false,status:2,note:note||`${mode==="return"?"مردود":mode==="gift"?"هدية":"فاتورة"} من نقطة البيع ${point?.name||""}`,insert_user:Number(user?.id)||null,pos_payments:payments.filter(p=>p.amount>0).map(p=>p.method==="cash"&&cashChangeAllowed?{...p,amount:round(p.amount-change),currency_amount:round(p.amount-change)}:p).filter(p=>p.amount>0),cash_currency_amounts:cashChangeAllowed?[{currency_id:Number(point?.currency_id),amount:round(cashPayment-change)}].filter(row=>row.amount>0):catalog.currencies.filter(row=>(cashCurrencyAmounts[row.currency_id]||0)>0).map(row=>({currency_id:row.currency_id,amount:cashCurrencyAmounts[row.currency_id]})),items:cart.map(l=>({product_id:l.id,item_id:l.id,product_code:l.code,product_name:l.name,item_name:l.name,barcode:l.barcode,unit_id:l.unitId,unit_name:l.unitName,unit:l.unitName,quantity:l.quantity,qnty:l.quantity,unit_price:l.price,price:l.price,discount_percent:l.discount,discount:l.discount,total_price:round(l.price*l.quantity*(1-l.discount/100)),line_amount:round(l.price*l.quantity*(1-l.discount/100)),account_id:mode==="return"?(point?.return_account_id||l.returnAccountId):l.accountId,available_stock:l.available}))}}
 const paymentIssue=()=>{
  const accountIssue=point&&validatePosAccounts(point,payments,{mode,taxAmount:tax,returnAccountIds:cart.map(line=>line.returnAccountId),customerAccountId:customerId})
  if(accountIssue)return accountIssue
  if(catalog.currencies.some(row=>{const value=cashCurrencyAmounts[row.currency_id];return value!==undefined&&(!Number.isFinite(value)||value<0||Math.abs(value*100-Math.round(value*100))>0.000001)}))return"مبلغ النقد يجب أن يكون موجباً وبدقتين عشريتين"
  for(const payment of payments.filter(row=>row.amount>0)){
   const value=Number(payment.currency_amount??payment.amount)
   if(!Number.isFinite(value)||value<=0||Math.abs(value*100-Math.round(value*100))>0.000001)return"مبلغ الدفع غير صالح"
   if(!catalog.currencies.some(row=>row.currency_id===Number(payment.currency_id||point?.currency_id)))return"اختر عملة دفع صالحة"
   if(payment.method==="cheque"){
    if(!payment.cheque_account?.trim())return"رقم حساب الشيك مطلوب"
    if(!payment.reference.trim())return"رقم الشيك مطلوب"
    if(!payment.due_date||payment.due_date<today())return"تاريخ استحقاق الشيك غير صالح"
    if(!payment.bank_id||!payment.branch_id)return"اختر البنك والفرع للشيك"
   }
   if(payment.method==="card"){
    if(!payment.card_type_id)return"اختر نوع البطاقة"
    if(!/^\d{12,19}$/.test(payment.reference.replace(/[\s-]/g,"")))return"رقم البطاقة يجب أن يتكون من 12 إلى 19 رقماً"
    if(!payment.card_expiry||payment.card_expiry<today().slice(0,7))return"تاريخ انتهاء البطاقة غير صالح"
   }
   if(payment.method==="account"&&!customerId)return"اختر العميل للدفع على الحساب"
   if(payment.method==="gift_card"&&!payment.reference.trim())return"رقم بطاقة الهدية مطلوب"
  }
  return null
 }
 const validate=()=>{if(mode==="return"&&payments.some(p=>p.amount>0&&p.method!=="cash"&&p.method!=="account"))return"المردودات متاحة نقداً أو على الذمة فقط";if(!point)return"اختر نقطة بيع";if(!session)return"يجب فتح عهدة";if(!cart.length)return"السلة فارغة";if(cart.some(line=>!Number.isFinite(line.discount)||line.discount<0||line.discount>Math.min(100,Math.max(0,Number(point.max_discount_percent??100)))||line.price*line.quantity*line.discount/100>line.price*line.quantity+0.009))return"خصم الصنف يجب ألا يتجاوز قيمته أو 100%";if(mode==="gift"){if(!point.allow_gifts)return"الهدايا غير مفعلة لهذه النقطة";if(cart.some(l=>l.quantity>l.available))return"كمية الهدية أكبر من الرصيد المتاح";return null}if(total<=0)return"لا يمكن حفظ فاتورة بإجمالي صفر";if(cashTendered<(payments.find(p=>p.method==="cash")?.amount||0))return"المبلغ النقدي المستلم أقل من الدفعة النقدية";const issue=paymentIssue();if(issue)return issue;if(allocated<total-.009)return"مجموع تفاصيل الدفع أقل من إجمالي الفاتورة";if(allocated>total+.009&&!cashChangeAllowed)return"الزيادة على إجمالي الفاتورة مسموحة للنقد بعملة نقطة البيع فقط";if(payments.some(p=>p.amount>0&&p.method==="cheque"&&!p.reference.trim()))return"رقم الشيك مطلوب";if(payments.some(p=>p.amount>0&&p.method==="gift_card"&&!p.reference.trim()))return"رقم بطاقة الهدية مطلوب";if(payments.some(p=>p.amount>0&&p.method==="account")&&!customerId)return"اختر العميل للدفع على الحساب";if(cart.some(l=>!(mode==="return"?(point.return_account_id||l.returnAccountId):l.accountId)))return mode==="return"?"يوجد صنف بلا حساب مردود مبيعات":"يوجد صنف بلا حساب مبيعات";return null}
 const finish=async()=>{if(pricingBusy)return;const v=validate();if(v){setCheckoutError(v);return}if(editingInvoiceId&&!navigator.onLine){setCheckoutError("تعديل الفاتورة يحتاج اتصالاً بالخادم");return}setSaving(true);const id=makeId(),payload=buildPayload(id),snapshot=cart.map(x=>({...x})),queued:PosQueuedSale={id,tenantKey:baseKey,createdAt:new Date().toISOString(),payload,attempts:0};let completed=false;try{if(!navigator.onLine)throw new TypeError("offline");if(editingInvoiceId){const remove=await fetch(`/api/pos/history?point_id=${pointId}&id=${editingInvoiceId}`,{method:"DELETE"}),removed=await remove.json();if(!remove.ok)throw new Error(errorText(removed,"تعذر إلغاء الفاتورة القديمة"))}const r=await fetch("/api/pos/sales",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){setCheckoutError(errorText(d,"فشل الحفظ"));return}setReceipt({code:String(d.vch_code||""),total,pending:false,lines:snapshot,mode});setMessage({type:"success",text:`تم ${editingInvoiceId?"تعديل":"حفظ"} ${mode==="return"?"المردود":mode==="gift"?"الهدية":"الفاتورة"} ${d.vch_code||""}`});completed=true;await loadSession();await loadCatalogData()}catch(e){if(!(e instanceof TypeError)&&navigator.onLine){setCheckoutError(e instanceof Error?e.message:"فشل الحفظ");return}if(!point?.allow_offline){setCheckoutError("العمل دون اتصال غير مسموح لهذه النقطة");return}await queuePosSale(queued);await updateQueue();setReceipt({code:`OFF-${id.slice(0,8).toUpperCase()}`,total,pending:true,lines:snapshot,mode});setMessage({type:"info",text:"حُفظت العملية على الجهاز وستُزامن تلقائيًا"});completed=true}finally{setSaving(false)}if(completed){setCart([]);setEditingInvoiceId(null);setEditingDraftId(null);focusBarcodeAfterSaveRef.current=true;setCheckoutOpen(false);setMode("sale");resetTransaction();if(pendingActionRef.current){setReceipt(null);resumeTransactionAction()}}}
 const custody=async(sourceId?:number,shiftGuid?:string)=>{if(saving)return;setCustodyError("");if(!navigator.onLine){setCustodyError("عمليات العهدة تحتاج اتصالاً بالخادم");return}setSaving(true);try{const closeAmounts=catalog.currencies.map(row=>({currency_id:row.currency_id,amount:Number(custodyAmounts[row.currency_id]??0)}));const closeTotal=closeAmounts.reduce((sum,row)=>sum+row.amount*Number(session?.currencies?.find((currency:any)=>Number(currency.currency_id)===row.currency_id)?.rate_to_point||catalog.currencies.find(currency=>currency.currency_id===row.currency_id)?.rate_to_point||1),0);const r=await fetch("/api/pos/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:!session?(sourceId?"receive":"open"):custodyAction,point_id:pointId,shift_guid:shiftGuid,amount:custodyAction==="close"?Math.round(closeTotal*100)/100:custodyAmount,currency_id:custodyCurrencyId||point?.currency_id,currency_amounts:(custodyAction==="cash_in"||custodyAction==="cash_out")?catalog.currencies.filter(row=>Number(movementAmounts[row.currency_id]||0)>0).map(row=>({currency_id:row.currency_id,amount:movementAmounts[row.currency_id]})):custodyAction==="close"?closeAmounts:(custodyAction==="open"||custodyAction==="handover")?catalog.currencies.map(row=>({currency_id:row.currency_id,amount:custodyAmounts[row.currency_id]||0})):undefined,note:custodyNote,source_session_id:sourceId})}),d=await r.json();if(!r.ok)throw new Error(d.error);setCatalog(c=>({...c,session:d.session||null}));setMessage({type:"success",text:"تم تنفيذ عملية العهدة بنجاح"});setCustodyOpen(false);setCustodyAmount(0);setCustodyAmounts({});setMovementAmounts({});setCustodyNote("");await loadSession()}catch(e){setCustodyError(e instanceof Error?e.message:"فشلت عملية العهدة")}finally{setSaving(false)}}
 const loadHistory=async(q=historyQuery,scope: "shift"|"all"=historyScope)=>{if(!pointId||!navigator.onLine){setHistoryError("سجل الفواتير يحتاج اتصالاً بالخادم");setHistoryOpen(true);return}const effectiveScope=scope==="shift"&&!session?.id?"all":scope;setHistoryScope(effectiveScope);setHistoryLoading(true);setHistoryError("");setHistoryOpen(true);try{const sessionFilter=effectiveScope==="shift"?`&session_id=${session?.id}`:"",r=await fetch(`/api/pos/history?point_id=${pointId}&q=${encodeURIComponent(q)}${sessionFilter}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(errorText(d,"تعذر تحميل الفواتير"));setHistoryRows(d.rows||[])}catch(e){setHistoryError(e instanceof Error?e.message:"تعذر تحميل الفواتير")}finally{setHistoryLoading(false)}}
 const saveDraft=async()=>{if(saving||draftSaving)return;if(!pointId||!cart.length){setMessage({type:"error",text:"أضف صنفاً واحداً على الأقل قبل حفظ المسودة"});return}if(!session){setMessage({type:"error",text:"يجب فتح العهدة قبل حفظ المسودة"});return}setDraftSaving(true);setDraftError("");try{const r=await fetch("/api/pos/drafts",{method:editingDraftId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:editingDraftId,pos_point_id:pointId,pos_session_id:session.id,pos_customer_id:customerId,salesman_id:salesmanId,pos_mode:mode,note,discount_value:discountValue,items:cart.map(line=>({product_id:line.id,product_code:line.code,product_name:line.name,barcode:line.barcode,unit_id:line.unitId,unit_name:line.unitName,price:line.price,quantity:line.quantity,discount:line.discount,account_id:line.accountId,return_account_id:line.returnAccountId,available:line.available}))})}),d=await r.json();if(!r.ok)throw new Error(errorText(d,"تعذر حفظ مسودة الكاشير"));setMessage({type:"success",text:`تم حفظ المسودة ${d.draft_code||""}`});setCart([]);setCustomerId(null);setSalesmanId(null);setNote("");setDiscountValue(0);setMode("sale")}catch(e){setDraftError(e instanceof Error?e.message:"تعذر حفظ المسودة");setMessage({type:"error",text:e instanceof Error?e.message:"تعذر حفظ المسودة"})}finally{setDraftSaving(false)}}
 const loadDrafts=async()=>{if(!pointId||!navigator.onLine){setDraftError("بحث المسودات يحتاج اتصالاً بالخادم");setDraftOpen(true);return}setDraftLoading(true);setDraftError("");setDraftOpen(true);try{const r=await fetch(`/api/pos/drafts?point_id=${pointId}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(errorText(d,"تعذر تحميل المسودات"));setDraftRows(d.rows||[])}catch(e){setDraftError(e instanceof Error?e.message:"تعذر تحميل المسودات")}finally{setDraftLoading(false)}}
 const openDraft=(draft:any)=>{const lines=(Array.isArray(draft.items)?draft.items:[]).map((item:any)=>{const product=catalog.products.find(row=>row.id===Number(item.product_id));if(!product)return null;return {...product,barcode:String(item.barcode||product.barcode||""),unitId:Number(item.unit_id)||product.unitId,unitName:String(item.unit_name||product.unitName||""),price:Number(item.price||0),quantity:Number(item.quantity||0),discount:Number(item.discount||0),gift:false}}).filter((line:any)=>line&&line.quantity>0);if(!lines.length||lines.length!==(draft.items||[]).length){setDraftError("تعذر مطابقة أصناف المسودة مع كتالوج نقطة البيع");return}setEditingInvoiceId(null);setEditingDraftId(Number(draft.id));setCart(lines);setCustomerId(Number(draft.customer_id)||null);setSalesmanId(Number(draft.salesman_id)||null);setMode(["sale","return","gift"].includes(draft.mode)?draft.mode:"sale");setNote(String(draft.note||""));setDiscountValue(Number(draft.discount_value||0));setPayments([]);setCashCurrencyAmounts({});setCashTendered(0);setDraftOpen(false);setMessage({type:"info",text:`تم فتح المسودة ${draft.draft_code||""}`});requestAnimationFrame(()=>searchRef.current?.focus())}
 const selectHistoryInvoice=async(row:PosInvoice)=>{setHistorySelected(row);setHistoryError("");setHistoryOpen(false);if(!pointId||row.items)return;try{const r=await fetch(`/api/pos/history?point_id=${pointId}&id=${row.id}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(errorText(d,"تعذر تحميل الفاتورة"));setHistorySelected(current=>Number(current?.id)===Number(row.id)?d:current)}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"تعذر تحميل الفاتورة"})}}
 const editHistoryInvoice=async()=>{const invoice=historySelected;if(!invoice?.items?.length)return;if(Number(invoice.vch_type)===9){setMessage({type:"error",text:"تعديل سند الهدية غير متاح من الكاشير"});return}const lines=invoice.items.map(item=>{const product=catalog.products.find(row=>row.id===Number(item.product_id));if(!product)return null;return {...product,quantity:Number(item.qnty??item.quantity??0),discount:Number(item.discount_percent??item.discount??0),gift:false}}).filter((line):line is CartLine=>Boolean(line&&line.quantity>0));if(lines.length!==invoice.items.length){setMessage({type:"error",text:"تعذر مطابقة أصناف الفاتورة الحالية مع كتالوج نقطة البيع"});return}setCart(lines);setCustomerId(Number(invoice.account_id)||null);setSalesmanId(Number(invoice.salesman_id)||null);setNote(String(invoice.note||""));setMode(Number(invoice.vch_type)===16?"return":"sale");setDiscountValue(0);setPayments([]);setCashCurrencyAmounts({});setCashTendered(0);setEditingDraftId(null);setEditingInvoiceId(Number(invoice.id));setHistorySelected(null);setMessage({type:"info",text:`جاري تعديل الفاتورة ${invoice.vch_code}`});requestAnimationFrame(()=>searchRef.current?.focus())}
 const historyIndex=historySelected?historyRows.findIndex(row=>Number(row.id)===Number(historySelected.id)):-1
 const moveHistory=(index:number)=>{const row=historyRows[index];if(row)void selectHistoryInvoice(row)}
 const deleteHistoryInvoice=async(row:PosInvoice)=>{if(!pointId||Number(row.id)<=0||!window.confirm(`تأكيد حذف الفاتورة ${row.vch_code}${row.receipt_vch_code?` وسند القبض المرتبط ${row.receipt_vch_code}`:""}؟`))return;setHistoryDeleting(true);setHistoryError("");try{const r=await fetch(`/api/pos/history?point_id=${pointId}&id=${row.id}`,{method:"DELETE"}),d=await r.json();if(!r.ok)throw new Error(errorText(d,"تعذر حذف الفاتورة"));const index=historyRows.findIndex(item=>Number(item.id)===Number(row.id)),remaining=historyRows.filter(item=>Number(item.id)!==Number(row.id));setHistoryRows(remaining);setHistorySelected(null);if(remaining.length)void selectHistoryInvoice(remaining[Math.min(index,remaining.length-1)]);await loadSession();await loadCatalogData();setMessage({type:"success",text:`تم حذف الفاتورة ${row.vch_code}`})}catch(e){setMessage({type:"error",text:e instanceof Error?e.message:"تعذر حذف الفاتورة"})}finally{setHistoryDeleting(false)}}
 const print=()=>{if(!receipt)return;const rows=receipt.lines.map(l=>`<tr><td>${l.name}</td><td>${l.quantity}</td><td>${l.price.toFixed(2)}</td><td>${round(l.price*l.quantity*(1-l.discount/100)).toFixed(2)}</td></tr>`).join("");const w=window.open("","_blank","width=420,height=680");if(!w)return;w.document.write(`<html dir=rtl><style>body{font-family:Arial;padding:20px}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px dashed #aaa}</style><h2>${receipt.mode==="return"?"مردود مبيعات":mode==="gift"?"سند إخراج هدية":"فاتورة بيع"}</h2><p>${receipt.code}</p><table><tr><th>الصنف</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th></tr>${rows}</table><h2>الإجمالي ${receipt.total.toFixed(2)} ${point?.currency_code||""}</h2></html>`);w.document.close();w.print()}
 const actions=[{label:mode==="gift"?"تأكيد الهدية":"تفاصيل الدفع",icon:CreditCard,onClick:openCheckout},{label:"خصم",icon:Percent,onClick:()=>setDiscountOpen(true)},{label:mode==="return"?"إلغاء المردود":"مردودات",icon:RotateCcw,onClick:()=>{if(!point?.allow_returns)return setMessage({type:"error",text:"المردودات غير مفعلة لهذه النقطة"});const nextMode=mode==="return"?"sale":"return";requestTransactionAction(()=>{resetTransaction();setMode(nextMode)})}},{label:mode==="gift"?"إلغاء الهدية":"هدية",icon:Gift,onClick:()=>{if(!point?.allow_gifts)return setMessage({type:"error",text:"الهدايا غير مفعلة لهذه النقطة"});const nextMode=mode==="gift"?"sale":"gift";requestTransactionAction(()=>{resetTransaction();setMode(nextMode)})}},{label:"ملاحظة",icon:StickyNote,onClick:()=>setNoteOpen(true)},{label:"الفواتير",icon:History,onClick:()=>requestTransactionAction(()=>void loadHistory())},{label:"العهدة F8",icon:HandCoins,onClick:()=>requestTransactionAction(()=>setCustodyOpen(true))},{label:"تحديث",icon:RefreshCw,onClick:()=>void loadCatalogData()}]
 const discountLine=cart.find(line=>posCartLineKey(line)===itemDiscountId)
 return <div dir="rtl" className="pos-workspace" data-mode={mode}>
  {pricingBusy && <div role="status" className="fixed inset-x-0 top-0 z-[1300] bg-teal-700 p-2 text-center text-sm text-white">جاري تحميل أسعار فئة العميل…</div>}
  <ConfirmDialogYesNo visible={Boolean(pendingCustomer)} title="فئة سعر العميل" message="فئة السعر للعميل المختار تختلف عن فئة السعر لنقطة البيع هل تريد احتساب اسعار الاصناف ؟" showBack useAppDialog busy={pricingBusy} confirmLabel="نعم" cancelLabel="لا" backLabel="إلغاء" onConfirm={()=>{if(pendingCustomer)void applyCustomerPrices(pendingCustomer)}} onCancel={keepCustomerPrices} onBack={cancelCustomerSelection} onDismiss={cancelCustomerSelection}/>
  <Dialog open={Boolean(customerPriceError)} onOpenChange={open=>{if(!open)setCustomerPriceError("")}}><DialogContent dir="rtl" className="z-[1200] max-w-md"><DialogHeader><DialogTitle>تعذر اختيار العميل</DialogTitle><DialogDescription>{customerPriceError}</DialogDescription></DialogHeader><DialogFooter><Button onClick={()=>setCustomerPriceError("")}>حسناً</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={unsavedActionOpen} onOpenChange={open=>{if(!open)cancelTransactionAction()}}>
   <DialogContent dir="rtl" className="pos-unsaved-dialog">
    <div className="pos-unsaved-heading"><span className="pos-unsaved-icon"><Save size={24}/></span><DialogHeader><DialogTitle>حفظ التغييرات؟</DialogTitle><DialogDescription>توجد تغييرات غير محفوظة في الحركة الحالية. هل تريد حفظها قبل المتابعة؟</DialogDescription></DialogHeader></div>
    <DialogFooter className="pos-unsaved-actions">
     <Button className="pos-save-continue" onClick={saveAndContinue} disabled={!cart.length||saving||!session}><Save/>حفظ ومتابعة</Button>
     <Button className="pos-discard-continue" variant="outline" onClick={discardAndContinue}><ArrowLeft/>تجاهل ومتابعة</Button>
     <Button variant="outline" onClick={cancelTransactionAction}><X/>إلغاء</Button>
    </DialogFooter>
   </DialogContent>
  </Dialog>
  {noPoints&&<div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-center text-lg font-bold text-amber-800">يجب تعريف نقطة بيع اولا</div>}
  <div className="pos-topbar">
  <header className="pos-toolbar">
   <div className="pos-identity"><span className="pos-brand"><ShoppingBag size={25}/></span><div><span className="pos-eyebrow">مساحة البيع</span><h1>الكاشير</h1></div></div>
   <nav className="pos-toolbar-actions" aria-label="إجراءات نقطة البيع">
    <Button variant="outline" onClick={()=>setNewSaleOpen(true)} disabled={!cart.length||saving}><Plus size={16}/>جديد</Button>
    <Button className="pos-primary-tool" onClick={openCheckout} disabled={!cart.length||saving}><CreditCard size={16}/>الدفع والحفظ <kbd>F4</kbd></Button>
    <Button variant="outline" onClick={()=>requestTransactionAction(()=>void loadHistory())}><History size={16}/>الفواتير</Button>
      <Button variant="outline" onClick={()=>void saveDraft()} disabled={!cart.length||saving||draftSaving}><Bookmark size={16}/>حفظ كمسودة</Button>
      <Button variant="outline" onClick={()=>void loadDrafts()} disabled={draftLoading}><FolderOpen size={16}/>بحث المسودات</Button>
    <Button variant="outline" onClick={()=>requestTransactionAction(()=>setCustodyOpen(true))}><HandCoins size={16}/>العهدة <kbd>F8</kbd></Button>
    <button onClick={()=>void syncPending()} disabled={syncing||!online} className="pos-tool"><RefreshCw size={16} className={cn(syncing&&"animate-spin")}/>مزامنة ({pendingCount})</button>
   </nav>
   <span className={cn("pos-connection",!online&&"is-offline")} role="status">{online?<Wifi size={15}/>:<WifiOff size={15}/>} {online?"متصل":"غير متصل"}</span>
  </header>
  <section className="pos-overview">
   <div className="pos-context"><label htmlFor="pos-point">نقطة البيع الحالية</label><select id="pos-point" value={pointId||""} disabled={cart.length>0||saving} onChange={e=>setPointId(Number(e.target.value)||null)}><option value="">اختر نقطة البيع</option>{points.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></div>
   <div className="pos-shift"><div><UserRound size={15}/><b>{user?.fullName||user?.username||"الكاشير"}</b><time dateTime={today()}>{today()}</time></div><div><Warehouse size={15}/><span>{point?.warehouse_name||"المخزن"}</span><span className={cn("pos-shift-state",!session&&"is-closed")}><span/>{session?"العهدة مفتوحة":"العهدة مغلقة"}</span></div></div>
   <div className="pos-net"><span className="pos-net-icon"><WalletCards size={25}/></span><div><span>{mode==="return"?"الصافي للاسترجاع":mode==="gift"?"إجمالي الهدية":"الصافي للدفع"}</span><strong><bdi>{total.toFixed(2)}</bdi> <small>{point?.currency_code}</small></strong></div></div>
  </section>
  </div>
  {message&&<div role="status" className={cn("flex items-center justify-between rounded-xl border px-4 py-3 text-sm",message.type==="error"?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700")}><span>{message.text}</span><button aria-label="إغلاق الرسالة" onClick={()=>setMessage(null)}><X size={16}/></button></div>}
  <main className="pos-layout">
   <section className="pos-catalog">
    <div className="pos-panel-heading"><div className="pos-panel-title"><span className="pos-heading-icon"><PackageOpen size={20}/></span><div><h2>كتالوج الأصناف</h2><p>اختر الأصناف لإضافتها إلى الفاتورة</p></div></div><span className="pos-count">{shown.length} صنف</span></div>
    <div className="pos-search-field"><Search size={19}/><Input aria-label="البحث باسم الصنف" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الصنف…"/>{query&&<button type="button" aria-label="مسح البحث" onClick={()=>setQuery("")}><X size={16}/></button>}</div>
    <div className="pos-categories" aria-label="تصنيفات الأصناف"><button type="button" aria-pressed={category==="all"} onClick={()=>setCategory("all")} title="كل الأصناف"><span>الكل</span><small>{productsForSale.length}</small></button>{categories.map(group=><button type="button" key={group.name} aria-pressed={category===group.name} onClick={()=>setCategory(group.name)} title={group.name}><span>{group.name}</span><small>{group.count}</small></button>)}</div>
    <div className="pos-products" aria-busy={loading}>{loading?<div className="pos-empty"><RefreshCw className="animate-spin"/>جاري تحميل الأصناف…</div>:shown.length?shown.slice(0,visibleLimit).map(p=><button key={p.id} onClick={()=>add(p)} className="pos-product" aria-label={`إضافة ${p.name}`} disabled={pricingBusy}>
     <div className="pos-product-visual"><small className="pos-product-code" dir="ltr">{p.code}</small><span className={cn("pos-product-icon",p.image&&"has-image")}>{p.image?<img src={p.image} alt="" loading="lazy"/>:<PackageOpen size={34}/>}</span><span className="pos-product-add" aria-hidden="true"><Plus size={16}/></span></div>
     <div className="pos-product-details"><b>{p.name}</b><small className={cn("pos-stock",p.available<=0&&"is-unavailable")}><span/>{p.available} {p.unitName||"وحدة"}</small><strong><bdi>{p.price.toFixed(2)}</bdi><small>{point?.currency_code}</small></strong></div>
    </button>):<div className="pos-empty"><span className="pos-empty-icon"><Search size={32}/></span><h3>لا توجد أصناف مطابقة</h3><button className="pos-tool" onClick={()=>{setQuery("");setCategory("all")}}>مسح البحث والتصنيف</button></div>}</div>
    {shown.length>visibleLimit&&<button className="pos-tool mx-3 mb-3" onClick={()=>setVisibleLimit(limit=>limit+180)}>عرض المزيد ({shown.length-visibleLimit})</button>}
   </section>
   <section className="pos-sale">
    <div className="pos-panel-heading"><div className="pos-panel-title"><span className="pos-heading-icon"><ShoppingCart size={20}/></span><div><h2>{historySelected?`عرض الفاتورة ${historySelected.vch_code}`:mode==="return"?"مردود مبيعات":mode==="gift"?"هدية":"الفاتورة الحالية"}</h2><p>{historySelected?`${historySelected.items?.length||0} أصناف`:`${cart.length} أصناف · ${cart.reduce((s,l)=>s+l.quantity,0)} وحدات`}</p></div></div><span className={cn("pos-mode-badge",`is-${mode}`)}>{historySelected?"عرض":editingInvoiceId?"تعديل":mode==="return"?"مردود":mode==="gift"?"هدية":"بيع جديد"}</span></div>
    {!historySelected&&<div className="pos-parties">{(["customer","salesman"] as const).map(kind=><PosPartyButton key={kind} kind={kind} selected={kind==="customer"?catalog.customers.find(c=>c.id===customerId):(catalog.salesmen||[]).find(c=>c.id===salesmanId)} onOpen={()=>setPartyPicker(kind)} onClear={()=>kind==="customer"?selectCustomer(null):setSalesmanId(null)}/>)}</div>}
    <div className="pos-search-field pos-barcode-field"><Barcode size={21}/><Input ref={searchRef} autoFocus aria-label="إدخال باركود الصنف" value={barcodeQuery} onChange={e=>setBarcodeQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();if(!e.nativeEvent.isComposing)searchEnter()}}} placeholder="امسح أو أدخل الباركود ثم Enter…"/><kbd>F2</kbd></div>
    <div className="pos-cart" aria-label="أصناف الفاتورة">
     {historySelected?<div className="space-y-3">
      <div className="flex flex-wrap items-center gap-1 rounded-xl border bg-slate-50 p-2 dark:bg-slate-900">
       <Button size="icon" variant="outline" disabled={historyIndex<=0} onClick={()=>moveHistory(0)} aria-label="أول فاتورة"><ChevronsRight size={16}/></Button>
       <Button size="icon" variant="outline" disabled={historyIndex<=0} onClick={()=>moveHistory(historyIndex-1)} aria-label="الفاتورة السابقة"><ChevronRight size={16}/></Button>
       <span className="min-w-16 text-center text-xs">{historyIndex>=0?`${historyIndex+1} / ${historyRows.length}`:"—"}</span>
       <Button size="icon" variant="outline" disabled={historyIndex<0||historyIndex>=historyRows.length-1} onClick={()=>moveHistory(historyIndex+1)} aria-label="الفاتورة التالية"><ChevronLeft size={16}/></Button>
       <Button size="icon" variant="outline" disabled={historyIndex<0||historyIndex>=historyRows.length-1} onClick={()=>moveHistory(historyRows.length-1)} aria-label="آخر فاتورة"><ChevronsLeft size={16}/></Button>
    <Button size="sm" variant="outline" disabled={!historySelected.items?.length||historyDeleting} onClick={editHistoryInvoice}><Pencil size={15}/>تعديل وحفظ</Button>
    <Button size="sm" variant="outline" className="text-rose-700" disabled={Number(historySelected.id)<=0||historyDeleting} onClick={()=>void deleteHistoryInvoice(historySelected)}><Trash2 size={15}/>حذف</Button>
      <Button size="sm" variant="outline" onClick={()=>{setHistorySelected(null);setEditingInvoiceId(null);setEditingDraftId(null);requestAnimationFrame(()=>searchRef.current?.focus())}}><Plus size={15}/>فاتورة جديدة</Button>
      </div>
      <div className="grid gap-2 rounded-xl border bg-white p-3 text-sm sm:grid-cols-3 dark:bg-slate-950"><div><small className="text-slate-500">العميل</small><b className="block">{historySelected.customer_name||"عميل نقدي"}</b></div><div><small className="text-slate-500">التاريخ</small><b className="block">{String(historySelected.vch_date).slice(0,10)}</b></div><div><small className="text-slate-500">الإجمالي</small><b dir="ltr" className="block text-emerald-700">{Number(historySelected.amount||0).toFixed(2)} {point?.currency_code}</b></div></div>
      {!!historySelected.payments?.length&&<div className="flex flex-wrap gap-2">{historySelected.payments.map((payment,index)=><span key={index} className="rounded-lg bg-slate-100 px-3 py-2 text-xs dark:bg-slate-800">{paymentLabels[payment.method as PaymentKey]||payment.method}: {Number(payment.amount||0).toFixed(2)}{payment.reference?` · ${payment.reference}`:""}</span>)}</div>}
      {(historySelected.items||[]).map((item,index)=><article key={item.id||index} className="pos-cart-line"><div className="pos-line-name"><small>{index+1}</small><b>{item.product_name||item.item_name||"—"}</b><small>{Number(item.price||0).toFixed(2)}</small></div><strong>{Number(item.qnty??item.quantity??0)}</strong><strong className="pos-line-total">{Number(item.total_price??item.line_amount??0).toFixed(2)}</strong></article>)}
      {!historySelected.items&&<p className="py-8 text-center text-sm text-slate-500">جاري تحميل تفاصيل الفاتورة...</p>}
     </div>:cart.length?cart.map((l,index)=><article key={posCartLineKey(l)} className={cn("pos-cart-line",selectedLineId===posCartLineKey(l)&&"is-selected",l.gift&&"is-gift")}>
      <button className="pos-line-name" aria-pressed={selectedLineId===posCartLineKey(l)} onClick={()=>{setSelectedLineId(posCartLineKey(l));setQuantityEntry(String(l.quantity))}}><small>{index+1} · {l.code}{l.barcode?` · ${l.barcode}`:""}</small><b>{l.name}</b><small>{l.price.toFixed(2)} / {l.unitName||"وحدة"}{l.gift?" · هدية":l.discount?` · خصم ${l.discount}%`:""}</small></button>
      <div className="pos-quantity"><button aria-label={`تقليل كمية ${l.name}`} onClick={()=>changeQty(posCartLineKey(l),-1)}><Minus size={16}/></button><strong>{l.quantity}</strong><button aria-label={`زيادة كمية ${l.name}`} onClick={()=>changeQty(posCartLineKey(l),1)}><Plus size={16}/></button></div>
      <button type="button" className="pos-item-discount" disabled={mode==="gift"||saving} onClick={()=>setItemDiscountId(posCartLineKey(l))} aria-label={`خصم الصنف ${l.name}`}><Percent size={15}/><span>{l.discount?`${Number(l.discount.toFixed(2))}%`:"خصم"}</span></button>
      <strong className="pos-line-total">{round(l.price*l.quantity*(1-l.discount/100)).toFixed(2)}</strong><button className="pos-remove" aria-label={`حذف ${l.name}`} onClick={()=>setCart(c=>c.filter(x=>posCartLineKey(x)!==posCartLineKey(l)))}><Trash2 size={17}/></button>
     </article>):<div className="pos-empty"><span className="pos-empty-icon"><ShoppingCart size={38}/><span className="pos-empty-plus"><Plus size={16}/></span></span><h3>فاتورتك جاهزة للبدء</h3><p>اختر صنفاً من الكتالوج أو امسح الباركود</p><span className="pos-empty-hint"><Barcode size={16}/> إدخال سريع <kbd>F2</kbd></span></div>}
    </div>
    {!historySelected&&<><div className="pos-checkout-dock">
     <div className="pos-keypad"><label htmlFor="pos-quantity-entry">كمية الصنف المحدد</label><div className="flex gap-1"><Input id="pos-quantity-entry" inputMode="decimal" value={quantityEntry} disabled={!cart.some(l=>posCartLineKey(l)===selectedLineId)} onChange={e=>setQuantityEntry(e.target.value)} onKeyDown={e=>e.key==="Enter"&&applyQuantity()}/><Button variant="outline" onClick={applyQuantity} disabled={!cart.some(l=>posCartLineKey(l)===selectedLineId)}>تطبيق</Button></div><div className="pos-keypad-keys" dir="ltr">{["1","2","3","4","5","6","7","8","9","⌫","0","."].map(key=><button key={key} disabled={!cart.some(l=>posCartLineKey(l)===selectedLineId)} aria-label={key==="⌫"?"مسح رقم":key} onClick={()=>setQuantityEntry(v=>key==="⌫"?v.slice(0,-1):key==="."&&v.includes(".")?v:v+key)}>{key}</button>)}</div></div>
     <nav className="pos-actions" aria-label="إجراءات الفاتورة">{actions.map(a=><button key={a.label} onClick={a.onClick} disabled={(a.label==="تفاصيل الدفع"||a.label==="تأكيد الهدية")&&!cart.length||mode==="gift"&&a.label==="خصم"}><span><a.icon size={18}/></span>{a.label}</button>)}</nav>
     <div className="pos-totals"><h3>ملخص الفاتورة <span>{point?.currency_code}</span></h3><div><span>مجموع الأصناف</span><b>{cart.reduce((s,l)=>s+l.price*l.quantity,0).toFixed(2)}</b></div><div><span>خصم الأصناف</span><b>{cart.reduce((s,l)=>s+l.price*l.quantity*l.discount/100,0).toFixed(2)}</b></div><div><span>الضريبة</span><b>{tax.toFixed(2)}</b></div><div><span>خصم الفاتورة</span><b>{invoiceDiscount.toFixed(2)}</b></div><div className="pos-total-due"><span>{mode==="return"?"الصافي للاسترجاع":mode==="gift"?"إجمالي الهدية":"الصافي للدفع"}</span><strong>{total.toFixed(2)}</strong></div><Button className="pos-checkout-button" disabled={!cart.length||saving} onClick={openCheckout}><CreditCard size={18}/><span>{mode==="return"?"إعادة المبلغ":mode==="gift"?"إخراج الهدية":"إتمام البيع"}</span><kbd>F4</kbd></Button></div>
    </div>
    {note&&<div className="px-4 pb-3 text-xs text-slate-500">ملاحظة: {note}</div>}</>}
   </section>
  </main>
   <Dialog open={newSaleOpen} onOpenChange={setNewSaleOpen}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>بدء فاتورة جديدة؟</DialogTitle><DialogDescription>سيتم مسح أصناف الفاتورة الحالية غير المحفوظة.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setNewSaleOpen(false)}>لا، متابعة الفاتورة</Button><Button onClick={()=>{setCart([]);setNote("");setCustomerId(null);setSalesmanId(null);setEditingInvoiceId(null);setEditingDraftId(null);setMode("sale");setSelectedLineId(null);setQuantityEntry("");setCustomerProducts(null);setNewSaleOpen(false);searchRef.current?.focus()}}>نعم، فاتورة جديدة</Button></DialogFooter></DialogContent></Dialog>

 {partyPicker&&<PosPartyPicker title={partyPicker==="customer"?"بحث الحساب":"بحث المندوب"} rows={partyPicker==="customer"?catalog.customers:catalog.salesmen||[]} onClose={()=>setPartyPicker(null)} onSelect={id=>{if(partyPicker==="customer")selectCustomer(id);else setSalesmanId(id);setPartyPicker(null)}}/>}
 <PosPaymentDetailsDialog open={checkoutOpen} onOpenChange={open=>{setCheckoutOpen(open);if(!open)pendingActionRef.current=null}} mode={mode} total={total} currencyCode={point?.currency_code||""} pointCurrencyId={Number(point?.currency_id||0)} currencies={catalog.currencies} customers={catalog.customers} customerId={customerId} onCustomerChange={selectCustomer} banks={catalog.banks} branches={catalog.bankBranches} cardTypes={catalog.cardTypes.filter(card=>Number(card.currency_id)===Number(point?.currency_id))} payments={payments} cashAmounts={cashCurrencyAmounts} onCashChange={updateCashCurrency} onPaymentAmount={(method,value,currencyId)=>{updatePayment(method,value,undefined,currencyId);setCheckoutError("")}} onPaymentField={updatePaymentField} onConfirm={()=>void finish()} onSavedClose={()=>{if(!focusBarcodeAfterSaveRef.current)return false;focusBarcodeAfterSaveRef.current=false;searchRef.current?.focus();return true}} busy={saving} error={checkoutError}/>
 <PosStartSessionDialog open={custodyOpen&&!session&&!!point&&!noPoints} onOpenChange={setCustodyOpen} userName={user?.fullName||user?.username||""} currency={point?.currency_name||""} amount={custodyAmount} onAmountChange={setCustodyAmount} currencies={catalog.currencies} amounts={custodyAmounts} onCurrencyAmountChange={(currencyId,amount)=>setCustodyAmounts(current=>({...current,[currencyId]:amount}))} busy={saving} online={online} error={custodyError} pending={pendingHandovers} activeShift={activePointShift} onConfirm={(sourceId,shiftGuid)=>void custody(sourceId,shiftGuid)}/>
 <PosHandoverDialog open={custodyOpen&&!!session} onOpenChange={setCustodyOpen} session={session} userName={user?.fullName||user?.username||""} currencyCode={point?.currency_code||""} currencies={catalog.currencies} action={custodyAction} onActionChange={action=>{setCustodyAction(action);setCustodyAmount(0);setMovementAmounts({});}} amount={custodyAmount} onAmountChange={setCustodyAmount} currencyId={custodyCurrencyId||Number(point?.currency_id||catalog.currencies[0]?.currency_id)} onCurrencyIdChange={setCustodyCurrencyId} amounts={custodyAmounts} onCurrencyAmountChange={(id,amount)=>{custodyAmountsEditedRef.current=true;setCustodyAmounts(current=>({...current,[id]:amount}))}} movementAmounts={movementAmounts} onMovementAmountChange={(id,amount)=>setMovementAmounts(current=>({...current,[id]:amount}))} note={custodyNote} onNoteChange={setCustodyNote} onConfirm={()=>void custody()} busy={saving} error={custodyError}/>
 {discountOpen&&<PosDiscountDialog subtotal={subtotal} itemDiscount={cart.reduce((sum,line)=>sum+line.price*line.quantity*line.discount/100,0)} customer={catalog.customers.find(c=>c.id===customerId)?.name||"عميل نقدي"} maximum={Number(point?.max_discount_percent??100)} initialPercent={discountValue} taxPercent={Number(point?.tax_percent||0)} onApply={percent=>{setDiscountValue(percent);setDiscountOpen(false)}} onClose={()=>setDiscountOpen(false)}/>}
 {discountLine&&<PosItemDiscountDialog key={itemDiscountId} itemName={discountLine.name} gross={discountLine.price*discountLine.quantity} maximum={Number(point?.max_discount_percent??100)} initialPercent={discountLine.discount} onApply={percent=>{setCart(lines=>lines.map(line=>posCartLineKey(line)===itemDiscountId?{...line,discount:percent}:line));setItemDiscountId(null)}} onClose={()=>setItemDiscountId(null)}/>}
 <Dialog open={noteOpen} onOpenChange={setNoteOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>ملاحظة الفاتورة</DialogTitle></DialogHeader><textarea value={note} onChange={e=>setNote(e.target.value)} rows={5} className="w-full rounded-xl border p-3"/><DialogFooter><Button onClick={()=>setNoteOpen(false)}>حفظ الملاحظة</Button></DialogFooter></DialogContent></Dialog>
 <PosInvoiceHistoryDialog open={historyOpen} onOpenChange={setHistoryOpen} rows={historyRows} query={historyQuery} onQueryChange={setHistoryQuery} scope={historyScope} onScopeChange={scope=>{setHistoryScope(scope);void loadHistory(historyQuery,scope)}} onSearch={()=>void loadHistory(historyQuery,historyScope)} onSelect={row=>void selectHistoryInvoice(row)} loading={historyLoading} error={historyError} currencyCode={point?.currency_code||""} hasShift={!!session?.id}/>
 <Dialog open={draftOpen} onOpenChange={setDraftOpen}><DialogContent dir="rtl" className="flex max-h-[88dvh] w-[min(94vw,680px)] max-w-none flex-col overflow-hidden p-0"><DialogHeader className="shrink-0 border-b bg-amber-50 px-5 py-4 text-right"><DialogTitle className="flex items-center gap-2 text-base"><FolderOpen className="h-5 w-5 text-amber-700"/>بحث المسودات</DialogTitle><DialogDescription>اختر مسودة لاستكمالها في الكاشير. المسودة لا تنشئ فاتورة حتى تضغط الدفع والحفظ.</DialogDescription></DialogHeader>{draftError&&<p className="mx-4 mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{draftError}</p>}<div className="min-h-0 flex-1 overflow-y-auto bg-slate-50 p-3">{draftLoading?<p className="py-12 text-center text-sm text-slate-500">جاري تحميل المسودات...</p>:draftRows.length?draftRows.map(draft=><button key={draft.id} type="button" onClick={()=>openDraft(draft)} className="mb-2 flex w-full items-center justify-between gap-3 rounded-xl border bg-white p-3 text-right transition hover:border-amber-400 hover:bg-amber-50"><div><strong>{draft.draft_code}</strong><p className="mt-1 text-xs text-slate-500">{draft.customer_name||"عميل نقدي"} · {Array.isArray(draft.items)?draft.items.length:0} أصناف</p></div><span className="text-xs text-slate-500">{String(draft.updated_at||draft.created_at||"").slice(0,16).replace("T"," ")}</span></button>):<p className="py-12 text-center text-sm text-slate-500">لا توجد مسودات محفوظة</p>}</div></DialogContent></Dialog>
 <Dialog open={Boolean(receipt)} onOpenChange={o=>!o&&setReceipt(null)}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>{receipt?.mode==="return"?"تم حفظ المردود":receipt?.mode==="gift"?"تم إصدار سند الهدية":"تمت عملية البيع"}</DialogTitle><DialogDescription>{receipt?.pending?"نسخة محلية بانتظار المزامنة":receipt?.mode==="gift"?"تم إخراج الهدية من المخزون":"تم ترحيل الحركة والمخزون والمدفوعات"}</DialogDescription></DialogHeader><div className="rounded-2xl bg-slate-950 p-5 text-center text-white"><small className="text-slate-400">رقم الحركة</small><p className="text-xl font-black text-emerald-300">{receipt?.code}</p><p className="mt-4 text-3xl font-black">{receipt?.total.toFixed(2)} {point?.currency_code}</p></div><DialogFooter><Button variant="outline" onClick={()=>setReceipt(null)}>عملية جديدة</Button><Button onClick={print}><Printer className="ml-2 h-4 w-4"/>طباعة</Button></DialogFooter></DialogContent></Dialog>
 </div>
}

function Field({label,children}:any){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
