"use client"

import {useCallback,useEffect,useMemo,useState} from "react"
import {BadgeDollarSign,Building2,CreditCard,Edit3,Package,Plus,RefreshCw,Save,Store,Trash2,Users,X} from "lucide-react"
import {Button} from "@/components/ui/button"
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog"
import {Input} from "@/components/ui/input"
import {Label} from "@/components/ui/label"
import {Switch} from "@/components/ui/switch"

type Option={id:number;code?:string;name:string;currency_id?:number}
type Meta={branches:Option[];warehouses:Option[];currencies:Option[];books:Option[];accounts:Option[];users:{user_id:string;name:string}[];priceCategories:Option[]}
type Point=Record<string,any>&{id:number;code:string;name:string;users:any[]}
const empty={code:"",name:"",branch_id:"",main_warehouse_id:"",currency_id:"",sales_book_id:"",return_book_id:"",cash_account_id:"",card_account_id:"",cheque_account_id:"",receivable_account_id:"",gift_account_id:"",walk_in_account_id:"",tax_account_id:"",price_category_id:"",tax_percent:0,max_discount_percent:100,allow_offline:true,allow_returns:true,allow_gifts:true,users:[] as any[]}

function Field({label,children}:any){return <div className="min-w-0 space-y-1.5"><Label>{label}</Label>{children}</div>}
function SelectField({value,onChange,options,placeholder="اختر..."}:any){return <select value={value??""} onChange={e=>onChange(e.target.value)} className="h-11 min-w-0 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100"><option value="">{placeholder}</option>{options.map((x:any)=><option key={x.id??x.user_id} value={x.id??x.user_id}>{x.code?`${x.code} — `:""}{x.name}</option>)}</select>}

export default function PosPointsSettings(){
 const [points,setPoints]=useState<Point[]>([]),[meta,setMeta]=useState<Meta>({branches:[],warehouses:[],currencies:[],books:[],accounts:[],users:[],priceCategories:[]}),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState<any>(empty),[message,setMessage]=useState("")
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/pos/points?meta=1",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);setPoints(d.points||[]);setMeta(d.meta||meta)}catch(e){setMessage(e instanceof Error?e.message:"تعذر التحميل")}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const currencyAccounts=useMemo(()=>meta.accounts.filter(a=>!form.currency_id||!a.currency_id||Number(a.currency_id)===Number(form.currency_id)),[meta.accounts,form.currency_id])
 const edit=(point?:Point)=>{setForm(point?{...empty,...point,users:Array.isArray(point.users)?point.users:[]}:{...empty,price_category_id:meta.priceCategories[0]?.id?String(meta.priceCategories[0].id):""});setMessage("");setOpen(true)}
 const save=async()=>{setSaving(true);setMessage("");try{const r=await fetch("/api/pos/points",{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.error);setOpen(false);await load()}catch(e){setMessage(e instanceof Error?e.message:"تعذر الحفظ")}finally{setSaving(false)}}
 const remove=async(point:Point)=>{if(!confirm(`حذف نقطة البيع ${point.name}؟`))return;const r=await fetch("/api/pos/points",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:point.id,status:3})});const d=await r.json();if(!r.ok)setMessage(d.error||"تعذر الحذف");else await load()}
 const account=(key:string,label:string)=><Field label={label}><SelectField value={form[key]} onChange={(v:string)=>setForm({...form,[key]:v})} options={currencyAccounts} placeholder="ابحث بالرقم أو الاسم"/></Field>
 return <div dir="rtl" className="min-h-full w-full bg-gradient-to-br from-emerald-50 via-white to-cyan-50 p-3 sm:p-6">
    <div className="w-full space-y-5">
     <header className="relative overflow-hidden rounded-[28px] border border-emerald-200 bg-gradient-to-l from-emerald-700 via-teal-600 to-cyan-600 p-6 text-white shadow-xl shadow-emerald-900/10"><div className="absolute -left-16 -top-20 h-56 w-56 rounded-full bg-white/15 blur-3xl"/><div className="relative flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-white/20 text-white ring-1 ring-white/25"><Store/></div><div><p className="text-xs font-bold text-emerald-100">نظام البيع بالتجزئة</p><h1 className="text-2xl font-black">إعداد نقاط البيع</h1><p className="mt-1 text-sm text-emerald-50/80">مخزن وحسابات ودفاتر وصلاحيات مستقلة لكل نقطة</p></div></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()} className="border-white/30 bg-white/10 text-white hover:bg-white/20"><RefreshCw className="ml-2 h-4 w-4"/>تحديث</Button><Button onClick={()=>edit()} className="bg-white font-black text-emerald-700 hover:bg-emerald-50"><Plus className="ml-2 h-4 w-4"/>نقطة جديدة</Button></div></div></header>
   {message&&!open&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{message}</div>}
   {loading?<div className="grid h-64 place-items-center"><RefreshCw className="animate-spin text-emerald-600"/></div>:points.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{points.map(p=><article key={p.id} className="group overflow-hidden rounded-3xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="h-1.5 bg-gradient-to-l from-emerald-400 to-cyan-500"/><div className="p-5"><div className="flex items-start justify-between"><div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">{p.code}</span><h2 className="mt-3 text-xl font-black">{p.name}</h2></div><div className="flex gap-1"><button onClick={()=>edit(p)} className="rounded-xl bg-slate-100 p-2 text-slate-600 hover:bg-emerald-50 hover:text-emerald-700"><Edit3 className="h-4 w-4"/></button><button onClick={()=>void remove(p)} className="rounded-xl bg-slate-100 p-2 text-slate-600 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></div></div><div className="mt-5 grid grid-cols-2 gap-2 text-sm"><div className="rounded-2xl bg-slate-50 p-3"><Building2 className="mb-2 h-4 w-4 text-indigo-500"/><span className="text-xs text-slate-400">الفرع</span><p className="truncate font-bold">{p.branch_name}</p></div><div className="rounded-2xl bg-slate-50 p-3"><Package className="mb-2 h-4 w-4 text-amber-500"/><span className="text-xs text-slate-400">المخزن الرئيسي</span><p className="truncate font-bold">{p.warehouse_name}</p></div><div className="rounded-2xl bg-slate-50 p-3"><BadgeDollarSign className="mb-2 h-4 w-4 text-emerald-600"/><span className="text-xs text-slate-400">العملة</span><p className="truncate font-bold">{p.currency_name}</p></div><div className="rounded-2xl bg-slate-50 p-3"><Users className="mb-2 h-4 w-4 text-cyan-600"/><span className="text-xs text-slate-400">الكاشير</span><p className="font-bold">{p.users?.length||"كل المستخدمين"}</p></div></div></div></article>)}</div>:<div className="grid h-72 place-items-center rounded-3xl border border-dashed bg-white text-center"><div><Store className="mx-auto h-12 w-12 text-slate-300"/><h2 className="mt-3 font-black">لم تُعرّف نقاط بيع بعد</h2><Button onClick={()=>edit()} className="mt-4">إضافة أول نقطة بيع</Button></div></div>}
  </div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent hideCloseButton className="flex h-[min(92dvh,850px)] max-h-[calc(100%-1.5rem)] w-[calc(100%-1.5rem)] max-w-5xl flex-col gap-0 overflow-hidden p-0"><div className="z-10 flex shrink-0 items-start justify-between gap-4 bg-gradient-to-l from-emerald-700 to-teal-600 p-4 pr-5 text-white sm:p-5"><DialogHeader className="min-w-0 text-right"><DialogTitle className="text-lg sm:text-xl">{form.id?"تعديل نقطة البيع":"إضافة نقطة بيع"}</DialogTitle><DialogDescription className="text-emerald-50/80">هذه الإعدادات تُفرض على الكاشير عند البيع والمردود.</DialogDescription></DialogHeader><button type="button" aria-label="إغلاق" onClick={()=>setOpen(false)} className="shrink-0 rounded-full bg-white/15 p-2 hover:bg-white/25"><X className="h-4 w-4"/></button></div><div className="min-h-0 min-w-0 flex-1 space-y-6 overflow-y-auto p-4 sm:p-5">
   {message&&<div className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{message}</div>}
   <section><h3 className="mb-3 font-black">التعريف والمخزن</h3><div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,220px),1fr))] gap-4"><Field label="رمز نقطة البيع *"><Input value={form.code} maxLength={12} onChange={e=>setForm({...form,code:e.target.value})}/></Field><Field label="اسم نقطة البيع *"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="الفرع *"><SelectField value={form.branch_id} onChange={(v:string)=>setForm({...form,branch_id:v})} options={meta.branches}/></Field><Field label="المخزن الرئيسي *"><SelectField value={form.main_warehouse_id} onChange={(v:string)=>setForm({...form,main_warehouse_id:v})} options={meta.warehouses}/></Field><Field label="العملة *"><SelectField value={form.currency_id} onChange={(v:string)=>setForm({...form,currency_id:v})} options={meta.currencies}/></Field><Field label="فئة السعر *"><SelectField value={form.price_category_id} onChange={(value:string)=>setForm({...form,price_category_id:value})} options={meta.priceCategories} placeholder="اختر فئة السعر"/></Field></div></section>
   <section className="rounded-2xl bg-slate-50 p-4"><h3 className="mb-3 flex items-center gap-2 font-black"><CreditCard className="h-5 w-5 text-emerald-600"/>الدفاتر والحسابات</h3><div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,220px),1fr))] gap-4"><Field label="دفتر فواتير البيع *"><SelectField value={form.sales_book_id} onChange={(v:string)=>setForm({...form,sales_book_id:v})} options={meta.books}/></Field><Field label="دفتر المردود"><SelectField value={form.return_book_id} onChange={(v:string)=>setForm({...form,return_book_id:v})} options={meta.books}/></Field>{account("cash_account_id","حساب الصندوق *")}{account("card_account_id","حساب البطاقات")}{account("cheque_account_id","حساب الشيكات")}{account("receivable_account_id","حساب الذمم")}{account("gift_account_id","حساب بطاقات الهدايا")}{account("walk_in_account_id","حساب العميل النقدي")}{account("tax_account_id","حساب الضريبة")}</div></section>
   <section><h3 className="mb-3 font-black">السياسات والكاشير</h3><div className="grid grid-cols-[repeat(auto-fit,minmax(min(100%,220px),1fr))] gap-4"><Field label="نسبة الضريبة"><Input type="number" min="0" step=".01" value={form.tax_percent} onChange={e=>setForm({...form,tax_percent:e.target.value})}/></Field><Field label="أقصى خصم %"><Input type="number" min="0" max="100" value={form.max_discount_percent} onChange={e=>setForm({...form,max_discount_percent:e.target.value})}/></Field><div className="space-y-2">{[["allow_offline","العمل دون اتصال"],["allow_returns","السماح بالمردودات"],["allow_gifts","السماح بالهدايا"]].map(([k,l])=><label key={k} className="flex items-center justify-between rounded-xl border bg-white p-3 text-sm font-bold"><span>{l}</span><Switch checked={Boolean(form[k])} onCheckedChange={v=>setForm({...form,[k]:v})}/></label>)}</div><div className="col-span-full min-w-0"><Label>المستخدمون المسموحون</Label><p className="mb-2 text-xs text-slate-400">اترك الجميع دون تحديد لإتاحة النقطة لكل مستخدمي الفرع.</p><div className="grid max-h-40 gap-2 overflow-y-auto rounded-xl border bg-white p-3 sm:grid-cols-2">{meta.users.map(u=>{const checked=form.users.some((x:any)=>String(x.user_id||x)===u.user_id);return <label key={u.user_id} className="flex items-center gap-2 rounded-lg p-2 hover:bg-slate-50"><input type="checkbox" checked={checked} onChange={e=>setForm({...form,users:e.target.checked?[...form.users,{user_id:u.user_id}]:form.users.filter((x:any)=>String(x.user_id||x)!==u.user_id)})}/><span className="text-sm">{u.name}</span></label>})}</div></div></div></section>
  </div><DialogFooter className="shrink-0 flex-wrap gap-2 border-t bg-white p-3 sm:p-4"><Button variant="outline" onClick={()=>setOpen(false)}>إلغاء</Button><Button disabled={saving} onClick={()=>void save()} className="bg-emerald-600 hover:bg-emerald-700">{saving?<RefreshCw className="ml-2 h-4 w-4 animate-spin"/>:<Save className="ml-2 h-4 w-4"/>}حفظ الإعداد</Button></DialogFooter></DialogContent></Dialog>
 </div>
}
