"use client"

import { ReportShiftFilter, type ReportShift } from "@/components/reports/report-shift-filter"
import { ReportFilters } from "@/components/reports/report-filters"
import { BalanceSheetTable, IncomeStatementTable } from "@/components/reports/statement-tables"

import { useEffect, useMemo, useState } from "react"
import { ReportSummaryCard } from "@/components/reports/report-summary-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ReportCurrencyFilter, OtherCurrenciesFilter } from "@/components/reports/report-currency-filter"
import { VoucherLink } from "@/components/reports/voucher-link"
import { Switch } from "@/components/ui/switch"
import { ReportMultiChoice, type ReportOption } from "@/components/reports/account-statement-report"
import { Activity, ArrowDownLeft, ArrowUpRight, BarChart3, BookOpen, CalendarRange, Download, FileBarChart, FileText, Landmark, Loader2, Printer, RefreshCcw, Search, Scale, SlidersHorizontal } from "lucide-react"

export type FinancialReportType = "vouchers" | "transactions" | "trial-balance" | "balance-sheet" | "income-statement"
type Meta = { accounts: ReportOption[]; currencies: ReportOption[]; branches: ReportOption[]; salesmen: ReportOption[]; voucher_types: ReportOption[]; shifts: ReportShift[] }
type Row = Record<string, any> & { id: number }
type Summary = Record<string, number>

const currentDate = () => new Date().toISOString().slice(0,10)
const firstDate = () => `${currentDate().slice(0,4)}-01-01`
const formatter = new Intl.NumberFormat("ar",{minimumFractionDigits:2,maximumFractionDigits:2})
const emptyMeta:Meta={accounts:[],currencies:[],branches:[],salesmen:[],voucher_types:[],shifts:[]}
const configs:Record<FinancialReportType,{title:string;description:string;icon:any;accent:string}>={
  vouchers:{title:"تقرير السندات",description:"مراجعة السندات وقيمها وحالة ترحيلها والحسابات المرتبطة بها",icon:FileText,accent:"from-cyan-500 to-blue-600"},
  transactions:{title:"تقرير الحركات",description:"تفاصيل جميع الأسطر المحاسبية مع الحساب المقابل والعملة والفرع",icon:Activity,accent:"from-teal-500 to-emerald-600"},
  "trial-balance":{title:"ميزان المراجعة",description:"الأرصدة الافتتاحية وحركة المدين والدائن والرصيد النهائي لكل حساب",icon:Scale,accent:"from-indigo-500 to-violet-600"},
  "balance-sheet":{title:"الميزانية العمومية",description:"عرض الأصول والالتزامات بحسب البنود المعرفة في شجرة الحسابات",icon:Landmark,accent:"from-sky-500 to-indigo-600"},
  "income-statement":{title:"قائمة الدخل",description:"تحليل الإيرادات والمصروفات وصافي نتيجة الفترة المالية",icon:BarChart3,accent:"from-fuchsia-500 to-rose-600"},
}

export function FinancialReport({type}:{type:FinancialReportType}) {
  const config=configs[type], Icon=config.icon
  const [meta,setMeta]=useState<Meta>(emptyMeta),[rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState<Summary>({})
  const [loadingMeta,setLoadingMeta]=useState(true),[loading,setLoading]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState("")
  const [filters,setFilters]=useState({accountIds:[] as number[],currencyIds:[] as number[],branchIds:[] as number[],salesmanIds:[] as number[],voucherTypes:[] as number[],shiftGuid:"",fromDate:firstDate(),toDate:currentDate(),status:"all",level:"1",evaluateInventory:false,valuationMethod:"average",showOtherCurrencies:true,showCounterAccounts:false})
  const isDetail=type==="vouchers"||type==="transactions"

  useEffect(()=>{let active=true;setLoadingMeta(true);fetch(`/api/reports/financial?type=${type}&meta=1`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"تعذر تحميل خيارات التقرير");if(active){setMeta(data.meta||emptyMeta);setFilters(current=>({...current,currencyIds:current.currencyIds.length?current.currencyIds:data.meta?.currencies?.[0]?.id?[Number(data.meta.currencies[0].id)]:[]}))}}).catch(reason=>active&&setError(reason instanceof Error?reason.message:"تعذر تحميل خيارات التقرير")).finally(()=>active&&setLoadingMeta(false));return()=>{active=false}},[type])

  const run=async()=>{if(filters.fromDate>filters.toDate){setError("تاريخ البداية يجب أن يسبق تاريخ النهاية");return}setLoading(true);setError("");try{const p=new URLSearchParams({type,from_date:filters.fromDate,to_date:filters.toDate,status:filters.status,level:filters.level});if(filters.accountIds.length)p.set("account_ids",filters.accountIds.join(","));if(filters.currencyIds[0])p.set("report_currency_id",String(filters.currencyIds[0]));if(!filters.showOtherCurrencies&&filters.currencyIds.length)p.set("currency_ids",filters.currencyIds.join(","));if(filters.branchIds.length)p.set("branch_ids",filters.branchIds.join(","));if(filters.salesmanIds.length)p.set("salesman_ids",filters.salesmanIds.join(","));if(filters.voucherTypes.length)p.set("voucher_types",filters.voucherTypes.join(","));if(isDetail&&filters.shiftGuid)p.set("shift_guid",filters.shiftGuid);if(filters.showCounterAccounts)p.set("show_counter_accounts","1");if(filters.evaluateInventory&&(type==="balance-sheet"||type==="income-statement")){p.set("evaluate_inventory","1");p.set("valuation_method",filters.valuationMethod)};const response=await fetch(`/api/reports/financial?${p}`),data=await response.json();if(!response.ok)throw new Error(data.error||"تعذر تحميل التقرير");setRows(data.rows||[]);setSummary(data.summary||{});if(data.meta)setMeta(data.meta)}catch(reason){setError(reason instanceof Error?reason.message:"تعذر تحميل التقرير")}finally{setLoading(false)}}
  const reset=()=>{setFilters({accountIds:[],currencyIds:meta.currencies[0]?.id?[Number(meta.currencies[0].id)]:[],branchIds:[],salesmanIds:[],voucherTypes:[],shiftGuid:"",fromDate:firstDate(),toDate:currentDate(),status:"all",level:"1",evaluateInventory:false,valuationMethod:"average",showOtherCurrencies:true,showCounterAccounts:false});setRows([]);setSummary({});setSearch("");setError("")}
  const visible=useMemo(()=>rows.filter(row=>!search||Object.values(row).join(" ").toLowerCase().includes(search.toLowerCase())),[rows,search])
  const n=(value:any)=>Number(value||0)
  const stats=type==="vouchers"?[["عدد السندات",summary.count||0,FileText],["إجمالي القيم",summary.total||0,FileBarChart],["إجمالي المدين",summary.debit||0,ArrowDownLeft],["إجمالي الدائن",summary.credit||0,ArrowUpRight]]:
    type==="balance-sheet"?[["إجمالي الأصول",summary.assets||0,Landmark],["إجمالي الالتزامات",summary.liabilities||0,Scale],["الفرق",n(summary.assets)-n(summary.liabilities),Activity],["عدد الحسابات",summary.count||0,BookOpen]]:
    type==="income-statement"?[["الإيرادات",summary.income||0,ArrowUpRight],["المصروفات",summary.expenses||0,ArrowDownLeft],["صافي النتيجة",n(summary.income)-n(summary.expenses),BarChart3],["عدد الحسابات",summary.count||0,BookOpen]]:
    type==="trial-balance"?[["الرصيد السابق",summary.opening||0,BookOpen],["حركة المدين",summary.debit||0,ArrowDownLeft],["حركة الدائن",summary.credit||0,ArrowUpRight],["الرصيد النهائي",summary.balance||0,Scale]]:
    [["عدد الحركات",summary.count||0,Activity],["إجمالي المدين",summary.debit||0,ArrowDownLeft],["إجمالي الدائن",summary.credit||0,ArrowUpRight],["الفرق",summary.balance||0,Scale]]
  const exportTrialCsv=()=>{if(!visible.length)return;const headers=['##','رقم الحساب','اسم الحساب','رصيد سابق مدين','رصيد سابق دائن','مجموع الحركات مدين','مجموع الحركات دائن','مجموع الحركات','الرصيد الحالي مدين','الرصيد الحالي دائن'];const quote=(value:unknown)=>'"'+String(value??'').replaceAll('"','""')+'"';const lines=visible.map((row,index)=>{const opening=nv(row.opening_balance),debit=nv(row.debit),credit=nv(row.credit),balance=nv(row.balance);return [index+1,row.account_code,row.account_name,Math.max(opening,0),Math.max(-opening,0),debit,credit,debit-credit,Math.max(balance,0),Math.max(-balance,0)].map(quote).join(',')});const blob=new Blob(['\ufeff'+[headers.map(quote).join(','),...lines].join('\n')],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${config.title}-${currentDate()}.csv`;link.click();URL.revokeObjectURL(link.href)}
  const exportCsv=()=>{if(!visible.length)return;const keys=type==="vouchers"?["vch_date","vch_code","voucher_type_name","accounts","amount","debit","credit","currency_code","branch_name","salesman_name","note"]:type==="transactions"?["vch_date","vch_code","voucher_type_name","account_code","account_name","debit","credit","currency_code","branch_name","counter_accounts","note"]:["account_code","account_name","statement_item","opening_balance","debit","credit","balance"];const labels:Record<string,string>={vch_date:"التاريخ",vch_code:"رقم السند",voucher_type_name:"نوع السند",accounts:"الحسابات",amount:"المبلغ",debit:"مدين",credit:"دائن",currency_code:"العملة",branch_name:"الفرع",salesman_name:"المندوب",note:"الملاحظة",account_code:"رقم الحساب",account_name:"اسم الحساب",counter_accounts:"الحساب المقابل",statement_item:"بند القائمة",opening_balance:"الرصيد السابق",balance:"الرصيد"};const quote=(value:any)=>`"${String(value??"").replace(/"/g,'""')}"`;const csv=[keys.map(key=>labels[key]).join(","),...visible.map(row=>keys.map(key=>quote(key==="vch_date"?String(row[key]||"").slice(0,10):row[key])).join(","))].join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${config.title}-${currentDate()}.csv`;link.click();URL.revokeObjectURL(link.href)}

  return <main dir="rtl" style={{ fontSize: "clamp(12px, var(--font-size-custom, 14px), 18px)" }} className="accounting-report min-h-full w-full bg-[linear-gradient(145deg,rgba(248,250,252,.96),rgba(240,253,250,.75),rgba(238,242,255,.75))] p-3 dark:bg-[linear-gradient(145deg,#020617,#071a1a,#0f172a)] md:h-full md:min-h-0 md:overflow-hidden sm:p-5 lg:p-7 print:h-auto print:overflow-visible print:bg-white print:p-0"><div className="w-full space-y-5 md:flex md:h-full md:min-h-0 md:flex-col md:gap-5 md:space-y-0">
    <header className={`relative shrink-0 overflow-hidden rounded-[30px] border border-white/20 bg-gradient-to-l ${config.accent} p-6 text-white shadow-2xl shadow-cyan-900/20 sm:p-8`}><div className="absolute -left-16 -top-20 h-56 w-56 rounded-full bg-white/20 blur-3xl"/><div className="absolute -bottom-24 right-1/3 h-52 w-52 rounded-full bg-indigo-950/15 blur-3xl"/><div className="relative flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/15 shadow-lg ring-1 ring-white/25 backdrop-blur"><Icon className="h-7 w-7"/></span><div><Badge className="mb-2 border-white/20 bg-white/15 text-white">التقارير المحاسبية</Badge><h1 className="text-2xl font-black sm:text-3xl">{config.title}</h1><p className="mt-1 text-sm text-white/80">{config.description}</p></div></div><div className="flex gap-2 print:hidden"><Button variant="secondary" onClick={type==="trial-balance"?exportTrialCsv:exportCsv} disabled={!visible.length}><Download className="ml-2 h-4 w-4"/>تصدير</Button><Button className="bg-white text-sky-800 hover:bg-sky-50" onClick={()=>window.print()} disabled={!visible.length}><Printer className="ml-2 h-4 w-4"/>طباعة</Button></div></div></header>

    <ReportFilters><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-6">
      <ReportMultiChoice label="الحسابات" options={meta.accounts} selected={filters.accountIds} onChange={accountIds=>setFilters({...filters,accountIds})} placeholder={loadingMeta?"جاري التحميل...":"جميع الحسابات"}/>
      <ReportMultiChoice label="أنواع السندات" options={meta.voucher_types} selected={filters.voucherTypes} onChange={voucherTypes=>setFilters({...filters,voucherTypes})} placeholder="جميع أنواع السندات"/>
      {isDetail&&<ReportShiftFilter shifts={meta.shifts} value={filters.shiftGuid} onChange={shiftGuid=>setFilters(current=>({...current,shiftGuid}))}/>}
      <div className="space-y-2"><Label>من تاريخ</Label><div className="relative"><CalendarRange className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-indigo-600"/><Input type="date" className="rounded-xl pr-9" value={filters.fromDate} onChange={event=>setFilters({...filters,fromDate:event.target.value})}/></div></div>
      <div className="space-y-2"><Label>إلى تاريخ</Label><Input type="date" className="rounded-xl" value={filters.toDate} onChange={event=>setFilters({...filters,toDate:event.target.value})}/></div>
      <ReportCurrencyFilter currencies={meta.currencies} value={filters.currencyIds[0]} onChange={id=>setFilters({...filters,currencyIds:[id]})}/>
      <ReportMultiChoice label="الفروع" options={meta.branches} selected={filters.branchIds} onChange={branchIds=>setFilters({...filters,branchIds})} placeholder="جميع الفروع المتاحة"/>
      <ReportMultiChoice label="المندوبون" options={meta.salesmen} selected={filters.salesmanIds} onChange={salesmanIds=>setFilters({...filters,salesmanIds})} placeholder="جميع المندوبين"/>
      <div className="space-y-2"><Label>حالة السند</Label><Select value={filters.status} onValueChange={status=>setFilters({...filters,status})}><SelectTrigger className="rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="posted">مرحّل فقط</SelectItem><SelectItem value="draft">مسودة فقط</SelectItem><SelectItem value="all">الكل</SelectItem></SelectContent></Select></div>
      <OtherCurrenciesFilter checked={filters.showOtherCurrencies} onCheckedChange={showOtherCurrencies=>setFilters({...filters,showOtherCurrencies})}/>
      {!isDetail&&<div className="space-y-2"><Label>مستوى الحساب</Label><Select value={filters.level} onValueChange={level=>setFilters({...filters,level})}><SelectTrigger className="rounded-xl"><SelectValue/></SelectTrigger><SelectContent>{[1,2,3,4,5,6,7,8].map(level=><SelectItem key={level} value={String(level)}>حتى المستوى {level}</SelectItem>)}</SelectContent></Select></div>}
    </div>{(type==="balance-sheet"||type==="income-statement")&&<div className="mt-4 flex flex-wrap gap-3 rounded-2xl bg-slate-50 p-3 dark:bg-slate-900"><label className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm shadow-sm dark:bg-slate-950">تقييم المخزون<Switch checked={filters.evaluateInventory} onCheckedChange={evaluateInventory=>setFilters({...filters,evaluateInventory})}/></label>{filters.evaluateInventory&&<div className="min-w-52"><Select value={filters.valuationMethod} onValueChange={valuationMethod=>setFilters({...filters,valuationMethod})}><SelectTrigger className="rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="average">متوسط تكلفة الوارد</SelectItem><SelectItem value="last">آخر تكلفة وارد</SelectItem></SelectContent></Select></div>}</div>}{type==="transactions"&&<div className="mt-4 grid gap-2 rounded-2xl bg-slate-50 p-3 dark:bg-slate-900 sm:grid-cols-2 lg:grid-cols-3">{type==="transactions"&&<label className="flex items-center justify-between rounded-xl bg-white px-3 py-2 text-sm shadow-sm dark:bg-slate-950">إظهار الحساب المقابل<Switch checked={filters.showCounterAccounts} onCheckedChange={showCounterAccounts=>setFilters({...filters,showCounterAccounts})}/></label>}</div>}
    <div className="mt-4 flex justify-end gap-2"><Button variant="outline" onClick={reset}><RefreshCcw className="ml-2 h-4 w-4"/>مسح</Button><Button data-report-apply onClick={run} disabled={loading||loadingMeta} className={`min-w-36 rounded-xl bg-gradient-to-l ${config.accent} text-white shadow-lg`}>{loading?<Loader2 className="ml-2 h-4 w-4 animate-spin"/>:<Search className="ml-2 h-4 w-4"/>}عرض التقرير</Button></div></ReportFilters>
    {error&&<p className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}

    <section dir="rtl" className="grid shrink-0 grid-cols-1 gap-[10px] sm:grid-cols-2 lg:grid-cols-4">{stats.map(([label,value],index)=><ReportSummaryCard key={String(label)} label={String(label)} highlight={index===2}>{type==="vouchers"&&index===0?Number(value).toLocaleString("ar"):formatter.format(Number(value))}</ReportSummaryCard>)}</section>

    <section className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-[26px] border bg-background shadow-xl"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4 print:hidden"><div><h2 className="font-bold">نتائج {config.title}</h2><p className="text-xs text-muted-foreground">{visible.length.toLocaleString("ar")} سجل</p></div><div className="relative w-full sm:w-80"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={event=>setSearch(event.target.value)} placeholder="بحث داخل النتائج..." className="rounded-xl bg-muted/40 pr-9"/></div></div><div className="min-h-0 flex-1 overflow-auto overscroll-contain print:max-h-none print:overflow-visible">
      {type==="vouchers"?<VoucherTable rows={visible}/>:type==="transactions"?<TransactionTable rows={visible} counter={filters.showCounterAccounts}/>:type==="income-statement"?<IncomeStatementTable rows={visible}/>:type==="balance-sheet"?<BalanceSheetTable rows={visible}/>:<BalanceTable rows={visible} type={type}/>} {!loading&&!visible.length&&<div className="py-16 text-center"><FileBarChart className="mx-auto mb-3 h-11 w-11 text-slate-300"/><p className="font-semibold">لا توجد نتائج لعرضها</p><p className="mt-1 text-xs text-muted-foreground">اختر الفلاتر ثم اضغط عرض التقرير</p></div>}
    </div></section>
  </div></main>
}

const Th=({children}:{children:any})=><th className="whitespace-nowrap px-3 py-3 text-right text-xs font-semibold">{children}</th>
const Td=({children,className="",dir}:{children?:any;className?:string;dir?:"ltr"|"rtl"|"auto"})=><td dir={dir} className={`px-3 py-3 ${className}`}>{children}</td>
function VoucherTable({rows}:{rows:Row[]}){if(!rows.length)return null;return <table className="w-full min-w-[1200px] text-sm"><thead className="sticky top-0 bg-gradient-to-l from-cyan-700 via-sky-700 to-indigo-700 text-white print:static"><tr>{["التاريخ","رقم السند","النوع","الحسابات","المبلغ","مدين","دائن","العملة","الفرع","المندوب","الحالة","الملاحظة"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={`border-b hover:bg-cyan-50/70 dark:hover:bg-cyan-950/20 ${i%2?"bg-slate-50/60 dark:bg-slate-900/30":""}`}><Td>{String(r.vch_date||"").slice(0,10)}</Td><Td className="font-mono font-bold text-cyan-700">{<VoucherLink id={r.voucher_id || r.id} type={r.vch_type} code={r.vch_code}/>}</Td><Td><Badge>{r.voucher_type_name}</Badge></Td><Td className="max-w-80 whitespace-normal text-xs">{r.accounts}</Td><Td className="font-bold" dir="ltr">{formatter.format(nv(r.amount))}</Td><Td className="text-emerald-700" dir="ltr">{formatter.format(nv(r.debit))}</Td><Td className="text-rose-700" dir="ltr">{formatter.format(nv(r.credit))}</Td><Td>{r.currency_code||r.currency_name||"—"}</Td><Td>{r.branch_name||"—"}</Td><Td>{r.salesman_name||"—"}</Td><Td><Badge variant={r.voucher_status===2?"default":"secondary"}>{r.voucher_status===2?"مرحّل":"مسودة"}</Badge></Td><Td className="max-w-60 whitespace-normal text-muted-foreground">{r.note||"—"}</Td></tr>)}</tbody></table>}
function TransactionTable({rows,counter}:{rows:Row[];counter:boolean}){if(!rows.length)return null;return <table className="w-full min-w-[1150px] text-sm"><thead className="sticky top-0 bg-gradient-to-l from-teal-700 via-cyan-700 to-sky-700 text-white print:static"><tr>{["التاريخ","السند","الحركة","رقم الحساب","اسم الحساب","مدين","دائن","العملة","الفرع",...(counter?["الحساب المقابل"]:[]),"الملاحظة"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={`border-b hover:bg-teal-50/70 dark:hover:bg-teal-950/20 ${i%2?"bg-slate-50/60 dark:bg-slate-900/30":""}`}><Td>{String(r.vch_date||"").slice(0,10)}</Td><Td className="font-mono font-bold text-teal-700">{<VoucherLink id={r.voucher_id || r.id} type={r.vch_type} code={r.vch_code}/>}</Td><Td>{r.voucher_type_name}</Td><Td>{r.account_code}</Td><Td className="font-semibold">{r.account_name}</Td><Td className="font-bold text-emerald-700" dir="ltr">{r.debit?formatter.format(nv(r.debit)):"—"}</Td><Td className="font-bold text-rose-700" dir="ltr">{r.credit?formatter.format(nv(r.credit)):"—"}</Td><Td>{r.currency_code||r.currency_name||"—"}</Td><Td>{r.branch_name||"—"}</Td>{counter&&<Td className="max-w-72 whitespace-normal text-xs">{r.counter_accounts||"—"}</Td>}<Td className="max-w-64 whitespace-normal text-muted-foreground">{r.note||"—"}</Td></tr>)}</tbody></table>}
function BalanceTable({rows,type}:{rows:Row[];type:FinancialReportType}){if(!rows.length)return null;if(type==="trial-balance"){
  const amount=(value:number)=>Math.abs(value)>0.00001?formatter.format(value):"—"
  const values=(r:Row)=>[Math.max(nv(r.opening_balance),0),Math.max(-nv(r.opening_balance),0),nv(r.debit),nv(r.credit),nv(r.debit)-nv(r.credit),Math.max(nv(r.balance),0),Math.max(-nv(r.balance),0)]
  const totals:number[]=rows.reduce<number[]>((sum,r)=>values(r).map((value:number,i:number)=>value+sum[i]),[0,0,0,0,0,0,0])
  return <table className="w-full min-w-[1300px] border-collapse text-sm"><thead className="sticky top-0 bg-gradient-to-l from-indigo-700 via-blue-700 to-sky-700 text-white print:static"><tr>{["##","رقم الحساب","اسم الحساب","رصيد سابق مدين","رصيد سابق دائن","مجموع الحركات مدين","مجموع الحركات دائن","مجموع الحركات","الرصيد الحالي مدين","الرصيد الحالي دائن"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={`border-b hover:bg-indigo-50/70 dark:hover:bg-indigo-950/20 ${i%2?"bg-slate-50/60 dark:bg-slate-900/30":""}`}><Td>{i+1}</Td><Td className="font-mono font-bold text-indigo-700">{r.account_code}</Td><Td className="min-w-52 font-semibold">{r.account_name}</Td>{values(r).map((value,j)=><Td key={j} dir="ltr" className="tabular-nums">{amount(value)}</Td>)}</tr>)}</tbody><tfoot className="sticky bottom-0 bg-slate-100 font-bold dark:bg-slate-900 print:static"><tr><Td>{rows.length}</Td><Td>الإجمالي</Td><Td/>{totals.map((value,i)=><Td key={i} dir="ltr" className="tabular-nums">{amount(value)}</Td>)}</tr></tfoot></table>
}return <table className="w-full min-w-[900px] text-sm"><thead className="sticky top-0 bg-gradient-to-l from-indigo-700 via-blue-700 to-sky-700 text-white print:static"><tr>{["رقم الحساب","اسم الحساب","بند القائمة","المستوى","الرصيد السابق","مدين الفترة","دائن الفترة","الرصيد النهائي"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={`border-b hover:bg-indigo-50/70 dark:hover:bg-indigo-950/20 ${i%2?"bg-slate-50/60 dark:bg-slate-900/30":""}`}><Td className="font-mono font-bold text-indigo-700">{r.account_code}</Td><Td className="font-semibold">{r.account_name}</Td><Td><Badge variant="secondary">{r.statement_item}</Badge></Td><Td>{r.level_no}</Td><Td dir="ltr">{formatter.format(nv(r.opening_balance))}</Td><Td className="text-emerald-700" dir="ltr">{formatter.format(nv(r.debit))}</Td><Td className="text-rose-700" dir="ltr">{formatter.format(nv(r.credit))}</Td><Td className={`font-black ${nv(r.balance)<0?"text-rose-700":""}`} dir="ltr">{formatter.format(nv(r.balance))}</Td></tr>)}</tbody></table>}
const nv=(value:any)=>Number(value||0)

export const VouchersReport=()=> <FinancialReport type="vouchers"/>
export const TransactionsReport=()=> <FinancialReport type="transactions"/>
export const TrialBalanceReport=()=> <FinancialReport type="trial-balance"/>
export const BalanceSheetReport=()=> <FinancialReport type="balance-sheet"/>
export const IncomeStatementReport=()=> <FinancialReport type="income-statement"/>
