"use client"

import { useEffect, useMemo, useState } from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { ReportMultiChoice, type ReportOption } from "@/components/reports/account-statement-report"
import { Activity, ArrowDownLeft, ArrowUpRight, BarChart3, BookOpen, CalendarRange, Download, FileBarChart, FileText, Landmark, Loader2, Printer, RefreshCcw, Search, Scale, SlidersHorizontal } from "lucide-react"

export type FinancialReportType = "vouchers" | "transactions" | "trial-balance" | "balance-sheet" | "income-statement"
type Meta = { accounts: ReportOption[]; currencies: ReportOption[]; branches: ReportOption[]; salesmen: ReportOption[]; voucher_types: ReportOption[] }
type Row = Record<string, any>
type Summary = Record<string, number>

const currentDate = () => new Date().toISOString().slice(0,10)
const firstDate = () => `${currentDate().slice(0,4)}-01-01`
const formatter = new Intl.NumberFormat("ar",{minimumFractionDigits:2,maximumFractionDigits:2})
const emptyMeta:Meta={accounts:[],currencies:[],branches:[],salesmen:[],voucher_types:[]}
const configs:Record<FinancialReportType,{title:string;description:string;icon:any;accent:string}>={
  vouchers:{title:"تقرير السندات",description:"مراجعة السندات وقيمها وحالة ترحيلها والحسابات المرتبطة بها",icon:FileText,accent:"from-cyan-500 to-blue-600"},
  transactions:{title:"تقرير الحركات",description:"تفاصيل جميع الأسطر المحاسبية مع الحساب المقابل والعملة والفرع",icon:Activity,accent:"from-teal-500 to-emerald-600"},
  "trial-balance":{title:"ميزان المراجعة",description:"الأرصدة الافتتاحية وحركة المدين والدائن والرصيد النهائي لكل حساب",icon:Scale,accent:"from-indigo-500 to-violet-600"},
  "balance-sheet":{title:"الميزانية العمومية",description:"عرض الأصول والالتزامات بحسب البنود المعرفة في شجرة الحسابات",icon:Landmark,accent:"from-sky-500 to-indigo-600"},
  "income-statement":{title:"قائمة الدخل",description:"تحليل الإيرادات والمصروفات وصافي نتيجة الفترة المالية",icon:BarChart3,accent:"from-fuchsia-500 to-rose-600"},
}

export function FinancialReport({type}:{type:FinancialReportType}) {
  const config=configs[type], Icon=config.icon
  const [meta,setMeta]=useState<Meta>(emptyMeta),[rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState<Summary>({})
  const [loadingMeta,setLoadingMeta]=useState(true),[loading,setLoading]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState("")
  const [filters,setFilters]=useState({accountIds:[] as number[],currencyIds:[] as number[],branchIds:[] as number[],salesmanIds:[] as number[],voucherTypes:[] as number[],fromDate:firstDate(),toDate:currentDate(),status:"posted",level:"0",includeZero:false,baseCurrency:false,showCounterAccounts:false})
  const isDetail=type==="vouchers"||type==="transactions"

  useEffect(()=>{let active=true;setLoadingMeta(true);fetch(`/api/reports/financial?type=${type}&meta=1`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"تعذر تحميل خيارات التقرير");if(active)setMeta(data.meta||emptyMeta)}).catch(reason=>active&&setError(reason instanceof Error?reason.message:"تعذر تحميل خيارات التقرير")).finally(()=>active&&setLoadingMeta(false));return()=>{active=false}},[type])

  const run=async()=>{if(filters.fromDate>filters.toDate){setError("تاريخ البداية يجب أن يسبق تاريخ النهاية");return}setLoading(true);setError("");try{const p=new URLSearchParams({type,from_date:filters.fromDate,to_date:filters.toDate,status:filters.status,level:filters.level});if(filters.accountIds.length)p.set("account_ids",filters.accountIds.join(","));if(filters.currencyIds.length)p.set("currency_ids",filters.currencyIds.join(","));if(filters.branchIds.length)p.set("branch_ids",filters.branchIds.join(","));if(filters.salesmanIds.length)p.set("salesman_ids",filters.salesmanIds.join(","));if(filters.voucherTypes.length)p.set("voucher_types",filters.voucherTypes.join(","));if(filters.includeZero)p.set("include_zero","1");if(filters.baseCurrency)p.set("base_currency","1");if(filters.showCounterAccounts)p.set("show_counter_accounts","1");const response=await fetch(`/api/reports/financial?${p}`),data=await response.json();if(!response.ok)throw new Error(data.error||"تعذر تحميل التقرير");setRows(data.rows||[]);setSummary(data.summary||{});if(data.meta)setMeta(data.meta)}catch(reason){setError(reason instanceof Error?reason.message:"تعذر تحميل التقرير")}finally{setLoading(false)}}
  const reset=()=>{setFilters({accountIds:[],currencyIds:[],branchIds:[],salesmanIds:[],voucherTypes:[],fromDate:firstDate(),toDate:currentDate(),status:"posted",level:"0",includeZero:false,baseCurrency:false,showCounterAccounts:false});setRows([]);setSummary({});setSearch("");setError("")}
  const visible=useMemo(()=>rows.filter(row=>!search||Object.values(row).join(" ").toLowerCase().includes(search.toLowerCase())),[rows,search])
  const n=(value:any)=>Number(value||0)
  const stats=type==="vouchers"?[["عدد السندات",summary.count||0,FileText],["إجمالي القيم",summary.total||0,FileBarChart],["إجمالي المدين",summary.debit||0,ArrowDownLeft],["إجمالي الدائن",summary.credit||0,ArrowUpRight]]:
    type==="balance-sheet"?[["إجمالي الأصول",summary.assets||0,Landmark],["إجمالي الالتزامات",summary.liabilities||0,Scale],["الفرق",n(summary.assets)-n(summary.liabilities),Activity],["عدد الحسابات",summary.count||0,BookOpen]]:
    type==="income-statement"?[["الإيرادات",summary.income||0,ArrowUpRight],["المصروفات",summary.expenses||0,ArrowDownLeft],["صافي النتيجة",n(summary.income)-n(summary.expenses),BarChart3],["عدد الحسابات",summary.count||0,BookOpen]]:
    type==="trial-balance"?[["الرصيد السابق",summary.opening||0,BookOpen],["حركة المدين",summary.debit||0,ArrowDownLeft],["حركة الدائن",summary.credit||0,ArrowUpRight],["الرصيد النهائي",summary.balance||0,Scale]]:
    [["عدد الحركات",summary.count||0,Activity],["إجمالي المدين",summary.debit||0,ArrowDownLeft],["إجمالي الدائن",summary.credit||0,ArrowUpRight],["الفرق",summary.balance||0,Scale]]
  const exportCsv=()=>{if(!visible.length)return;const keys=type==="vouchers"?["vch_date","vch_code","voucher_type_name","accounts","amount","debit","credit","currency_code","branch_name","salesman_name","note"]:type==="transactions"?["vch_date","vch_code","voucher_type_name","account_code","account_name","debit","credit","currency_code","branch_name","counter_accounts","note"]:["account_code","account_name","statement_item","opening_balance","debit","credit","balance"];const labels:Record<string,string>={vch_date:"التاريخ",vch_code:"رقم السند",voucher_type_name:"نوع السند",accounts:"الحسابات",amount:"المبلغ",debit:"مدين",credit:"دائن",currency_code:"العملة",branch_name:"الفرع",salesman_name:"المندوب",note:"الملاحظة",account_code:"رقم الحساب",account_name:"اسم الحساب",counter_accounts:"الحساب المقابل",statement_item:"بند القائمة",opening_balance:"الرصيد السابق",balance:"الرصيد"};const quote=(value:any)=>`"${String(value??"").replace(/"/g,'""')}"`;const csv=[keys.map(key=>labels[key]).join(","),...visible.map(row=>keys.map(key=>quote(key==="vch_date"?String(row[key]||"").slice(0,10):row[key])).join(","))].join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${config.title}-${currentDate()}.csv`;link.click();URL.revokeObjectURL(link.href)}

  return <main dir="rtl" className="min-h-full bg-[linear-gradient(145deg,rgba(248,250,252,.96),rgba(240,253,250,.75),rgba(238,242,255,.75))] p-3 dark:bg-[linear-gradient(145deg,#020617,#071a1a,#0f172a)] sm:p-5 lg:p-7 print:bg-white print:p-0"><div className="mx-auto max-w-[1750px] space-y-5">
    <header className="relative overflow-hidden rounded-[30px] border border-white/10 bg-slate-950 p-6 text-white shadow-2xl sm:p-8"><div className={`absolute inset-y-0 right-0 w-2/3 bg-gradient-to-l ${config.accent} opacity-20 blur-3xl`}/><div className="relative flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><span className={`flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br ${config.accent} shadow-lg`}><Icon className="h-7 w-7"/></span><div><Badge className="mb-2 border-white/10 bg-white/10 text-white">التقارير المحاسبية</Badge><h1 className="text-2xl font-black sm:text-3xl">{config.title}</h1><p className="mt-1 text-sm text-slate-300">{config.description}</p></div></div><div className="flex gap-2 print:hidden"><Button variant="secondary" onClick={exportCsv} disabled={!visible.length}><Download className="ml-2 h-4 w-4"/>تصدير</Button><Button className="bg-white text-slate-950 hover:bg-slate-100" onClick={()=>window.print()} disabled={!visible.length}><Printer className="ml-2 h-4 w-4"/>طباعة</Button></div></div></header>

    <section className="rounded-[26px] border border-slate-200/80 bg-white/90 p-4 shadow-xl shadow-slate-900/5 backdrop-blur dark:border-slate-800 dark:bg-slate-950/85 print:hidden"><div className="mb-4 flex items-center gap-2"><span className="rounded-xl bg-indigo-100 p-2 text-indigo-700 dark:bg-indigo-950"><SlidersHorizontal className="h-4 w-4"/></span><div><h2 className="font-bold">تصفية التقرير</h2><p className="text-xs text-muted-foreground">يمكن ترك أي اختيار فارغًا لعرض الكل</p></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-6">
      <ReportMultiChoice label="الحسابات" options={meta.accounts} selected={filters.accountIds} onChange={accountIds=>setFilters({...filters,accountIds})} placeholder={loadingMeta?"جاري التحميل...":"جميع الحسابات"}/>
      <ReportMultiChoice label="أنواع السندات" options={meta.voucher_types} selected={filters.voucherTypes} onChange={voucherTypes=>setFilters({...filters,voucherTypes})} placeholder="جميع أنواع السندات"/>
      <div className="space-y-2"><Label>من تاريخ</Label><div className="relative"><CalendarRange className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-indigo-600"/><Input type="date" className="rounded-xl pr-9" value={filters.fromDate} onChange={event=>setFilters({...filters,fromDate:event.target.value})}/></div></div>
      <div className="space-y-2"><Label>إلى تاريخ</Label><Input type="date" className="rounded-xl" value={filters.toDate} onChange={event=>setFilters({...filters,toDate:event.target.value})}/></div>
      <ReportMultiChoice label="العملات" options={meta.currencies} selected={filters.currencyIds} onChange={currencyIds=>setFilters({...filters,currencyIds})} placeholder="جميع العملات"/>
      <ReportMultiChoice label="الفروع" options={meta.branches} selected={filters.branchIds} onChange={branchIds=>setFilters({...filters,branchIds})} placeholder="جميع الفروع المتاحة"/>
      <ReportMultiChoice label="المندوبون" options={meta.salesmen} selected={filters.salesmanIds} onChange={salesmanIds=>setFilters({...filters,salesmanIds})} placeholder="جميع المندوبين"/>
      <div className="space-y-2"><Label>حالة السند</Label><Select value={filters.status} onValueChange={status=>setFilters({...filters,status})}><SelectTrigger className="rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="posted">مرحّل فقط</SelectItem><SelectItem value="draft">مسودة فقط</SelectItem><SelectItem value="all">الكل</SelectItem></SelectContent></Select></div>
      {!isDetail&&<div className="space-y-2"><Label>مستوى الحساب</Label><Select value={filters.level} onValueChange={level=>setFilters({...filters,level})}><SelectTrigger className="rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="0">جميع المستويات</SelectItem>{[1,2,3,4,5,6,7,8].map(level=><SelectItem key={level} value={String(level)}>حتى المستوى {level}</SelectItem>)}</SelectContent></Select></div>}
    </div><div className="mt-4 grid gap-2 rounded-2xl bg-slate-50 p-3 dark:bg-slate-900 sm:grid-cols-2 lg:grid-cols-3">{!isDetail&&<label className="flex items-center justify-between rounded-xl bg-white px-3 py-2 text-sm shadow-sm dark:bg-slate-950">إظهار الأرصدة الصفرية<Switch checked={filters.includeZero} onCheckedChange={includeZero=>setFilters({...filters,includeZero})}/></label>}<label className="flex items-center justify-between rounded-xl bg-white px-3 py-2 text-sm shadow-sm dark:bg-slate-950">النتائج بالعملة الأساسية<Switch checked={filters.baseCurrency} onCheckedChange={baseCurrency=>setFilters({...filters,baseCurrency})}/></label>{type==="transactions"&&<label className="flex items-center justify-between rounded-xl bg-white px-3 py-2 text-sm shadow-sm dark:bg-slate-950">إظهار الحساب المقابل<Switch checked={filters.showCounterAccounts} onCheckedChange={showCounterAccounts=>setFilters({...filters,showCounterAccounts})}/></label>}</div>
    {error&&<p className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}<div className="mt-4 flex justify-end gap-2"><Button variant="outline" onClick={reset}><RefreshCcw className="ml-2 h-4 w-4"/>مسح</Button><Button onClick={run} disabled={loading||loadingMeta} className={`min-w-36 rounded-xl bg-gradient-to-l ${config.accent} text-white shadow-lg`}>{loading?<Loader2 className="ml-2 h-4 w-4 animate-spin"/>:<Search className="ml-2 h-4 w-4"/>}عرض التقرير</Button></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,StatIcon],index)=><article key={String(label)} className="rounded-2xl border bg-white p-4 shadow-lg shadow-slate-900/5 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">{String(label)}</p><p className={`mt-1 text-2xl font-black tabular-nums ${index===2?"text-rose-600":"text-slate-900 dark:text-white"}`} dir="ltr">{type==="vouchers"&&index===0?Number(value).toLocaleString("ar"):formatter.format(Number(value))}</p></div>{typeof StatIcon==="function"&&<StatIcon className={`h-8 w-8 ${index%2?"text-indigo-500":"text-teal-500"}`}/>}</div></article>)}</section>

    <section className="overflow-hidden rounded-[26px] border bg-background shadow-xl"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4 print:hidden"><div><h2 className="font-bold">نتائج {config.title}</h2><p className="text-xs text-muted-foreground">{visible.length.toLocaleString("ar")} سجل</p></div><div className="relative w-full sm:w-80"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={event=>setSearch(event.target.value)} placeholder="بحث داخل النتائج..." className="rounded-xl bg-muted/40 pr-9"/></div></div><div className="max-h-[64vh] overflow-auto print:max-h-none print:overflow-visible">
      {type==="vouchers"?<VoucherTable rows={visible}/>:type==="transactions"?<TransactionTable rows={visible} counter={filters.showCounterAccounts}/>:<BalanceTable rows={visible} type={type}/>} {!loading&&!visible.length&&<div className="py-16 text-center"><FileBarChart className="mx-auto mb-3 h-11 w-11 text-slate-300"/><p className="font-semibold">لا توجد نتائج لعرضها</p><p className="mt-1 text-xs text-muted-foreground">اختر الفلاتر ثم اضغط عرض التقرير</p></div>}
    </div></section>
  </div></main>
}

const Th=({children}:{children:any})=><th className="whitespace-nowrap px-3 py-3 text-right text-xs font-semibold">{children}</th>
const Td=({children,className="",dir}:{children:any;className?:string;dir?:"ltr"|"rtl"|"auto"})=><td dir={dir} className={`px-3 py-3 ${className}`}>{children}</td>
function VoucherTable({rows}:{rows:Row[]}){if(!rows.length)return null;return <table className="w-full min-w-[1200px] text-sm"><thead className="sticky top-0 bg-slate-900 text-white print:static"><tr>{["التاريخ","رقم السند","النوع","الحسابات","المبلغ","مدين","دائن","العملة","الفرع","المندوب","الحالة","الملاحظة"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={`border-b hover:bg-cyan-50/70 dark:hover:bg-cyan-950/20 ${i%2?"bg-slate-50/60 dark:bg-slate-900/30":""}`}><Td>{String(r.vch_date||"").slice(0,10)}</Td><Td className="font-mono font-bold text-cyan-700">{r.vch_code}</Td><Td><Badge>{r.voucher_type_name}</Badge></Td><Td className="max-w-80 whitespace-normal text-xs">{r.accounts}</Td><Td className="font-bold" dir="ltr">{formatter.format(nv(r.amount))}</Td><Td className="text-emerald-700" dir="ltr">{formatter.format(nv(r.debit))}</Td><Td className="text-rose-700" dir="ltr">{formatter.format(nv(r.credit))}</Td><Td>{r.currency_code||r.currency_name||"—"}</Td><Td>{r.branch_name||"—"}</Td><Td>{r.salesman_name||"—"}</Td><Td><Badge variant={r.voucher_status===2?"default":"secondary"}>{r.voucher_status===2?"مرحّل":"مسودة"}</Badge></Td><Td className="max-w-60 whitespace-normal text-muted-foreground">{r.note||"—"}</Td></tr>)}</tbody></table>}
function TransactionTable({rows,counter}:{rows:Row[];counter:boolean}){if(!rows.length)return null;return <table className="w-full min-w-[1150px] text-sm"><thead className="sticky top-0 bg-slate-900 text-white print:static"><tr>{["التاريخ","السند","الحركة","رقم الحساب","اسم الحساب","مدين","دائن","العملة","الفرع",...(counter?["الحساب المقابل"]:[]),"الملاحظة"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={`border-b hover:bg-teal-50/70 dark:hover:bg-teal-950/20 ${i%2?"bg-slate-50/60 dark:bg-slate-900/30":""}`}><Td>{String(r.vch_date||"").slice(0,10)}</Td><Td className="font-mono font-bold text-teal-700">{r.vch_code}</Td><Td>{r.voucher_type_name}</Td><Td>{r.account_code}</Td><Td className="font-semibold">{r.account_name}</Td><Td className="font-bold text-emerald-700" dir="ltr">{r.debit?formatter.format(nv(r.debit)):"—"}</Td><Td className="font-bold text-rose-700" dir="ltr">{r.credit?formatter.format(nv(r.credit)):"—"}</Td><Td>{r.currency_code||r.currency_name||"—"}</Td><Td>{r.branch_name||"—"}</Td>{counter&&<Td className="max-w-72 whitespace-normal text-xs">{r.counter_accounts||"—"}</Td>}<Td className="max-w-64 whitespace-normal text-muted-foreground">{r.note||"—"}</Td></tr>)}</tbody></table>}
function BalanceTable({rows,type}:{rows:Row[];type:FinancialReportType}){if(!rows.length)return null;return <table className="w-full min-w-[900px] text-sm"><thead className="sticky top-0 bg-slate-900 text-white print:static"><tr>{["رقم الحساب","اسم الحساب",...(type!=="trial-balance"?["بند القائمة"]:[]),"المستوى","الرصيد السابق","مدين الفترة","دائن الفترة","الرصيد النهائي"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className={`border-b hover:bg-indigo-50/70 dark:hover:bg-indigo-950/20 ${i%2?"bg-slate-50/60 dark:bg-slate-900/30":""}`}><Td className="font-mono font-bold text-indigo-700">{r.account_code}</Td><Td className="font-semibold">{r.account_name}</Td>{type!=="trial-balance"&&<Td><Badge variant="secondary">{r.statement_item}</Badge></Td>}<Td>{r.level_no}</Td><Td dir="ltr">{formatter.format(nv(r.opening_balance))}</Td><Td className="text-emerald-700" dir="ltr">{formatter.format(nv(r.debit))}</Td><Td className="text-rose-700" dir="ltr">{formatter.format(nv(r.credit))}</Td><Td className={`font-black ${nv(r.balance)<0?"text-rose-700":""}`} dir="ltr">{formatter.format(nv(r.balance))}</Td></tr>)}</tbody></table>}
const nv=(value:any)=>Number(value||0)

export const VouchersReport=()=> <FinancialReport type="vouchers"/>
export const TransactionsReport=()=> <FinancialReport type="transactions"/>
export const TrialBalanceReport=()=> <FinancialReport type="trial-balance"/>
export const BalanceSheetReport=()=> <FinancialReport type="balance-sheet"/>
export const IncomeStatementReport=()=> <FinancialReport type="income-statement"/>
