"use client"

import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import type React from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { UniversalToolbar } from "@/components/ui/universal-toolbar"
import ConfirmDialogYesNo from "@/components/ui/ConfirmDialogYesNo"
import DataGridView from "@/components/common/DataGridView"
import ProgressSpinner from "@/components/ProgressSpinner/ProgressSpinner"
import { Package, Plus, Search, Snowflake, Trash2, Users } from "lucide-react"

type Form = { id:number; template_code:string; name_ar:string; name_en:string; start_date:string; end_date:string; notes:string; status:number; customer_ids:number[]; product_ids:number[] }
const empty = (): Form => ({ id:0, template_code:"", name_ar:"", name_en:"", start_date:new Date().toISOString().slice(0,10), end_date:"", notes:"", status:1, customer_ids:[], product_ids:[] })
const date = (value:any) => String(value || "").slice(0,10)

export default function UnifiedCustomerProductsTemplates({ initialTemplate, onSaved }: { initialTemplate?:any; onSaved?:()=>void } = {}) {
  const [records,setRecords] = useState<any[]>([]), [customers,setCustomers] = useState<any[]>([]), [products,setProducts] = useState<any[]>([])
  const [form,setForm] = useState<Form>(empty()), [message,setMessage] = useState(""), [saving,setSaving] = useState(false), [loading,setLoading] = useState(false)
  const [confirmDelete,setConfirmDelete] = useState(false), [confirmFreeze,setConfirmFreeze] = useState(false)
  const [customerText,setCustomerText] = useState(""), [productText,setProductText] = useState("")
  const [customerOpen,setCustomerOpen] = useState(false), [productOpen,setProductOpen] = useState(false)
  const [templateSearchOpen,setTemplateSearchOpen] = useState(false), [templateSearchText,setTemplateSearchText] = useState("")
  const [selectedCustomer,setSelectedCustomer] = useState<any>(null), [selectedProduct,setSelectedProduct] = useState<any>(null)
  const nameArRef = useRef<HTMLInputElement>(null), saveRef = useRef<()=>void>(()=>{}), deleteRef = useRef<()=>void>(()=>{})
  const focusArabicName = () => window.setTimeout(() => nameArRef.current?.focus(), 60)

  const apply = useCallback((record:any) => {
    setForm({ id:Number(record.id), template_code:record.template_code||"", name_ar:record.name_ar||"", name_en:record.name_en||"", start_date:date(record.start_date), end_date:date(record.end_date), notes:record.notes||"", status:Number(record.status||1), customer_ids:(record.customer_ids||[]).map(Number), product_ids:(record.product_ids||[]).map(Number) })
    setCustomerText(""); setProductText(""); setSelectedCustomer(null); setSelectedProduct(null); focusArabicName()
  }, [])
  const load = useCallback(async () => { setLoading(true); try { const response=await fetch("/api/customer-product-templates?lookup=1",{cache:"no-store",headers:{Accept:"application/json"}}),data=await response.json(); if(!response.ok)throw new Error(data?.error||"تعذر تحميل بيانات النماذج"); setRecords(Array.isArray(data.templates)?data.templates:[]); setCustomers(Array.isArray(data.customers)?data.customers:[]); setProducts(Array.isArray(data.products)?data.products:[]) } catch(error){setMessage(error instanceof Error?error.message:"تعذر تحميل العملاء والأصناف")} finally{setLoading(false)} },[])
  const createNew = useCallback(async () => { setLoading(true);setMessage("");try{const response=await fetch("/api/customer-product-templates?generate=1"),data=await response.json();if(!response.ok)throw new Error(data?.error||"تعذر إنشاء رقم النموذج");setForm({...empty(),template_code:data.code||""});setCustomerText("");setProductText("");setSelectedCustomer(null);setSelectedProduct(null);focusArabicName()}catch(error){setMessage(error instanceof Error?error.message:"تعذر إنشاء نموذج جديد")}finally{setLoading(false)} },[])
  useEffect(()=>{void load();if(initialTemplate)apply(initialTemplate);else void createNew()},[initialTemplate,apply,createNew,load])

  const customerMatches=useMemo(()=>{const words=customerText.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);return words.length?customers.filter(customer=>{const fullText=[customer.account_code,customer.account_name,customer.mobile1,customer.phone,customer.email].filter(Boolean).join(" ").toLocaleLowerCase();return words.every(word=>fullText.includes(word))}).slice(0,30):[]},[customerText,customers])
  const productMatches=useMemo(()=>{const words=productText.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);return words.length?products.filter(product=>{const fullText=[product.product_code,product.product_name,product.barcode,product.first_barcode,product.description].filter(Boolean).join(" ").toLocaleLowerCase();return words.every(word=>fullText.includes(word))}).slice(0,30):[]},[productText,products])
  const chosenCustomers=useMemo(()=>form.customer_ids.map(id=>customers.find(c=>Number(c.account_id??c.id)===id)).filter(Boolean),[form.customer_ids,customers])
  const chosenProducts=useMemo(()=>form.product_ids.map(id=>products.find(p=>Number(p.id)===id)).filter(Boolean),[form.product_ids,products])
  const matchingTemplates=useMemo(()=>{const q=templateSearchText.trim().toLowerCase();return records.filter(record=>!q||String(record.template_code||"").toLowerCase().includes(q)||String(record.name_ar||"").toLowerCase().includes(q)||String(record.name_en||"").toLowerCase().includes(q))},[records,templateSearchText])
  const addCustomer=()=>{const id=Number(selectedCustomer?.account_id??selectedCustomer?.id);if(!id)return setMessage("يجب اختيار حساب عميل صالح من القائمة");if(form.customer_ids.includes(id))return setMessage("العميل مضاف مسبقاً");setForm(v=>({...v,customer_ids:[...v.customer_ids,id]}));setCustomerText("");setSelectedCustomer(null);setCustomerOpen(false);setMessage("")}
  const addProduct=()=>{const id=Number(selectedProduct?.id);if(!id)return setMessage("يجب اختيار صنف صالح من القائمة");if(form.product_ids.includes(id))return setMessage("الصنف مضاف مسبقاً");setForm(v=>({...v,product_ids:[...v.product_ids,id]}));setProductText("");setSelectedProduct(null);setProductOpen(false);setMessage("")}
  const removeCustomer=useCallback((id:number)=>setForm(v=>({...v,customer_ids:v.customer_ids.filter(value=>value!==id)})),[])
  const removeProduct=useCallback((id:number)=>setForm(v=>({...v,product_ids:v.product_ids.filter(value=>value!==id)})),[])
  const customerScheme=useMemo(()=>({name:"template-customers",columns:[{header:"رقم العميل",name:"account_code",width:150,isReadOnly:true},{header:"اسم العميل",name:"account_name",width:"*",isReadOnly:true},{name:"delete",header:"إجراء",width:76,buttonBody:"button",className:"danger",align:"center",title:"حذف العميل",iconType:"delete",isReadOnly:true,onClick:(event:any,ctx:any)=>{event.stopPropagation();removeCustomer(Number(ctx.item?.account_id??ctx.item?.id))},visible:form.status!==2}]}),[form.status,removeCustomer])
  const productScheme=useMemo(()=>({name:"template-products",columns:[{header:"رقم الصنف",name:"product_code",width:150,isReadOnly:true},{header:"اسم الصنف",name:"product_name",width:"*",isReadOnly:true},{name:"delete",header:"إجراء",width:76,buttonBody:"button",className:"danger",align:"center",title:"حذف الصنف",iconType:"delete",isReadOnly:true,onClick:(event:any,ctx:any)=>{event.stopPropagation();removeProduct(Number(ctx.item?.id))},visible:form.status!==2}]}),[form.status,removeProduct])

  const save=async()=>{if(saving)return;if(!form.name_ar.trim()||!form.start_date)return setMessage("الاسم العربي وتاريخ البداية مطلوبان");if(form.end_date&&form.end_date<form.start_date)return setMessage("تاريخ النهاية لا يمكن أن يسبق تاريخ البداية");if(!form.customer_ids.length)return setMessage("يجب إضافة عميل واحد على الأقل");if(!form.product_ids.length)return setMessage("يجب إضافة صنف واحد على الأقل");setSaving(true);setMessage("");try{const response=await fetch(form.id?`/api/customer-product-templates/${form.id}`:"/api/customer-product-templates",{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),data=await response.json();if(!response.ok)throw new Error(data?.error||"تعذر الحفظ");await load();apply({...form,...data});setMessage("تم حفظ النموذج بنجاح");onSaved?.()}catch(error){setMessage(error instanceof Error?error.message:"تعذر الحفظ")}finally{setSaving(false)}}
  const remove=async()=>{setConfirmDelete(false);if(!form.id)return;setLoading(true);setMessage("");try{const response=await fetch(`/api/customer-product-templates/${form.id}`,{method:"DELETE"}),data=await response.json();if(!response.ok)throw new Error(data?.error||"تعذر الحذف");await load();await createNew();setMessage("تم حذف النموذج")}catch(error){setMessage(error instanceof Error?error.message:"تعذر الحذف")}finally{setLoading(false)}}
  const freeze=async()=>{setConfirmFreeze(false);if(!form.id)return;setLoading(true);try{const action=form.status===2?"unfreeze":"freeze",response=await fetch(`/api/customer-product-templates/${form.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})}),data=await response.json();if(!response.ok)throw new Error(data?.error||"تعذر تحديث الحالة");setForm(v=>({...v,status:Number(data.status)}));await load();setMessage(action==="freeze"?"تم تجميد النموذج":"تم فك تجميد النموذج")}catch(error){setMessage(error instanceof Error?error.message:"تعذر تحديث الحالة")}finally{setLoading(false)}}
  const nav=async(direction:string)=>{setLoading(true);try{const response=await fetch(`/api/customer-product-templates?navigation=${direction}&currentId=${form.id}`),data=await response.json();if(response.ok)apply(data);else setMessage(data?.error||"تعذر عرض النموذج")}finally{setLoading(false)}}
  saveRef.current=()=>{void save()};deleteRef.current=()=>{if(form.id)setConfirmDelete(true)}
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.key==="F3"){event.preventDefault();saveRef.current()}else if(event.key==="F8"&&form.id){event.preventDefault();deleteRef.current()}};document.addEventListener("keydown",handler,true);return()=>document.removeEventListener("keydown",handler,true)},[form.id])
  const enterAsTab=(event:React.KeyboardEvent<HTMLDivElement>)=>{if(event.key!=="Enter"||event.target instanceof HTMLTextAreaElement)return;const controls=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('input:not([disabled]),textarea:not([disabled]),button:not([disabled]),[tabindex]:not([tabindex="-1"])')).filter(element=>element.offsetParent!==null);const index=controls.indexOf(event.target as HTMLElement);if(index>=0){event.preventDefault();controls[index+1]?.focus()}}
  const index=records.findIndex(record=>Number(record.id)===form.id)

  return <div dir="rtl" className="customer-products-template-editor min-h-0 w-full max-w-full space-y-4 overflow-y-auto overflow-x-hidden pb-4 [&>*:not(:first-child)]:mx-4 sm:[&>*:not(:first-child)]:mx-6" onKeyDown={enterAsTab}>
    <UniversalToolbar currentRecord={index>=0?index+1:0} totalRecords={records.length} onNew={createNew} onSave={save} onDelete={()=>setConfirmDelete(true)} onFirst={()=>nav("first")} onPrevious={()=>nav(form.id?"previous":"last")} onNext={()=>nav(form.id?"next":"first")} onLast={()=>nav("last")} isSaving={saving} isLoading={loading} canSave={form.status!==2} canDelete={form.id>0} isFirstRecord={index===0} isLastRecord={index===records.length-1} isNewRecord={!form.id}/>
    <ProgressSpinner loading={loading||saving}/>
    <div className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="text-2xl font-bold">{form.id?"تعديل نموذج":"إضافة نموذج"}</h1><p className="text-sm text-muted-foreground">ربط عملاء محددين مع أصناف محددة ضمن فترة صلاحية.</p></div><div className="flex items-center gap-2"><Badge className={form.status===2?"bg-amber-500":"bg-emerald-600"}>{form.status===2?"مجمد":"فعال"}</Badge><Button variant="outline" disabled={!form.id||loading} onClick={()=>setConfirmFreeze(true)}><Snowflake className="ml-2 h-4 w-4"/>{form.status===2?"فك التجميد":"تجميد"}</Button></div></div>
    {message&&<div className={`rounded-md border p-3 text-sm ${message.startsWith("تم ")?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-700"}`}>{message}</div>}
    <Card><CardContent className="grid gap-4 pt-6 md:grid-cols-2 lg:grid-cols-3"><div><Label>رقم النموذج *</Label><div className="flex gap-2"><Input readOnly value={form.template_code} className="min-w-0 flex-1 bg-muted font-mono"/><Button type="button" variant="outline" size="icon" title="بحث عن نموذج" onClick={()=>{setTemplateSearchText("");setTemplateSearchOpen(true)}}><Search className="h-4 w-4"/></Button></div></div><div><Label>الاسم بالعربية *</Label><Input ref={nameArRef} disabled={form.status===2} value={form.name_ar} maxLength={200} onChange={e=>setForm({...form,name_ar:e.target.value})}/></div><div><Label>الاسم بالإنجليزية</Label><Input disabled={form.status===2} dir="ltr" value={form.name_en} maxLength={200} onChange={e=>setForm({...form,name_en:e.target.value})}/></div><div><Label>تاريخ البداية *</Label><Input disabled={form.status===2} type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></div><div><Label>تاريخ النهاية</Label><Input disabled={form.status===2} type="date" min={form.start_date} value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></div><div><Label>ملاحظات</Label><Textarea disabled={form.status===2} rows={1} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-2">
      <PickerCard title="العملاء" icon={<Users className="h-5 w-5"/>} count={form.customer_ids.length} text={customerText} setText={value=>{setCustomerText(value);setSelectedCustomer(null);setCustomerOpen(true)}} open={customerOpen} setOpen={setCustomerOpen} matches={customerMatches} select={customer=>{setSelectedCustomer(customer);setCustomerText(`${customer.account_code} - ${customer.account_name}`);setCustomerOpen(false)}} codeKey="account_code" nameKey="account_name" add={addCustomer} clear={()=>setForm(v=>({...v,customer_ids:[]}))} clearLabel="تفريغ الزبائن" disabled={form.status===2} scheme={customerScheme} rows={chosenCustomers}/>
      <PickerCard title="الأصناف" icon={<Package className="h-5 w-5"/>} count={form.product_ids.length} text={productText} setText={value=>{setProductText(value);setSelectedProduct(null);setProductOpen(true)}} open={productOpen} setOpen={setProductOpen} matches={productMatches} select={product=>{setSelectedProduct(product);setProductText(`${product.product_code} - ${product.product_name}`);setProductOpen(false)}} codeKey="product_code" nameKey="product_name" add={addProduct} clear={()=>setForm(v=>({...v,product_ids:[]}))} clearLabel="تفريغ الأصناف" disabled={form.status===2} scheme={productScheme} rows={chosenProducts}/>
    </div>
    <ConfirmDialogYesNo visible={confirmDelete} message="هل تريد حذف هذا النموذج؟" onConfirm={remove} onCancel={()=>setConfirmDelete(false)}/><ConfirmDialogYesNo visible={confirmFreeze} message={form.status===2?"هل تريد فك تجميد النموذج؟":"هل تريد تجميد النموذج؟"} onConfirm={freeze} onCancel={()=>setConfirmFreeze(false)}/>
    <Dialog open={templateSearchOpen} onOpenChange={setTemplateSearchOpen}><DialogContent className="max-h-[80vh] max-w-2xl overflow-hidden" dir="rtl"><DialogHeader><DialogTitle>بحث عن نموذج</DialogTitle></DialogHeader><Input autoFocus value={templateSearchText} onChange={event=>setTemplateSearchText(event.target.value)} placeholder="ابحث برقم النموذج أو الاسم..."/><div className="max-h-[55vh] overflow-y-auto rounded-md border">{matchingTemplates.map(record=><button type="button" key={record.id} className="grid w-full grid-cols-[140px_1fr] gap-3 border-b px-4 py-3 text-right hover:bg-muted" onClick={()=>{apply(record);setTemplateSearchOpen(false)}}><span className="font-mono">{record.template_code}</span><span>{record.name_ar}</span></button>)}{!matchingTemplates.length&&<div className="p-8 text-center text-muted-foreground">لا توجد نتائج</div>}</div></DialogContent></Dialog>
  </div>
}

function PickerCard(props:{title:string;icon:React.ReactNode;count:number;text:string;setText:(value:string)=>void;open:boolean;setOpen:(value:boolean)=>void;matches:any[];select:(row:any)=>void;codeKey:string;nameKey:string;add:()=>void;clear:()=>void;clearLabel:string;disabled:boolean;scheme:any;rows:any[]}){
  return <Card className="min-w-0"><CardContent className="space-y-3 pt-5"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 font-bold">{props.icon}{props.title}</h3><Badge variant="secondary">{props.count}</Badge></div><div className="flex gap-2"><div className="relative flex-1"><Input disabled={props.disabled} value={props.text} onFocus={()=>props.setOpen(true)} onBlur={()=>window.setTimeout(()=>props.setOpen(false),150)} onChange={e=>props.setText(e.target.value)} placeholder={`اكتب كلمات من اسم أو رقم ${props.title==="العملاء"?"العميل":"الصنف"}...`}/>{props.open&&props.text&&<div className="absolute z-50 mt-1 max-h-56 w-full overflow-auto rounded-md border bg-background shadow-xl">{props.matches.map(row=><button type="button" key={row.id??row.account_id} className="flex w-full justify-between border-b px-3 py-2 text-right hover:bg-muted" onMouseDown={e=>e.preventDefault()} onClick={()=>props.select(row)}><span>{row[props.nameKey]}</span><span className="text-xs text-muted-foreground">{row[props.codeKey]}</span></button>)}{!props.matches.length&&<div className="p-3 text-center text-sm text-muted-foreground">لا توجد نتائج</div>}</div>}</div><Button type="button" disabled={props.disabled} onClick={props.add}><Plus className="ml-1 h-4 w-4"/>إضافة</Button></div><div className="h-56 min-w-0 overflow-hidden rounded-md border"><DataGridView containerStyle={{height:"100%",minHeight:0,width:"100%",overflow:"hidden"}} style={{height:"100%",minHeight:0,width:"100%",overflowX:"hidden"}} scheme={props.scheme} dataSource={props.rows} defaultRowHeight={42} dontConvertToCards={true}/></div><Button type="button" variant="destructive" disabled={props.disabled||!props.count} onClick={props.clear}><Trash2 className="ml-2 h-4 w-4"/>{props.clearLabel}</Button></CardContent></Card>
}
