"use client"

import {useCallback,useEffect,useMemo,useRef,useState} from "react"
import {ArrowDownToLine,ArrowUpFromLine,CalendarDays,Check,CheckCheck,FileCheck2,Landmark,Loader2,RefreshCcw,Search,Send,ShieldCheck,SquareStack,UsersRound,X} from "lucide-react"
import {Button} from "@/components/ui/button"
import {Input} from "@/components/ui/input"
import {Label} from "@/components/ui/label"
import Messages from "@/components/common/Messages"
import {cn} from "@/lib/utils"

type Mode="deposit"|"endorse"|"clear_outgoing"
type Cheque={id:number;cheq_num:string;amount:number;currency_id?:number;currency_code?:string;due_date?:string;status_name?:string;bank_name?:string;branch_name?:string;voucher_branch_id?:number;bank_account_name?:string;bank_account?:string;customer_name?:string;cheq_owner_name?:string;vch_code?:string;allowed_operations?:{code:string}[]}
type Option={id:number;code?:string;name?:string;currency_id?:number;currency_name?:string;currency_code?:string;bank_name?:string;branch_name?:string}
type Meta={currencies:Option[];banks:Option[];bank_accounts:Option[];accounts:Option[]}
const emptyMeta:Meta={currencies:[],banks:[],bank_accounts:[],accounts:[]}
const today=()=>new Date().toISOString().slice(0,10)
const money=new Intl.NumberFormat("ar",{minimumFractionDigits:2,maximumFractionDigits:2})
const config:Record<Mode,{title:string;description:string;operation:string;type:number;icon:any;gradient:string;targetLabel?:string}>={
 deposit:{title:"إيداع الشيكات الواردة",description:"حدد عدة شيكات مستحقة وأودعها بحساب البنك في عملية واحدة.",operation:"deposit",type:1,icon:ArrowDownToLine,gradient:"from-emerald-700 via-teal-700 to-cyan-800",targetLabel:"حساب البنك"},
 endorse:{title:"تجيير الشيكات",description:"اختر الشيكات الواردة وحساب المستفيد وأنشئ سند قيد مجمع.",operation:"endorse",type:1,icon:Send,gradient:"from-violet-700 via-indigo-700 to-blue-800",targetLabel:"حساب المستفيد"},
 clear_outgoing:{title:"إخراج الشيكات الصادرة",description:"رحّل عدة شيكات صادرة مستحقة من حساباتها البنكية معًا.",operation:"clear_outgoing",type:2,icon:ArrowUpFromLine,gradient:"from-rose-700 via-orange-700 to-amber-700"},
}

function BulkChequeOperation({mode}:{mode:Mode}){
 const view=config[mode],Icon=view.icon,messagesRef=useRef<any>(null)
 const [rows,setRows]=useState<Cheque[]>([]),[meta,setMeta]=useState<Meta>(emptyMeta),[selected,setSelected]=useState<Set<number>>(new Set()),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false)
 const [q,setQ]=useState(""),[fromDue,setFromDue]=useState(""),[toDue,setToDue]=useState(""),[currencyId,setCurrencyId]=useState("all"),[bankId,setBankId]=useState("all"),[operationDate,setOperationDate]=useState(today()),[targetId,setTargetId]=useState(""),[targetQuery,setTargetQuery]=useState(""),[targetOpen,setTargetOpen]=useState(false),[note,setNote]=useState(""),[journal,setJournal]=useState<{id:number;code:string}|null>(null)
 const show=(severity:"success"|"error"|"info",detail:string)=>{messagesRef.current?.clear?.();messagesRef.current?.show?.([{severity,summary:"",detail,sticky:true}])}
 const load=useCallback(async()=>{setLoading(true);setJournal(null);try{const p=new URLSearchParams({type:String(view.type)});if(q.trim())p.set("q",q.trim());if(fromDue)p.set("from_due_date",fromDue);if(toDue)p.set("to_due_date",toDue);if(currencyId!=="all")p.set("currency_id",currencyId);if(bankId!=="all")p.set("bank_id",bankId);const r=await fetch(`/api/cheques?${p}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تحميل الشيكات");const eligible=(d.rows||[]).filter((row:Cheque)=>row.allowed_operations?.some(op=>op.code===view.operation));setRows(eligible);setMeta(d.meta||emptyMeta);setSelected(new Set())}catch(e){show("error",e instanceof Error?e.message:"تعذر تحميل الشيكات")}finally{setLoading(false)}},[bankId,currencyId,fromDue,q,toDue,view.operation,view.type])
 useEffect(()=>{void load()},[mode])
 const selectedRows=useMemo(()=>rows.filter(row=>selected.has(row.id)),[rows,selected]),total=selectedRows.reduce((sum,row)=>sum+Number(row.amount||0),0),selectedCurrencies=Array.from(new Set(selectedRows.map(row=>Number(row.currency_id)||0)))
 const targets=mode==="deposit"?meta.bank_accounts:meta.accounts
 const filteredTargets=useMemo(()=>{const term=targetQuery.trim().toLowerCase(),currency=selectedCurrencies.length===1?selectedCurrencies[0]:Number(currencyId)||0;return targets.filter(item=>(!currency||!item.currency_id||Number(item.currency_id)===currency)&&(!term||`${item.code||""} ${item.name||""} ${item.bank_name||""} ${item.branch_name||""}`.toLowerCase().includes(term))).slice(0,30)},[currencyId,selectedCurrencies,targetQuery,targets])
 const toggle=(id:number)=>setSelected(current=>{const next=new Set(current);if(next.has(id)){next.delete(id);return next}const row=rows.find(x=>x.id===id),first=rows.find(x=>next.has(x.id));if(first&&row&&(Number(first.currency_id)!==Number(row.currency_id)||Number(first.voucher_branch_id)!==Number(row.voucher_branch_id))){show("info","اختر شيكات من نفس الفرع والعملة في المجموعة الواحدة");return next}next.add(id);return next})
 const selectableRows=useMemo(()=>{const first=rows[0];return first?rows.filter(row=>Number(row.currency_id)===Number(first.currency_id)&&Number(row.voucher_branch_id)===Number(first.voucher_branch_id)):[]},[rows])
 const allSelected=selectableRows.length>0&&selectableRows.every(row=>selected.has(row.id))
 const toggleAll=()=>{if(allSelected){setSelected(new Set());return}setSelected(new Set(selectableRows.map(row=>row.id)));if(selectableRows.length<rows.length)show("info","تم تحديد الشيكات التابعة لنفس الفرع والعملة فقط")}
 const execute=async()=>{messagesRef.current?.clear?.();if(!selected.size)return show("error","اختر شيكاً واحداً على الأقل");if(selectedCurrencies.length!==1)return show("error","يجب أن تكون الشيكات المحددة من نفس العملة");if(view.targetLabel&&!targetId)return show("error",`يجب اختيار ${view.targetLabel}`);setSaving(true);try{const r=await fetch("/api/cheques/bulk-operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation_code:view.operation,cheque_ids:Array.from(selected),operation_date:operationDate,account_id:targetId?Number(targetId):null,note})}),d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تنفيذ العملية");show("success",d.message);const savedJournal=d.journal_voucher||null;setNote("");setTargetId("");setTargetQuery("");await load();setJournal(savedJournal)}catch(e){show("error",e instanceof Error?e.message:"تعذر تنفيذ العملية")}finally{setSaving(false)}}
 return <main dir="rtl" className="min-h-full bg-slate-50/80 p-3 sm:p-5">
  <div className="mx-auto max-w-[1750px] space-y-4">
   <header className={cn("relative overflow-hidden rounded-[30px] bg-gradient-to-l p-5 text-white shadow-xl sm:p-7",view.gradient)}><div className="absolute -left-16 -top-20 h-60 w-60 rounded-full bg-white/10 blur-3xl"/><div className="relative flex flex-wrap items-center justify-between gap-4"><div className="flex items-start gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white/15 backdrop-blur"><Icon className="h-7 w-7"/></span><div><p className="text-xs font-bold text-white/70">عمليات الشيكات الجماعية</p><h1 className="text-2xl font-black sm:text-3xl">{view.title}</h1><p className="mt-1 max-w-2xl text-sm text-white/75">{view.description}</p></div></div><div className="rounded-2xl bg-black/15 px-5 py-3 text-center backdrop-blur"><small className="text-white/70">المحدد</small><p className="text-2xl font-black">{selected.size} <span className="text-sm">شيكات</span></p></div></div></header>
   <Messages ref={messagesRef}/>
   <section className="rounded-3xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><div className="md:col-span-2 xl:col-span-2"><Label>بحث شامل</Label><div className="relative mt-1"><Search className="absolute right-3 top-3 h-4 w-4 text-slate-400"/><Input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load()} className="pr-9" placeholder="رقم الشيك، العميل، البنك أو السند..."/></div></div><Field label="استحقاق من"><Input type="date" value={fromDue} onChange={e=>setFromDue(e.target.value)}/></Field><Field label="استحقاق إلى"><Input type="date" value={toDue} onChange={e=>setToDue(e.target.value)}/></Field><Field label="العملة"><select value={currencyId} onChange={e=>setCurrencyId(e.target.value)} className="h-10 w-full rounded-md border bg-white px-3"><option value="all">جميع العملات</option>{meta.currencies.map(x=><option key={x.id} value={x.id}>{x.currency_code} — {x.currency_name}</option>)}</select></Field><Field label="البنك"><select value={bankId} onChange={e=>setBankId(e.target.value)} className="h-10 w-full rounded-md border bg-white px-3"><option value="all">جميع البنوك</option>{meta.banks.map(x=><option key={x.id} value={x.id}>{x.name||x.bank_name}</option>)}</select></Field></div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={()=>void load()} disabled={loading} className="bg-slate-900 hover:bg-slate-800">{loading?<Loader2 className="ml-2 h-4 w-4 animate-spin"/>:<Search className="ml-2 h-4 w-4"/>}عرض الشيكات المطابقة</Button><Button variant="outline" onClick={()=>{setQ("");setFromDue("");setToDue("");setCurrencyId("all");setBankId("all")}}><RefreshCcw className="ml-2 h-4 w-4"/>مسح الفلاتر</Button></div></section>
   <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="min-w-0 overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2 border-b p-3"><div><h2 className="font-black">الشيكات المتاحة للعملية</h2><p className="text-xs text-slate-500">تظهر الشيكات التي تسمح حالتها الحالية بتنفيذ العملية فقط.</p></div><Button variant="outline" onClick={toggleAll} disabled={!rows.length}>{allSelected?<X className="ml-2 h-4 w-4"/>:<CheckCheck className="ml-2 h-4 w-4"/>}{allSelected?"إلغاء تحديد الكل":"تحديد الكل"}</Button></div><div className="max-h-[58vh] overflow-auto"><table className="w-full min-w-[980px] text-sm"><thead className="sticky top-0 z-10 bg-slate-900 text-white"><tr><th className="w-14 p-3">تحديد</th>{["رقم الشيك","العميل / المستفيد","المبلغ","العملة","الاستحقاق","البنك والفرع","السند","الحالة"].map(x=><th key={x} className="p-3 text-right text-xs">{x}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id} onClick={()=>toggle(row.id)} className={cn("cursor-pointer border-b transition hover:bg-cyan-50",selected.has(row.id)?"bg-emerald-50 ring-1 ring-inset ring-emerald-300":index%2?"bg-slate-50/60":"")}><td className="p-3 text-center"><span className={cn("inline-grid h-6 w-6 place-items-center rounded-md border",selected.has(row.id)?"border-emerald-600 bg-emerald-600 text-white":"bg-white")}>{selected.has(row.id)&&<Check className="h-4 w-4"/>}</span></td><td className="p-3 font-mono font-black text-cyan-700">{row.cheq_num}</td><td className="p-3"><b>{row.customer_name||row.cheq_owner_name||"—"}</b></td><td className="p-3 font-black text-emerald-700" dir="ltr">{money.format(Number(row.amount))}</td><td className="p-3">{row.currency_code||"—"}</td><td className="p-3" dir="ltr">{String(row.due_date||"").slice(0,10)}</td><td className="p-3"><b>{row.bank_name||row.bank_account_name||row.bank_account||"—"}</b><small className="block text-slate-400">{row.branch_name}</small></td><td className="p-3 font-mono">{row.vch_code||"—"}</td><td className="p-3"><span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800">{row.status_name}</span></td></tr>)}</tbody></table>{!rows.length&&!loading&&<div className="grid h-52 place-items-center text-center text-slate-400"><div><SquareStack className="mx-auto mb-2 h-10 w-10"/><p>لا توجد شيكات تنطبق عليها العملية والفلاتر</p></div></div>}</div></div>
    <aside className="h-fit space-y-4 rounded-3xl bg-slate-950 p-5 text-white shadow-xl xl:sticky xl:top-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-400/15 p-2 text-emerald-300"><FileCheck2/></span><div><h2 className="font-black">تنفيذ المجموعة</h2><p className="text-xs text-slate-400">ينشأ سند قيد واحد للعملية</p></div></div><div className="grid grid-cols-2 gap-2"><div className="rounded-2xl bg-white/[.07] p-3"><small className="text-slate-400">عدد الشيكات</small><p className="text-xl font-black">{selected.size}</p></div><div className="rounded-2xl bg-white/[.07] p-3"><small className="text-slate-400">الإجمالي</small><p className="text-xl font-black text-emerald-300">{money.format(total)}</p></div></div><Field label="تاريخ العملية"><Input type="date" value={operationDate} onChange={e=>setOperationDate(e.target.value)} className="border-white/10 bg-white/10 text-white"/></Field>{view.targetLabel&&<div className="relative" onBlur={()=>setTimeout(()=>setTargetOpen(false),100)}><Label>{view.targetLabel}</Label><Input value={targetQuery} onFocus={()=>setTargetOpen(true)} onChange={e=>{setTargetQuery(e.target.value);setTargetId("");setTargetOpen(true)}} placeholder="ابحث بالرقم أو الاسم..." className="mt-1 border-white/10 bg-white/10 text-white placeholder:text-slate-500"/>{targetOpen&&<div className="absolute z-30 mt-1 max-h-56 w-full overflow-y-auto rounded-xl border bg-white p-1 text-slate-900 shadow-2xl">{filteredTargets.map(item=><button key={item.id} onMouseDown={e=>e.preventDefault()} onClick={()=>{setTargetId(String(item.id));setTargetQuery(`${item.code?item.code+" — ":""}${item.name||item.bank_name||""}`);setTargetOpen(false)}} className="block w-full rounded-lg p-2 text-right text-sm hover:bg-emerald-50"><b>{item.code}</b> {item.name||item.bank_name}<small className="block text-slate-400">{item.branch_name}</small></button>)}{!filteredTargets.length&&<p className="p-3 text-center text-sm text-slate-400">لا توجد نتائج</p>}</div>}</div>}<Field label="ملاحظة / رقم مستند البنك"><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} className="mt-1 w-full rounded-xl border border-white/10 bg-white/10 p-3 text-sm outline-none focus:border-emerald-400"/></Field>{journal&&<a href={`/?section=journal-vouchers&voucher=${journal.id}`} className="block rounded-xl bg-emerald-400/15 p-3 text-sm font-bold text-emerald-300">سند القيد: {journal.code}</a>}<Button onClick={()=>void execute()} disabled={saving||!selected.size} className="h-13 w-full bg-emerald-400 text-base font-black text-slate-950 hover:bg-emerald-300">{saving?<Loader2 className="ml-2 h-5 w-5 animate-spin"/>:<ShieldCheck className="ml-2 h-5 w-5"/>}تنفيذ {view.title}</Button><p className="text-center text-[11px] leading-5 text-slate-500">يتم التحقق من حالة كل شيك مرة أخرى عند الحفظ. عند فشل أي شيك لن تتغير بقية المجموعة.</p></aside>
   </section>
  </div>
 </main>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1"><Label>{label}</Label>{children}</div>}
export function ChequeDepositBulkPage(){return <BulkChequeOperation mode="deposit"/>}
export function ChequeEndorseBulkPage(){return <BulkChequeOperation mode="endorse"/>}
export function OutgoingChequeClearBulkPage(){return <BulkChequeOperation mode="clear_outgoing"/>}
