"use client"
import { useEffect, useMemo, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Paperclip, Plus, Save, Trash2 } from "lucide-react"
import { useAuth } from "@/components/auth/auth-context"
import ProductSearchPopup from "@/components/products/ProductSearchPopup"
import Messages from "@/components/common/Messages"

type Item={product_id:number;product_name:string;quantity:number;price:number;discount:number;minimum_order_quantity:number;unit_id:number|null;store_id:number|null;barcode?:string|null}
export function DraftOrderForm({ onSaved, initialDraft }: { onSaved?: () => void; initialDraft?: any } = {}){
 const {user,activeBranchId}=useAuth(); const [customers,setCustomers]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[templates,setTemplates]=useState<any[]>([]); const [items,setItems]=useState<Item[]>([]),[files,setFiles]=useState<any[]>([]),[message,setMessage]=useState("");
 const [customerSearch,setCustomerSearch]=useState(""); const [customerMenuOpen,setCustomerMenuOpen]=useState(false); const [showProductSearch,setShowProductSearch]=useState(false)
 const [isSaving,setIsSaving]=useState(false); const savingRef=useRef(false); const saveActionRef=useRef<()=>void>(()=>{})
 const messagesRef=useRef<any>(null)
 const [form,setForm]=useState({account_id:"",order_date:new Date().toISOString().slice(0,10),requested_delivery_date:"",deposit_amount:0,notes:"",delivery_address:"",contact_phone:"",priority:"normal",checklist_template_id:""});
 const loadCustomers=async()=>{try{const response=await fetch('/api/accounts?type=2',{cache:'no-store'});if(!response.ok)throw new Error(`Account request failed: ${response.status}`);const data=await response.json();setCustomers(Array.isArray(data)?data:[])}catch(error){console.error('Failed to load draft customer accounts:',error)}}
 useEffect(()=>{void Promise.all([loadCustomers(),fetch('/api/inventory/products').then(r=>r.json()).then(p=>setProducts(Array.isArray(p)?p:p.products||[])),fetch('/api/order-checklists').then(r=>r.json()).then(t=>setTemplates(Array.isArray(t)?t:[]))]);const refresh=()=>{void loadCustomers()};window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh)},[])
 useEffect(()=>{if(!initialDraft)return;setCustomerSearch(String(initialDraft.customer_name||""));setForm({account_id:String(initialDraft.account_id||""),order_date:String(initialDraft.order_date||"").slice(0,10),requested_delivery_date:String(initialDraft.requested_delivery_date||"").slice(0,10),deposit_amount:Number(initialDraft.deposit_amount||0),notes:initialDraft.notes||"",delivery_address:initialDraft.delivery_address||"",contact_phone:initialDraft.contact_phone||"",priority:initialDraft.priority||"normal",checklist_template_id:initialDraft.checklist_template_id?String(initialDraft.checklist_template_id):""});setFiles(Array.isArray(initialDraft.attachments)?initialDraft.attachments:[]);setItems((initialDraft.items||[]).map((item:any)=>({product_id:Number(item.product_id),product_name:item.product_name,quantity:Number(item.quantity),price:Number(item.price),discount:Number(item.discount||0),minimum_order_quantity:Number(item.minimum_order_quantity||0),unit_id:item.unit_id?Number(item.unit_id):null,store_id:item.store_id?Number(item.store_id):null,barcode:item.barcode||null})))},[initialDraft])
 useEffect(()=>{if(!products.length)return;setItems(current=>current.map(item=>({...item,minimum_order_quantity:Number(products.find(product=>Number(product.id)===item.product_id)?.minimum_order_quantity||0)})))},[products])
 const total=useMemo(()=>items.reduce((s,i)=>s+i.quantity*i.price-i.discount,0),[items]);
 const visibleCustomers=useMemo(()=>{const term=customerSearch.trim().toLocaleLowerCase();return customers.filter(customer=>!term||String(customer.account_name||customer.name||"").toLocaleLowerCase().includes(term)||String(customer.account_code||customer.code||"").toLocaleLowerCase().includes(term)).slice(0,50)},[customerSearch,customers])
 const add=(id:string)=>{const p=products.find(x=>String(x.id)===id);if(!p||items.some(i=>i.product_id===p.id))return;const unit=p.units?.[0];setItems([...items,{product_id:p.id,product_name:p.product_name||p.name,quantity:Number(p.minimum_order_quantity||1)||1,price:Number(unit?.price??p.sale_price??p.selling_price??p.first_price??0),discount:0,minimum_order_quantity:Number(p.minimum_order_quantity||0),unit_id:unit?.unit_id?Number(unit.unit_id):null,store_id:p.default_store?Number(p.default_store):null,barcode:unit?.barcode||null}])}
 const selectProducts=(selected:any[])=>{setShowProductSearch(false);setItems(current=>{const next=[...current];for(const product of selected||[]){if(next.some(item=>item.product_id===Number(product.id)))continue;const unit=product.selected_unit||product.units?.[0];next.push({product_id:Number(product.id),product_name:product.product_name||product.name,quantity:Number(product.minimum_order_quantity||1)||1,price:Number(unit?.price??product.first_price??product.sale_price??product.selling_price??0),discount:0,minimum_order_quantity:Number(product.minimum_order_quantity||0),unit_id:unit?.unit_id?Number(unit.unit_id):null,store_id:product.default_store?Number(product.default_store):null,barcode:unit?.barcode||null})}return next})}
 const changeCustomer=(value:string)=>{setCustomerSearch(value);const normalized=value.trim().toLowerCase();const match=customers.find(customer=>String(customer.id)===value||String(customer.account_code||customer.code||"").toLowerCase()===normalized||String(customer.account_name||customer.name||"").toLowerCase()===normalized);setForm(current=>({...current,account_id:match?String(match.id):""}))}
 const selectCustomer=(customer:any)=>{setCustomerSearch(String(customer.account_name||customer.name||""));setForm(current=>({...current,account_id:String(customer.id)}));setCustomerMenuOpen(false)}
 const attach=async(e:React.ChangeEvent<HTMLInputElement>)=>{const selected=Array.from(e.target.files||[]);for(const f of selected){if(f.size>5*1024*1024||!(/^(image\/(jpeg|png|webp)|application\/pdf)$/).test(f.type)){setMessage(`الملف ${f.name} غير مسموح أو أكبر من 5MB`);continue}const data=await new Promise<string>(res=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.readAsDataURL(f)});setFiles(v=>[...v,{name:f.name,type:f.type,size:f.size,data}])}}
 const save=async()=>{if(savingRef.current)return;if(!form.account_id||!form.order_date||!form.requested_delivery_date||!items.length){setMessage("العميل وتاريخ الطلب والتسليم وصنف واحد على الأقل مطلوبة");return}if(form.requested_delivery_date<form.order_date){setMessage("تاريخ التسليم لا يمكن أن يسبق تاريخ الطلب");return}if(!Number.isFinite(form.deposit_amount)||form.deposit_amount<0){setMessage("مبلغ العربون يجب أن يكون صفراً أو أكبر");return}if(form.deposit_amount>total){setMessage("مبلغ العربون لا يمكن أن يتجاوز إجمالي الطلبية");return}setMessage("");const customer=customers.find(c=>String(c.id)===form.account_id);if(!customer){setMessage("اختر حساب عميل صالحاً من القائمة");return}const invalid=items.find(i=>!Number.isFinite(i.quantity)||i.quantity<=0||i.quantity<i.minimum_order_quantity||!Number.isFinite(i.price)||i.price<0||!Number.isFinite(i.discount)||i.discount<0||i.discount>i.quantity*i.price);if(invalid){setMessage(invalid.quantity<invalid.minimum_order_quantity?`الحد الأدنى لطلب ${invalid.product_name} هو ${invalid.minimum_order_quantity}`:`تحقق من الكمية والسعر والخصم للصنف ${invalid.product_name}`);return}savingRef.current=true;setIsSaving(true);try{const r=await fetch(initialDraft?`/api/order-drafts/${initialDraft.id}`:'/api/order-drafts',{method:initialDraft?'PUT':'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...form,account_id:Number(form.account_id),customer_name:customer?.account_name||customer?.name,checklist_template_id:form.checklist_template_id?Number(form.checklist_template_id):null,items,attachments:files,created_by:user?.id,branch_id:activeBranchId})});const contentType=r.headers.get('content-type')||'';const d=contentType.includes('application/json')?await r.json():null;if(!r.ok){setMessage(d?.error||(r.status===404?'مسار حفظ المسودة غير متاح على الخادم؛ أعد تشغيل خادم التطبيق لتحميل API الجديد':`فشل حفظ المسودة (HTTP ${r.status})`));return}if(!d){setMessage("أعاد الخادم استجابة غير صالحة أثناء حفظ المسودة");return}setMessage(initialDraft?'تم تحديث المسودة بنجاح':`تم حفظ المسودة ${d.draft_number}${d.receipt_voucher_id?' وسند قبض العربون':''}`);setItems([]);setFiles([]);onSaved?.()}catch(error){console.error("Failed to save order draft",error);setMessage(error instanceof Error?`تعذر حفظ المسودة: ${error.message}`:"تعذر الاتصال بالخادم أثناء حفظ المسودة")}finally{savingRef.current=false;setIsSaving(false)}}
 saveActionRef.current=()=>{void save()}
 useEffect(()=>{if(!message)return;const success=message.includes("بنجاح")||message.startsWith("تم حفظ");messagesRef.current?.clear?.();messagesRef.current?.show?.([{severity:success?"success":"error",summary:"",detail:message,life:5000}])},[message])
 useEffect(()=>{const handleKeyDown=(event:KeyboardEvent)=>{if(event.key==="F3"){event.preventDefault();event.stopPropagation();saveActionRef.current()}};document.addEventListener("keydown",handleKeyDown,true);return()=>document.removeEventListener("keydown",handleKeyDown,true)},[])
 return <div dir="rtl" className="w-full max-w-none space-y-5 p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">إنشاء مسودة طلبية</h1><p className="text-muted-foreground">تُراجع المسودة قبل تحويلها إلى طلبية مبيعات فعلية.</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-md border bg-muted px-3 py-1 text-xs">F3: حفظ المسودة</span><Button size="lg" onClick={save} disabled={isSaving||!form.account_id||!form.requested_delivery_date||!items.length}><Save className="ml-2 h-4 w-4"/>{isSaving?"جاري الحفظ...":"حفظ المسودة"}</Button></div></div><Messages innerRef={messagesRef}/>
 <Card><CardHeader><CardTitle>بيانات العميل والتسليم</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-3">
 <div className="relative"><Label htmlFor="draft-customer">العميل *</Label><Input id="draft-customer" className="mt-1" value={customerSearch} onFocus={()=>{setCustomerMenuOpen(true);void loadCustomers()}} onChange={event=>{changeCustomer(event.target.value);setCustomerMenuOpen(true)}} onBlur={()=>window.setTimeout(()=>setCustomerMenuOpen(false),150)} placeholder="اكتب اسم أو رقم العميل للبحث..." autoComplete="off"/>{customerMenuOpen&&<div className="absolute z-[100] mt-1 max-h-64 w-full overflow-y-auto rounded-md border bg-background shadow-xl">{visibleCustomers.length?visibleCustomers.map(customer=><button type="button" key={customer.id} className="flex w-full items-center justify-between gap-3 border-b px-3 py-2 text-right hover:bg-muted" onMouseDown={event=>event.preventDefault()} onClick={()=>selectCustomer(customer)}><span>{customer.account_name||customer.name}</span><span className="text-xs text-muted-foreground">{customer.account_code||customer.code||""}</span></button>):<div className="px-3 py-4 text-center text-sm text-muted-foreground">لا توجد نتائج</div>}</div>}</div>
 <div><Label>تاريخ الطلب</Label><Input type="date" value={form.order_date} onChange={e=>setForm({...form,order_date:e.target.value})}/></div><div><Label>التاريخ المطلوب للتسليم *</Label><Input type="date" min={form.order_date} value={form.requested_delivery_date} onChange={e=>setForm({...form,requested_delivery_date:e.target.value})}/></div>
 <div><Label>مبلغ العربون</Label><Input type="number" min="0" step="0.01" value={form.deposit_amount} onFocus={e=>e.currentTarget.select()} onChange={e=>setForm({...form,deposit_amount:Number(e.target.value)})}/></div><div><Label>هاتف التواصل</Label><Input value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></div><div><Label>الأولوية</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="normal">عادية</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></div>
 <div className="md:col-span-2"><Label>عنوان التسليم</Label><Input value={form.delivery_address} onChange={e=>setForm({...form,delivery_address:e.target.value})}/></div><div><Label>قائمة التحقق</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.checklist_template_id} onChange={e=>setForm({...form,checklist_template_id:e.target.value})}><option value="">بدون قائمة</option>{templates.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="md:col-span-3"><Label>ملاحظات</Label><Textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></CardContent></Card>
 <Card><CardHeader><CardTitle className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">الأصناف <Button type="button" onClick={()=>setShowProductSearch(true)}><Plus className="ml-2 h-4 w-4"/>إضافة صنف</Button></CardTitle></CardHeader><CardContent className="space-y-3">{items.map((i,n)=><div key={i.product_id} className="grid items-end gap-3 rounded-lg border p-3 md:grid-cols-6"><div className="md:col-span-2"><Label>الصنف</Label><div>{i.product_name}</div>{i.minimum_order_quantity>0&&<small>الحد الأدنى: {i.minimum_order_quantity}</small>}</div><div><Label>الكمية</Label><Input type="number" step="0.0001" min={i.minimum_order_quantity||0.0001} value={i.quantity} onFocus={e=>e.currentTarget.select()} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,quantity:Number(e.target.value)}:x))}/></div><div><Label>السعر</Label><Input type="number" step="0.01" value={i.price} onFocus={e=>e.currentTarget.select()} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,price:Number(e.target.value)}:x))}/></div><div><Label>الخصم</Label><Input type="number" step="0.01" value={i.discount} onFocus={e=>e.currentTarget.select()} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,discount:Number(e.target.value)}:x))}/></div><Button variant="destructive" onClick={()=>setItems(items.filter((_,k)=>k!==n))}><Trash2 className="h-4 w-4"/></Button></div>)}<div className="text-left text-xl font-bold">الإجمالي: {total.toFixed(2)}</div></CardContent></Card>
 <Card><CardContent className="flex flex-wrap items-center gap-3 pt-6"><label className="inline-flex cursor-pointer items-center gap-2 rounded-md border px-4 py-2"><Paperclip className="h-4 w-4"/>إرفاق صور أو PDF<input hidden type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={attach}/></label>{files.map((f,n)=><span key={n} className="rounded bg-muted px-2 py-1 text-sm">{f.name}</span>)}</CardContent></Card><ProductSearchPopup visible={showProductSearch} onClose={()=>setShowProductSearch(false)} onSelect={selectProducts} priceCategoryId={1} ShowSelect={true} searchText="" productTypes={[1]}/></div>
}
