"use client"
import { useEffect, useMemo, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Paperclip, Plus, Save, Trash2 } from "lucide-react"
import { useAuth } from "@/components/auth/auth-context"
import ProductSearchPopup from "@/components/products/ProductSearchPopup"

type Item={product_id:number;product_name:string;quantity:number;price:number;discount:number;minimum_order_quantity:number}
export function DraftOrderForm({ onSaved, initialDraft }: { onSaved?: () => void; initialDraft?: any } = {}){
 const {user,activeBranchId}=useAuth(); const [customers,setCustomers]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[templates,setTemplates]=useState<any[]>([]); const [items,setItems]=useState<Item[]>([]),[files,setFiles]=useState<any[]>([]),[message,setMessage]=useState("");
 const [customerSearch,setCustomerSearch]=useState(""); const [showProductSearch,setShowProductSearch]=useState(false)
 const [isSaving,setIsSaving]=useState(false); const savingRef=useRef(false); const saveActionRef=useRef<()=>void>(()=>{})
 const [form,setForm]=useState({customer_id:"",order_date:new Date().toISOString().slice(0,10),requested_delivery_date:"",deposit_amount:0,notes:"",delivery_address:"",contact_phone:"",priority:"normal",checklist_template_id:""});
 useEffect(()=>{Promise.all([fetch('/api/customers').then(r=>r.json()),fetch('/api/inventory/products').then(r=>r.json()),fetch('/api/order-checklists').then(r=>r.json())]).then(([c,p,t])=>{setCustomers(Array.isArray(c)?c:c.customers||[]);setProducts(Array.isArray(p)?p:p.products||[]);setTemplates(Array.isArray(t)?t:[])})},[])
 useEffect(()=>{if(!initialDraft)return;setCustomerSearch(String(initialDraft.customer_name||""));setForm({customer_id:String(initialDraft.customer_id||""),order_date:String(initialDraft.order_date||"").slice(0,10),requested_delivery_date:String(initialDraft.requested_delivery_date||"").slice(0,10),deposit_amount:Number(initialDraft.deposit_amount||0),notes:initialDraft.notes||"",delivery_address:initialDraft.delivery_address||"",contact_phone:initialDraft.contact_phone||"",priority:initialDraft.priority||"normal",checklist_template_id:initialDraft.checklist_template_id?String(initialDraft.checklist_template_id):""});setFiles(Array.isArray(initialDraft.attachments)?initialDraft.attachments:[]);setItems((initialDraft.items||[]).map((item:any)=>({product_id:Number(item.product_id),product_name:item.product_name,quantity:Number(item.quantity),price:Number(item.price),discount:Number(item.discount||0),minimum_order_quantity:Number(item.minimum_order_quantity||0)})))},[initialDraft])
 useEffect(()=>{if(!products.length)return;setItems(current=>current.map(item=>({...item,minimum_order_quantity:Number(products.find(product=>Number(product.id)===item.product_id)?.minimum_order_quantity||0)})))},[products])
 const total=useMemo(()=>items.reduce((s,i)=>s+i.quantity*i.price-i.discount,0),[items]);
 const add=(id:string)=>{const p=products.find(x=>String(x.id)===id);if(!p||items.some(i=>i.product_id===p.id))return;setItems([...items,{product_id:p.id,product_name:p.product_name||p.name,quantity:Number(p.minimum_order_quantity||1)||1,price:Number(p.sale_price||p.selling_price||p.first_price||0),discount:0,minimum_order_quantity:Number(p.minimum_order_quantity||0)}])}
 const selectProducts=(selected:any[])=>{setShowProductSearch(false);setItems(current=>{const next=[...current];for(const product of selected||[]){if(next.some(item=>item.product_id===Number(product.id)))continue;const unit=product.selected_unit||product.units?.[0];next.push({product_id:Number(product.id),product_name:product.product_name||product.name,quantity:Number(product.minimum_order_quantity||1)||1,price:Number(unit?.price??product.first_price??product.sale_price??product.selling_price??0),discount:0,minimum_order_quantity:Number(product.minimum_order_quantity||0)})}return next})}
 const changeCustomer=(value:string)=>{setCustomerSearch(value);const normalized=value.trim().toLowerCase();const match=customers.find(customer=>String(customer.id)===value||String(customer.customer_code||"").toLowerCase()===normalized||String(customer.customer_name||customer.name||"").toLowerCase()===normalized);setForm(current=>({...current,customer_id:match?String(match.id):"",contact_phone:match?.mobile1||match?.customer_mobile||current.contact_phone}))}
 const attach=async(e:React.ChangeEvent<HTMLInputElement>)=>{const selected=Array.from(e.target.files||[]);for(const f of selected){if(f.size>5*1024*1024||!(/^(image\/(jpeg|png|webp)|application\/pdf)$/).test(f.type)){setMessage(`الملف ${f.name} غير مسموح أو أكبر من 5MB`);continue}const data=await new Promise<string>(res=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.readAsDataURL(f)});setFiles(v=>[...v,{name:f.name,type:f.type,size:f.size,data}])}}
 const save=async()=>{if(savingRef.current)return;if(!form.customer_id||!form.requested_delivery_date||!items.length){setMessage("العميل وتاريخ التسليم وصنف واحد على الأقل مطلوبة");return}setMessage("");const customer=customers.find(c=>String(c.id)===form.customer_id);const invalid=items.find(i=>i.quantity<i.minimum_order_quantity);if(invalid){setMessage(`الحد الأدنى لطلب ${invalid.product_name} هو ${invalid.minimum_order_quantity}`);return}savingRef.current=true;setIsSaving(true);try{const r=await fetch(initialDraft?`/api/order-drafts/${initialDraft.id}`:'/api/order-drafts',{method:initialDraft?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,customer_id:Number(form.customer_id),customer_name:customer?.customer_name||customer?.name,checklist_template_id:form.checklist_template_id?Number(form.checklist_template_id):null,items,attachments:files,created_by:user?.id,branch_id:activeBranchId})});const d=await r.json();if(!r.ok){setMessage(d.error);return}setMessage(initialDraft?'تم تحديث المسودة بنجاح':`تم حفظ المسودة ${d.draft_number}`);setItems([]);setFiles([]);onSaved?.()}catch(error){setMessage("تعذر الاتصال بالخادم أثناء حفظ المسودة")}finally{savingRef.current=false;setIsSaving(false)}}
 saveActionRef.current=()=>{void save()}
 useEffect(()=>{const handleKeyDown=(event:KeyboardEvent)=>{if(event.key==="F3"){event.preventDefault();event.stopPropagation();saveActionRef.current()}};document.addEventListener("keydown",handleKeyDown,true);return()=>document.removeEventListener("keydown",handleKeyDown,true)},[])
 return <div dir="rtl" className="w-full max-w-none space-y-5 p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="text-2xl font-bold">إنشاء مسودة طلبية</h1><p className="text-muted-foreground">تُراجع المسودة قبل تحويلها إلى طلبية مبيعات فعلية.</p></div><span className="rounded-md border bg-muted px-3 py-1 text-xs">F3: حفظ المسودة</span></div>{message&&<div className="rounded-lg border bg-muted p-3">{message}</div>}
 <Card><CardHeader><CardTitle>بيانات العميل والتسليم</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-3">
 <div><Label htmlFor="draft-customer">العميل *</Label><Input id="draft-customer" className="mt-1" list="draft-customer-options" value={customerSearch} onChange={event=>changeCustomer(event.target.value)} placeholder="اكتب اسم أو رقم العميل للبحث..." autoComplete="off"/><datalist id="draft-customer-options">{customers.map(customer=><option key={customer.id} value={customer.customer_name||customer.name}>{customer.customer_code ? `${customer.customer_code} - ` : ""}{customer.customer_name||customer.name}</option>)}</datalist></div>
 <div><Label>تاريخ الطلب</Label><Input type="date" value={form.order_date} onChange={e=>setForm({...form,order_date:e.target.value})}/></div><div><Label>التاريخ المطلوب للتسليم *</Label><Input type="date" min={form.order_date} value={form.requested_delivery_date} onChange={e=>setForm({...form,requested_delivery_date:e.target.value})}/></div>
 <div><Label>مبلغ العربون</Label><Input type="number" min="0" step="0.01" value={form.deposit_amount} onChange={e=>setForm({...form,deposit_amount:Number(e.target.value)})}/></div><div><Label>هاتف التواصل</Label><Input value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></div><div><Label>الأولوية</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="normal">عادية</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></div>
 <div className="md:col-span-2"><Label>عنوان التسليم</Label><Input value={form.delivery_address} onChange={e=>setForm({...form,delivery_address:e.target.value})}/></div><div><Label>قائمة التحقق</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.checklist_template_id} onChange={e=>setForm({...form,checklist_template_id:e.target.value})}><option value="">بدون قائمة</option>{templates.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="md:col-span-3"><Label>ملاحظات</Label><Textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></CardContent></Card>
 <Card><CardHeader><CardTitle className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">الأصناف <Button type="button" onClick={()=>setShowProductSearch(true)}><Plus className="ml-2 h-4 w-4"/>إضافة صنف</Button></CardTitle></CardHeader><CardContent className="space-y-3">{items.map((i,n)=><div key={i.product_id} className="grid items-end gap-3 rounded-lg border p-3 md:grid-cols-6"><div className="md:col-span-2"><Label>الصنف</Label><div>{i.product_name}</div>{i.minimum_order_quantity>0&&<small>الحد الأدنى: {i.minimum_order_quantity}</small>}</div><div><Label>الكمية</Label><Input type="number" step="0.0001" min={i.minimum_order_quantity||0.0001} value={i.quantity} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,quantity:Number(e.target.value)}:x))}/></div><div><Label>السعر</Label><Input type="number" step="0.01" value={i.price} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,price:Number(e.target.value)}:x))}/></div><div><Label>الخصم</Label><Input type="number" step="0.01" value={i.discount} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,discount:Number(e.target.value)}:x))}/></div><Button variant="destructive" onClick={()=>setItems(items.filter((_,k)=>k!==n))}><Trash2 className="h-4 w-4"/></Button></div>)}<div className="text-left text-xl font-bold">الإجمالي: {total.toFixed(2)}</div></CardContent></Card>
 <Card><CardContent className="flex flex-wrap items-center gap-3 pt-6"><label className="inline-flex cursor-pointer items-center gap-2 rounded-md border px-4 py-2"><Paperclip className="h-4 w-4"/>إرفاق صور أو PDF<input hidden type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={attach}/></label>{files.map((f,n)=><span key={n} className="rounded bg-muted px-2 py-1 text-sm">{f.name}</span>)}</CardContent></Card><Button size="lg" onClick={save} disabled={isSaving||!form.customer_id||!form.requested_delivery_date||!items.length}><Save className="ml-2 h-4 w-4"/>{isSaving?"جاري الحفظ...":"حفظ المسودة"}</Button><ProductSearchPopup visible={showProductSearch} onClose={()=>setShowProductSearch(false)} onSelect={selectProducts} priceCategoryId={1} ShowSelect={true} searchText="" productTypes={[1]}/></div>
}
