"use client"
import { useEffect, useMemo, useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Paperclip, Plus, Save, Trash2 } from "lucide-react"
import { useAuth } from "@/components/auth/auth-context"

type Item={product_id:number;product_name:string;quantity:number;price:number;discount:number;minimum_order_quantity:number}
export function DraftOrderForm({ onSaved }: { onSaved?: () => void } = {}){
 const {user,activeBranchId}=useAuth(); const [customers,setCustomers]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[templates,setTemplates]=useState<any[]>([]); const [items,setItems]=useState<Item[]>([]),[files,setFiles]=useState<any[]>([]),[message,setMessage]=useState("");
 const [form,setForm]=useState({customer_id:"",order_date:new Date().toISOString().slice(0,10),requested_delivery_date:"",deposit_amount:0,notes:"",delivery_address:"",contact_phone:"",priority:"normal",checklist_template_id:""});
 useEffect(()=>{Promise.all([fetch('/api/customers').then(r=>r.json()),fetch('/api/inventory/products').then(r=>r.json()),fetch('/api/order-checklists').then(r=>r.json())]).then(([c,p,t])=>{setCustomers(Array.isArray(c)?c:c.customers||[]);setProducts(Array.isArray(p)?p:p.products||[]);setTemplates(Array.isArray(t)?t:[])})},[])
 const total=useMemo(()=>items.reduce((s,i)=>s+i.quantity*i.price-i.discount,0),[items]);
 const add=(id:string)=>{const p=products.find(x=>String(x.id)===id);if(!p||items.some(i=>i.product_id===p.id))return;setItems([...items,{product_id:p.id,product_name:p.product_name||p.name,quantity:Number(p.minimum_order_quantity||1)||1,price:Number(p.sale_price||p.selling_price||p.first_price||0),discount:0,minimum_order_quantity:Number(p.minimum_order_quantity||0)}])}
 const attach=async(e:React.ChangeEvent<HTMLInputElement>)=>{const selected=Array.from(e.target.files||[]);for(const f of selected){if(f.size>5*1024*1024||!(/^(image\/(jpeg|png|webp)|application\/pdf)$/).test(f.type)){setMessage(`الملف ${f.name} غير مسموح أو أكبر من 5MB`);continue}const data=await new Promise<string>(res=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.readAsDataURL(f)});setFiles(v=>[...v,{name:f.name,type:f.type,size:f.size,data}])}}
 const save=async()=>{setMessage("");const customer=customers.find(c=>String(c.id)===form.customer_id);const invalid=items.find(i=>i.quantity<i.minimum_order_quantity);if(invalid){setMessage(`الحد الأدنى لطلب ${invalid.product_name} هو ${invalid.minimum_order_quantity}`);return}const r=await fetch('/api/order-drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,customer_id:Number(form.customer_id),customer_name:customer?.customer_name||customer?.name,checklist_template_id:form.checklist_template_id?Number(form.checklist_template_id):null,items,attachments:files,created_by:user?.id,branch_id:activeBranchId})});const d=await r.json();if(!r.ok){setMessage(d.error);return}setMessage(`تم حفظ المسودة ${d.draft_number}`);setItems([]);setFiles([]);onSaved?.()}
 return <div dir="rtl" className="w-full max-w-none space-y-5 p-4 sm:p-6"><div><h1 className="text-2xl font-bold">إنشاء مسودة طلبية</h1><p className="text-muted-foreground">تُراجع المسودة قبل تحويلها إلى طلبية مبيعات فعلية.</p></div>{message&&<div className="rounded-lg border bg-muted p-3">{message}</div>}
 <Card><CardHeader><CardTitle>بيانات العميل والتسليم</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-3">
 <div><Label>العميل *</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">اختر العميل</option>{customers.map(c=><option key={c.id} value={c.id}>{c.customer_name||c.name}</option>)}</select></div>
 <div><Label>تاريخ الطلب</Label><Input type="date" value={form.order_date} onChange={e=>setForm({...form,order_date:e.target.value})}/></div><div><Label>التاريخ المطلوب للتسليم *</Label><Input type="date" min={form.order_date} value={form.requested_delivery_date} onChange={e=>setForm({...form,requested_delivery_date:e.target.value})}/></div>
 <div><Label>مبلغ العربون</Label><Input type="number" min="0" step="0.01" value={form.deposit_amount} onChange={e=>setForm({...form,deposit_amount:Number(e.target.value)})}/></div><div><Label>هاتف التواصل</Label><Input value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></div><div><Label>الأولوية</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="normal">عادية</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></div>
 <div className="md:col-span-2"><Label>عنوان التسليم</Label><Input value={form.delivery_address} onChange={e=>setForm({...form,delivery_address:e.target.value})}/></div><div><Label>قائمة التحقق</Label><select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.checklist_template_id} onChange={e=>setForm({...form,checklist_template_id:e.target.value})}><option value="">بدون قائمة</option>{templates.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="md:col-span-3"><Label>ملاحظات</Label><Textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center justify-between">الأصناف <select className="h-10 max-w-sm rounded-md border bg-background px-3 text-sm font-normal" value="" onChange={e=>add(e.target.value)}><option value="">+ إضافة صنف</option>{products.map(p=><option key={p.id} value={p.id}>{p.product_name||p.name}</option>)}</select></CardTitle></CardHeader><CardContent className="space-y-3">{items.map((i,n)=><div key={i.product_id} className="grid items-end gap-3 rounded-lg border p-3 md:grid-cols-6"><div className="md:col-span-2"><Label>الصنف</Label><div>{i.product_name}</div>{i.minimum_order_quantity>0&&<small>الحد الأدنى: {i.minimum_order_quantity}</small>}</div><div><Label>الكمية</Label><Input type="number" step="0.0001" min={i.minimum_order_quantity||0.0001} value={i.quantity} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,quantity:Number(e.target.value)}:x))}/></div><div><Label>السعر</Label><Input type="number" step="0.01" value={i.price} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,price:Number(e.target.value)}:x))}/></div><div><Label>الخصم</Label><Input type="number" step="0.01" value={i.discount} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,discount:Number(e.target.value)}:x))}/></div><Button variant="destructive" onClick={()=>setItems(items.filter((_,k)=>k!==n))}><Trash2 className="h-4 w-4"/></Button></div>)}<div className="text-left text-xl font-bold">الإجمالي: {total.toFixed(2)}</div></CardContent></Card>
 <Card><CardContent className="flex flex-wrap items-center gap-3 pt-6"><label className="inline-flex cursor-pointer items-center gap-2 rounded-md border px-4 py-2"><Paperclip className="h-4 w-4"/>إرفاق صور أو PDF<input hidden type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={attach}/></label>{files.map((f,n)=><span key={n} className="rounded bg-muted px-2 py-1 text-sm">{f.name}</span>)}</CardContent></Card><Button size="lg" onClick={save} disabled={!form.customer_id||!form.requested_delivery_date||!items.length}><Save className="ml-2 h-4 w-4"/>حفظ المسودة</Button></div>
}
