"use client"
import { useCallback,useEffect,useMemo,useRef,useState } from "react"
import { Pencil,Plus,RefreshCw } from "lucide-react"
import Messages from "@/components/common/Messages"
import { Button } from "@/components/ui/button"
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "@/components/ui/dialog"
import { FilterBar,Grid,HrPage,SalaryItemFields,type Column } from "./hr-shared"

type Item={id?:number;code:string;name:string;other_name:string;item_type:string;calculation_type:string;calculation_method:string;amount_period:string;add_to_total_salary:boolean;default_amount:number;taxable:boolean;account_code:string;is_active:boolean}
const blank=():Item=>({code:"",name:"",other_name:"",item_type:"basic_salary",calculation_type:"fixed",calculation_method:"fixed",amount_period:"monthly",add_to_total_salary:true,default_amount:0,taxable:true,account_code:"",is_active:true})
const normalized=(item:Item):Item=>({...blank(),...item,calculation_method:item.calculation_method||(["fixed","percentage"].includes(item.calculation_type)?item.calculation_type:"fixed"),amount_period:item.amount_period||(["monthly","daily"].includes(item.calculation_type)?item.calculation_type:"monthly")})

export function EmployeeSalaryItemsPage(){
 const [rows,setRows]=useState<Item[]>([]),[selected,setSelected]=useState<Item|null>(null),[form,setForm]=useState<Item>(blank()),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[search,setSearch]=useState("");const messages=useRef<any>(null),nameRef=useRef<HTMLInputElement>(null)
 const load=useCallback(async()=>{const r=await fetch("/api/hr/salary-items");setRows(r.ok?await r.json():[])},[]);useEffect(()=>{void load()},[load])
 const show=(item?:Item)=>{const n=Math.max(0,...rows.map(x=>Number(String(x.code||"").match(/\d+$/)?.[0]||0)))+1;setForm(item?normalized(item):{...blank(),code:`SI${String(n).padStart(4,"0")}`});setOpen(true);requestAnimationFrame(()=>nameRef.current?.focus())}
 const error=(detail:string)=>{messages.current?.clear?.();messages.current?.show?.([{severity:"error",summary:"",detail,life:5000}])}
 const save=async()=>{if(!form.name.trim()||!form.other_name.trim())return error("الاسم العربي والإنجليزي مطلوبان");if(form.calculation_method==="percentage"&&(form.default_amount<0||form.default_amount>100))return error("النسبة يجب أن تكون أقل من أو تساوي 100");if(!form.account_code)return error("الحساب المحاسبي مطلوب");setSaving(true);const r=await fetch("/api/hr/salary-items",{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,calculation_type:form.calculation_method})});if(r.ok){await load();setOpen(false);setSelected(null)}else error((await r.json()).error||"تعذر الحفظ");setSaving(false)}
 const filtered=rows.filter(x=>`${x.code} ${x.name} ${x.other_name}`.toLowerCase().includes(search.toLowerCase()))
 const columns=useMemo<Column[]>(()=>[{key:"code",label:"الرمز",width:105},{key:"name",label:"اسم البند",width:"*"},{key:"item_type",label:"النوع",format:v=>v==="basic_salary"?"الراتب الأساسي":v==="earning"?"إضافة على الراتب":"خصم من الراتب"},{key:"calculation_method",label:"طريقة الاحتساب",format:(v,r)=>(v||r.calculation_type)==="percentage"?"نسبة":"مبلغ ثابت"},{key:"amount_period",label:"نوع المبلغ",format:(v,r)=>(v||r.calculation_type)==="daily"?"يومي":"شهري"},{key:"default_amount",label:"القيمة",type:"number"},{key:"taxable",label:"خاضع للضريبة",type:"boolean"},{key:"is_active",label:"فعال",type:"boolean"}],[])
 return <HrPage title="بنود الراتب" subtitle="الموظفين والرواتب"><div className="flex justify-end gap-2"><Button onClick={()=>show()}><Plus className="ml-2 h-4 w-4"/>جديد</Button><Button variant="outline" disabled={!selected} onClick={()=>selected&&show(selected)}><Pencil className="ml-2 h-4 w-4"/>تعديل</Button><Button variant="outline" onClick={()=>void load()}><RefreshCw className="ml-2 h-4 w-4"/>تحديث</Button></div><FilterBar search={search} onSearch={setSearch} count={filtered.length}/><Grid rows={filtered} columns={columns} rowSelection onSelect={setSelected} onDoubleClick={row=>show(row)}/>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto p-0" dir="rtl"><DialogHeader className="border-b bg-slate-50 px-5 py-4"><DialogTitle className="text-right">بنود الراتب {!form.id&&<span className="text-red-600">(إضافة)</span>}</DialogTitle></DialogHeader><Messages innerRef={messages}/><SalaryItemFields value={form} onChange={setForm} nameRef={nameRef}/><div className="flex justify-end gap-2 border-t p-4"><Button variant="outline" onClick={()=>setOpen(false)}>إلغاء</Button><Button onClick={()=>void save()} disabled={saving}>{saving?"جاري الحفظ...":"حفظ"}</Button></div></DialogContent></Dialog></HrPage>
}
