"use client"
import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { UniversalToolbar } from "@/components/ui/universal-toolbar"
import Messages from "@/components/common/Messages"
import { FileBadge, Percent, Plus, WalletCards } from "lucide-react"
import { FilterBar, Grid, HrPage, inputClass, selectClass, type Column } from "./hr-shared"
import { useWorkspace } from "@/contexts/workspace-context"

type Exemption = { id?: number; name: string; other_name: string; tax_law_id: string | number; tax_law_name?: string; exemption_nature: string; exemption_value_type: string; annual_amount: number; max_amount: number; max_amount_type: string; is_active: boolean }
const blank = (): Exemption => ({ name: "", other_name: "", tax_law_id: "", exemption_nature: "personal", exemption_value_type: "amount", annual_amount: 0, max_amount: 0, max_amount_type: "amount", is_active: true })

export function TaxExemptionsPage() {
  const { fullscreenEnabled } = useWorkspace()
  const [rows, setRows] = useState<Exemption[]>([]), [laws, setLaws] = useState<any[]>([]), [form, setForm] = useState<Exemption>(blank()), [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [search, setSearch] = useState("")
  const messages = useRef<any>(null), nameRef = useRef<HTMLInputElement>(null)
  const load = useCallback(async () => { const [itemsResponse, lookupResponse] = await Promise.all([fetch("/api/hr/tax-exemptions"), fetch("/api/hr/lookups")]); const lookups = lookupResponse.ok ? await lookupResponse.json() : {}; const taxLaws = lookups.taxLaws || []; setLaws(taxLaws); if (itemsResponse.ok) setRows((await itemsResponse.json()).map((item: any) => ({ ...item, tax_law_name: taxLaws.find((law: any) => Number(law.id) === Number(item.tax_law_id))?.name || "" }))) }, [])
  useEffect(() => { void load() }, [load])
  const show = (item?: Exemption) => { setForm(item ? { ...item } : { ...blank(), tax_law_id: laws[0]?.id || "" }); setOpen(true); requestAnimationFrame(() => nameRef.current?.focus()) }
  const notify = (detail: string) => messages.current?.show?.([{ severity: "error", summary: "", detail, life: 5000 }])
  const save = async () => { if (!form.name.trim() || !form.other_name.trim()) return notify("يجب إدخال الاسم العربي والإنجليزي"); if (!form.tax_law_id) return notify("يجب اختيار قانون الضريبة"); if (!form.exemption_nature) return notify("يجب اختيار طبيعة الإعفاء"); setSaving(true); const response = await fetch("/api/hr/tax-exemptions", { method: form.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (response.ok) { await load(); setOpen(false) } else notify((await response.json()).error || "تعذر حفظ الإعفاء الضريبي"); setSaving(false) }
  const index = rows.findIndex(item => item.id === form.id), filtered = rows.filter(item => `${item.name} ${item.other_name} ${item.tax_law_name}`.toLowerCase().includes(search.toLowerCase()))
  const columns: Column[] = useMemo(() => [{ key: "name", label: "الاسم (ar)" }, { key: "other_name", label: "الاسم (en)" }, { key: "tax_law_name", label: "قانون الضريبة" }, { key: "exemption_nature", label: "طبيعة الإعفاء", format: value => ({ personal: "شخصي", transportation: "مواصلات", education: "تعليم", housing: "سكن" }[value as string] || value) }, { key: "exemption_value_type", label: "نوع الإعفاء", format: value => value === "percentage" ? "نسبة" : "مبلغ" }, { key: "annual_amount", label: "قيمة الإعفاء", type: "number" }], [])
  const nav = (target: number) => rows[target] && show(rows[target])
  const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <div><Label className="mb-2 block">{label}</Label>{children}</div>
  return <HrPage title="الإعفاءات الضريبية" subtitle="تعريف وإدارة الإعفاءات المرتبطة بقوانين ضريبة الدخل">
    <div className="grid gap-3 md:grid-cols-3"><Summary title="إجمالي الإعفاءات" value={rows.length} icon={FileBadge} color="from-blue-500 to-blue-600" /><Summary title="إعفاءات بمبلغ" value={rows.filter(item => item.exemption_value_type === "amount").length} icon={WalletCards} color="from-emerald-500 to-green-500" /><Summary title="إعفاءات بنسبة" value={rows.filter(item => item.exemption_value_type === "percentage").length} icon={Percent} color="from-purple-500 to-fuchsia-500" /></div>
    <div className="flex justify-end"><Button onClick={() => show()}><Plus className="ml-2 h-4 w-4" />إضافة إعفاء ضريبي</Button></div><FilterBar search={search} onSearch={setSearch} count={filtered.length} /><Grid rows={filtered} columns={columns} onDoubleClick={show} />
    <Dialog open={open} onOpenChange={setOpen}><DialogContent inline={fullscreenEnabled && open} className="max-h-[94vh] max-w-3xl overflow-y-auto p-0" dir="rtl"><UniversalToolbar currentRecord={index + 1} totalRecords={rows.length} onNew={() => show()} onSave={save} onFirst={() => nav(0)} onPrevious={() => nav(Math.max(0, index - 1))} onNext={() => nav(Math.min(rows.length - 1, index + 1))} onLast={() => nav(rows.length - 1)} isSaving={saving} /><div className="bg-slate-50 p-5"><Messages innerRef={messages} /><DialogHeader className="mb-4"><DialogTitle className="text-right">الإعفاء الضريبي {!form.id && <span className="text-red-600">(إضافة)</span>}</DialogTitle></DialogHeader><Card><CardContent className="grid gap-4 p-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label className="mb-2 block">الاسم (ar) *</Label><Input ref={nameRef} className={inputClass} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} onBlur={() => !form.other_name && setForm(current => ({ ...current, other_name: current.name }))} /></div><div className="sm:col-span-2"><Label className="mb-2 block">الاسم (en) *</Label><Input className={inputClass} value={form.other_name} onChange={event => setForm({ ...form, other_name: event.target.value })} /></div><div className="sm:col-span-2"><Field label="قانون الضريبة *"><select className={selectClass} value={form.tax_law_id} onChange={event => setForm({ ...form, tax_law_id: event.target.value })}><option value="">اختر</option>{laws.map(law => <option key={law.id} value={law.id}>{law.name}</option>)}</select></Field></div><div className="sm:col-span-2"><Field label="طبيعة الإعفاء *"><select className={selectClass} value={form.exemption_nature} onChange={event => setForm({ ...form, exemption_nature: event.target.value })}><option value="personal">شخصي</option><option value="transportation">مواصلات</option><option value="education">تعليم</option><option value="housing">سكن</option></select></Field></div><Field label="نوع الإعفاء *"><select className={selectClass} value={form.exemption_value_type} onChange={event => setForm({ ...form, exemption_value_type: event.target.value })}><option value="amount">مبلغ</option><option value="percentage">نسبة</option></select></Field><Field label="قيمة الإعفاء *"><Input className={inputClass} type="number" value={form.annual_amount} onChange={event => setForm({ ...form, annual_amount: Number(event.target.value) })} /></Field><Field label="الحد الأعلى للإعفاء *"><Input className={inputClass} type="number" value={form.max_amount} onChange={event => setForm({ ...form, max_amount: Number(event.target.value) })} /></Field><Field label="نوع الحد الأعلى *"><select className={selectClass} value={form.max_amount_type} onChange={event => setForm({ ...form, max_amount_type: event.target.value })}><option value="amount">مبلغ</option><option value="percentage">نسبة</option></select></Field></CardContent></Card></div></DialogContent></Dialog>
  </HrPage>
}
function Summary({ title, value, icon: Icon, color }: { title: string; value: number; icon: any; color: string }) { return <Card className={`border-0 bg-gradient-to-br ${color} text-white`}><CardContent className="flex items-center justify-between p-5"><div><p className="text-white/80">{title}</p><p className="text-3xl font-bold">{value}</p></div><Icon className="h-10 w-10 text-white/70" /></CardContent></Card> }
